// Code generated by scripts/generate-foundation-workspace-snapshot-cleanup.ts; DO NOT EDIT.

package coordination

const (
	WorkspaceSnapshotCleanupProfileID      = "foundationWorkspaceSnapshotCleanup/v1alpha1"
	WorkspaceSnapshotCleanupProfileDigest  = "sha256:6157975f3a02c036472fca30bb309fcdee757c2cc99d04a0f053bb7cfd064f69"
	WorkspaceSnapshotCleanupRegistryDigest = "sha256:08450e3a84a4ede0ffc7c56d87cfbd1d52e44ebbb9c16a1d4042fdac0cf4bcb1"
)
