// Code generated by scripts/generate-foundation-workspace-snapshot.ts; DO NOT EDIT.

package coordination

const (
	WorkspaceSnapshotProfileID      = "foundationWorkspaceSnapshot/v1alpha1"
	WorkspaceSnapshotProfileDigest  = "sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f"
	WorkspaceSnapshotRegistryDigest = "sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94"
)
