// Code generated by scripts/generate-foundation-coordination.ts; DO NOT EDIT.

package coordination

const (
	SandboxLifecycleProfileID      = "foundationSandboxLifecycle/v1alpha1"
	SandboxLifecycleProfileDigest  = "sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b"
	SandboxLifecycleRegistryDigest = "sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c"
)
