// Code generated by scripts/generate-platform-durable-coordination-go.ts; DO NOT EDIT.

package coordination

const (
	RegistryDigest     = "sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a"
	StateMachineDigest = "sha256:5c4fa5c0cfac253b45a41c2e49ee7e863b9efbe124e5d743e041f5e01f5c6f15"
	PolicyDigest       = "sha256:95023973eb007a958a3c5aea3ac61b6caa7cd8955b9a24fcef3ad269230c64e8"
)

var managedAgentCreateProjectProfile = operationProfile{
	profileID:                 "managedAgentCreateProject/v1alpha1",
	profileDigest:             "sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308",
	operationID:               "managedAgentCreateProject",
	projectionSchemaID:        "https://schemas.cloud-agents.dev/platform/v1alpha1/schemas/managed-agent-create-project-idempotency-projection.schema.json",
	canonicalizationProfile:   "cloud-agents-http-idempotency/managedAgentCreateProject/v1alpha1",
	canonicalizationAlgorithm: "RFC8785",
	digestAlgorithm:           "SHA-256",
	tenantSource:              "path.tenantId",
	scopeSource:               "body.organizationRef",
	scopeIdentitySchemaID:     "https://schemas.cloud-agents.dev/platform/v1alpha1/schemas/managed-agent-create-project-organization-ref.schema.json",
	scopeIdentifierProfile:    "cloud-agents-authorization-scope-identifier/ascii-v1",
	scopeIdentityComparison:   "exact_string_no_rewrite",
	requiredPermission:        "projects.create",
	requiredScopeLevel:        "organization",
	outboxEventClass:          "resource_change",
	resultResourceKind:        "project",
	replayTTLSeconds:          86400,
	createsPlatformOperation:  false,
	externalSideEffectAllowed: false,
}
