// Code generated by scripts/generate-platform-durable-coordination-go-v2.ts; DO NOT EDIT.

package coordination

const (
	DurableProjectCreateRegistryDigest     = "sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8"
	DurableProjectCreateStateMachineDigest = "sha256:5c4fa5c0cfac253b45a41c2e49ee7e863b9efbe124e5d743e041f5e01f5c6f15"
	DurableProjectCreatePolicyDigest       = "sha256:95023973eb007a958a3c5aea3ac61b6caa7cd8955b9a24fcef3ad269230c64e8"
)

var managedAgentCreateProjectDurableProfile = operationProfile{
	profileID:                 "managedAgentCreateProjectDurable/v1alpha1",
	profileDigest:             "sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f",
	operationID:               "managedAgentCreateProjectDurable",
	projectionSchemaID:        "https://schemas.cloud-agents.dev/platform/v1alpha1/schemas/durable-project-create-idempotency-projection.schema.json",
	canonicalizationProfile:   "cloud-agents-http-idempotency/managedAgentCreateProjectDurable/v1alpha1",
	canonicalizationAlgorithm: "RFC8785",
	digestAlgorithm:           "SHA-256",
	tenantSource:              "path.tenantId",
	scopeSource:               "body.organizationRef",
	scopeIdentitySchemaID:     "https://schemas.cloud-agents.dev/platform/v1alpha1/schemas/managed-agent-create-project-organization-ref.schema.json",
	scopeIdentifierProfile:    "cloud-agents-authorization-scope-identifier/ascii-v1",
	scopeIdentityComparison:   "exact_string_no_rewrite",
	requiredPermission:        "projects.create",
	requiredScopeLevel:        "organization",
	outboxEventClass:          "operation_effect",
	resultResourceKind:        "project",
	replayTTLSeconds:          86400,
	createsPlatformOperation:  true,
	externalSideEffectAllowed: false,
}
