// Code generated by scripts/generate-platform-durable-coordination-go.ts; DO NOT EDIT.

package coordination

const (
	RegistryDigest     = "sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30"
	StateMachineDigest = "sha256:5c4fa5c0cfac253b45a41c2e49ee7e863b9efbe124e5d743e041f5e01f5c6f15"
	PolicyDigest       = "sha256:95023973eb007a958a3c5aea3ac61b6caa7cd8955b9a24fcef3ad269230c64e8"
)

var managedAgentCreateProjectProfile = operationProfile{
	profileID:                 "managedAgentCreateProject/v1alpha1",
	profileDigest:             "sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a",
	operationID:               "managedAgentCreateProject",
	requiredPermission:        "projects.create",
	requiredScopeLevel:        "organization",
	outboxEventClass:          "resource_change",
	resultResourceKind:        "project",
	replayTTLSeconds:          86400,
	createsPlatformOperation:  false,
	externalSideEffectAllowed: false,
}
