// Code generated by scripts/generate-platform-identity-sdks.ts; DO NOT EDIT.

export const namespaceRefSchemaId =
  "https://schemas.cloud-agents.dev/common/v1alpha1/schemas/namespace-ref.schema.json";
export const subjectRefSchemaId =
  "https://schemas.cloud-agents.dev/common/v1alpha1/schemas/subject-ref.schema.json";

export type NamespaceRef = Readonly<{
  namespace: string;
  kind: string;
  id: string;
}>;

export type SubjectRef = Readonly<{
  kind: "user" | "serviceAccount" | "workload";
  issuer: string;
  subject: string;
}>;

export type IdentityValidationCode =
  | "CRYPTO_UNAVAILABLE"
  | "DUPLICATE_FIELD"
  | "INVALID_FIELD_TYPE"
  | "INVALID_JSON_OBJECT"
  | "INVALID_NAMESPACE_REF_GRAMMAR"
  | "INVALID_NAMESPACE_REF_LENGTH"
  | "INVALID_SUBJECT_REF_ISSUER"
  | "INVALID_SUBJECT_REF_KIND"
  | "INVALID_SUBJECT_REF_SUBJECT"
  | "INVALID_UNICODE_SCALAR"
  | "MISSING_FIELD"
  | "NON_NFC_NAMESPACE_REF_ID"
  | "TRAILING_JSON"
  | "UNKNOWN_FIELD";

export class IdentityValidationError extends TypeError {
  readonly code: IdentityValidationCode;
  readonly path: string;

  constructor(code: IdentityValidationCode, path: string) {
    super(`${code} at ${path}`);
    this.name = "IdentityValidationError";
    this.code = code;
    this.path = path;
  }
}

const utf8 = new TextEncoder();
const namespaceSegment = /^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$/u;
const subjectKinds = new Set(["user", "serviceAccount", "workload"]);

/**
 * The sole generated NFC conversion boundary. It never trims, lowercases,
 * path-cleans, percent-decodes, or otherwise rewrites the tuple.
 */
export function normalizeNamespaceRef(value: unknown): NamespaceRef {
  const ref = requireNamespaceRef(value);
  validateNamespaceRefComponents(ref, false);
  const normalized = { ...ref, id: ref.id.normalize("NFC") };
  validateNamespaceRef(normalized);
  return Object.freeze(normalized);
}

/** Requires an already-normalized strict NamespaceRef. */
export function validateNamespaceRef(value: unknown): asserts value is NamespaceRef {
  const ref = requireNamespaceRef(value);
  validateNamespaceRefComponents(ref, true);
}

function validateNamespaceRefComponents(ref: NamespaceRef, requireNFC: boolean): void {
  for (const [name, text] of Object.entries(ref)) {
    assertUnicodeScalarString(text, `/${name}`);
  }
  for (const name of ["namespace", "kind"] as const) {
    const text = ref[name];
    if (text.length < 1 || text.length > 63) {
      throw new IdentityValidationError("INVALID_NAMESPACE_REF_LENGTH", `/${name}`);
    }
    if (!namespaceSegment.test(text)) {
      throw new IdentityValidationError("INVALID_NAMESPACE_REF_GRAMMAR", `/${name}`);
    }
  }
  const idLength = [...ref.id].length;
  if (idLength < 1 || idLength > 256) {
    throw new IdentityValidationError("INVALID_NAMESPACE_REF_LENGTH", "/id");
  }
  if (requireNFC && ref.id !== ref.id.normalize("NFC")) {
    throw new IdentityValidationError("NON_NFC_NAMESPACE_REF_ID", "/id");
  }
}

/** Preserves issuer and subject bytes exactly. */
export function validateSubjectRef(value: unknown): asserts value is SubjectRef {
  const ref = requireSubjectRef(value);
  if (!subjectKinds.has(ref.kind)) {
    throw new IdentityValidationError("INVALID_SUBJECT_REF_KIND", "/kind");
  }
  assertUnicodeScalarString(ref.issuer, "/issuer");
  assertUnicodeScalarString(ref.subject, "/subject");
  if ([...ref.issuer].length < 1 || [...ref.issuer].length > 512 || !validAbsoluteURI(ref.issuer)) {
    throw new IdentityValidationError("INVALID_SUBJECT_REF_ISSUER", "/issuer");
  }
  if ([...ref.subject].length < 1 || [...ref.subject].length > 256) {
    throw new IdentityValidationError("INVALID_SUBJECT_REF_SUBJECT", "/subject");
  }
}

function validAbsoluteURI(value: string): boolean {
  const colon = value.indexOf(":");
  if (colon < 1 || !asciiAlpha(value.charCodeAt(0))) return false;
  for (let index = 1; index < colon; index++) {
    const character = value.charCodeAt(index);
    if (
      !asciiAlphaNumeric(character) &&
      character !== 0x2b &&
      character !== 0x2d &&
      character !== 0x2e
    ) {
      return false;
    }
  }
  for (let index = 0; index < value.length; index++) {
    const character = value.charCodeAt(index);
    if (character < 0x20 || character === 0x7f) return false;
    if (character === 0x25) {
      if (
        index + 2 >= value.length ||
        !asciiHex(value.charCodeAt(index + 1)) ||
        !asciiHex(value.charCodeAt(index + 2))
      ) {
        return false;
      }
      index += 2;
    }
  }
  return true;
}

function asciiAlpha(character: number): boolean {
  return (character >= 0x61 && character <= 0x7a) || (character >= 0x41 && character <= 0x5a);
}

function asciiAlphaNumeric(character: number): boolean {
  return asciiAlpha(character) || (character >= 0x30 && character <= 0x39);
}

function asciiHex(character: number): boolean {
  return (
    (character >= 0x30 && character <= 0x39) ||
    (character >= 0x61 && character <= 0x66) ||
    (character >= 0x41 && character <= 0x46)
  );
}

/** Strict JSON decoding rejects unknown, missing, duplicate, and trailing fields. */
export function decodeNamespaceRefJSON(text: string): NamespaceRef {
  const values = decodeStrictStringObject(text, ["id", "kind", "namespace"]);
  const ref = { namespace: values.namespace!, kind: values.kind!, id: values.id! };
  validateNamespaceRef(ref);
  return Object.freeze(ref);
}

/** Strict JSON decoding rejects unknown, missing, duplicate, and trailing fields. */
export function decodeSubjectRefJSON(text: string): SubjectRef {
  const values = decodeStrictStringObject(text, ["issuer", "kind", "subject"]);
  const ref = {
    kind: values.kind!,
    issuer: values.issuer!,
    subject: values.subject!,
  };
  validateSubjectRef(ref);
  return Object.freeze(ref);
}

function decodeStrictStringObject(
  text: string,
  expected: readonly string[],
): Record<string, string> {
  assertUnicodeScalarString(text, "");
  let offset = skipWhitespace(text, 0);
  if (text[offset] !== "{") {
    throw new IdentityValidationError("INVALID_JSON_OBJECT", "");
  }
  offset++;
  const wanted = new Set(expected);
  const values: Record<string, string> = Object.create(null) as Record<string, string>;
  let first = true;
  while (true) {
    offset = skipWhitespace(text, offset);
    if (text[offset] === "}") {
      offset++;
      break;
    }
    if (!first) {
      if (text[offset] !== ",") {
        throw new IdentityValidationError("INVALID_JSON_OBJECT", "");
      }
      offset = skipWhitespace(text, offset + 1);
    }
    first = false;
    const keyToken = parseJSONString(text, offset, "INVALID_JSON_OBJECT", "");
    const key = keyToken.value;
    offset = skipWhitespace(text, keyToken.end);
    if (text[offset] !== ":") {
      throw new IdentityValidationError("INVALID_JSON_OBJECT", "");
    }
    offset = skipWhitespace(text, offset + 1);
    const valueToken = parseJSONString(text, offset, "INVALID_FIELD_TYPE", `/${key}`);
    offset = valueToken.end;
    if (Object.hasOwn(values, key)) {
      throw new IdentityValidationError("DUPLICATE_FIELD", `/${key}`);
    }
    if (!wanted.has(key)) {
      throw new IdentityValidationError("UNKNOWN_FIELD", `/${key}`);
    }
    values[key] = valueToken.value;
  }
  if (skipWhitespace(text, offset) !== text.length) {
    throw new IdentityValidationError("TRAILING_JSON", "");
  }
  for (const key of expected) {
    if (!Object.hasOwn(values, key)) {
      throw new IdentityValidationError("MISSING_FIELD", `/${key}`);
    }
  }
  return values;
}

function parseJSONString(
  text: string,
  offset: number,
  code: "INVALID_FIELD_TYPE" | "INVALID_JSON_OBJECT",
  path: string,
): { value: string; end: number } {
  if (text[offset] !== '"') {
    throw new IdentityValidationError(code, path);
  }
  let escaped = false;
  for (let index = offset + 1; index < text.length; index++) {
    const character = text[index]!;
    if (escaped) {
      escaped = false;
      continue;
    }
    if (character === "\\") {
      escaped = true;
      continue;
    }
    if (character === '"') {
      const token = text.slice(offset, index + 1);
      let value: unknown;
      try {
        value = JSON.parse(token);
      } catch {
        throw new IdentityValidationError(code, path);
      }
      if (typeof value !== "string") {
        throw new IdentityValidationError(code, path);
      }
      assertUnicodeScalarString(value, path);
      return { value, end: index + 1 };
    }
  }
  throw new IdentityValidationError(code, path);
}

function skipWhitespace(text: string, offset: number): number {
  while (
    offset < text.length &&
    (text[offset] === " " ||
      text[offset] === "\n" ||
      text[offset] === "\r" ||
      text[offset] === "\t")
  ) {
    offset++;
  }
  return offset;
}

function requireNamespaceRef(value: unknown): NamespaceRef {
  const record = requireExactRecord(value, ["id", "kind", "namespace"]);
  if (
    typeof record.id !== "string" ||
    typeof record.kind !== "string" ||
    typeof record.namespace !== "string"
  ) {
    throw new IdentityValidationError("INVALID_FIELD_TYPE", "");
  }
  return { namespace: record.namespace, kind: record.kind, id: record.id };
}

function requireSubjectRef(value: unknown): SubjectRef {
  const record = requireExactRecord(value, ["issuer", "kind", "subject"]);
  if (
    typeof record.issuer !== "string" ||
    typeof record.kind !== "string" ||
    typeof record.subject !== "string"
  ) {
    throw new IdentityValidationError("INVALID_FIELD_TYPE", "");
  }
  return {
    kind: record.kind as SubjectRef["kind"],
    issuer: record.issuer,
    subject: record.subject,
  };
}

function requireExactRecord(value: unknown, expected: readonly string[]): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw new IdentityValidationError("INVALID_JSON_OBJECT", "");
  }
  const keys = Reflect.ownKeys(value);
  if (keys.some((key) => typeof key !== "string")) {
    throw new IdentityValidationError("UNKNOWN_FIELD", "");
  }
  const stringKeys = keys as string[];
  for (const key of stringKeys) {
    if (!expected.includes(key)) {
      throw new IdentityValidationError("UNKNOWN_FIELD", `/${key}`);
    }
  }
  for (const key of expected) {
    if (!stringKeys.includes(key)) {
      throw new IdentityValidationError("MISSING_FIELD", `/${key}`);
    }
  }
  return value as Record<string, unknown>;
}

function assertUnicodeScalarString(value: string, path: string): void {
  for (let index = 0; index < value.length; index++) {
    const current = value.charCodeAt(index);
    if (current >= 0xd800 && current <= 0xdbff) {
      if (index + 1 >= value.length) {
        throw new IdentityValidationError("INVALID_UNICODE_SCALAR", path);
      }
      const next = value.charCodeAt(index + 1);
      if (next < 0xdc00 || next > 0xdfff) {
        throw new IdentityValidationError("INVALID_UNICODE_SCALAR", path);
      }
      index++;
    } else if (current >= 0xdc00 && current <= 0xdfff) {
      throw new IdentityValidationError("INVALID_UNICODE_SCALAR", path);
    }
  }
}

/** RFC 8785 profile bytes for the strict NamespaceRef tuple. */
export function canonicalizeNamespaceRef(value: unknown): Uint8Array {
  validateNamespaceRef(value);
  return utf8.encode(
    `{"id":${JSON.stringify(value.id)},"kind":${JSON.stringify(value.kind)},"namespace":${JSON.stringify(value.namespace)}}`,
  );
}

/** RFC 8785 profile bytes for the strict SubjectRef tuple. */
export function canonicalizeSubjectRef(value: unknown): Uint8Array {
  validateSubjectRef(value);
  return utf8.encode(
    `{"issuer":${JSON.stringify(value.issuer)},"kind":${JSON.stringify(value.kind)},"subject":${JSON.stringify(value.subject)}}`,
  );
}

export async function namespaceRefDigest(value: unknown): Promise<`sha256:${string}`> {
  return digest(canonicalizeNamespaceRef(value));
}

export async function namespaceRefUrn(
  value: unknown,
): Promise<`urn:cloud-agents:ref:sha256:${string}`> {
  return `urn:cloud-agents:ref:${await namespaceRefDigest(value)}`;
}

export async function subjectRefDigest(value: unknown): Promise<`sha256:${string}`> {
  return digest(canonicalizeSubjectRef(value));
}

async function digest(value: Uint8Array): Promise<`sha256:${string}`> {
  const subtle = globalThis.crypto?.subtle;
  if (subtle === undefined) {
    throw new IdentityValidationError("CRYPTO_UNAVAILABLE", "");
  }
  const result = new Uint8Array(await subtle.digest("SHA-256", value));
  let hexadecimal = "";
  for (const byte of result) hexadecimal += byte.toString(16).padStart(2, "0");
  return `sha256:${hexadecimal}`;
}
