// Code generated by scripts/generate-managed-agent-local-execution-profile.ts; DO NOT EDIT.

package managedagent

const (
	ManagedAgentLocalExecutionAuthorityID           = "D-055-MANAGED-AGENT-WORKER-COORDINATION-000001"
	ManagedAgentLocalExecutionRevision              = "D-055-MANAGED-AGENT-WORKER-COORDINATION-000001.r1"
	ManagedAgentLocalExecutionDecision              = "D-055-MANAGED-AGENT-WORKER-COORDINATION-000001.r1"
	ManagedAgentLocalExecutionProfileID             = "cloud-agents/managed-agent-worker-local-execution/localdev-v1alpha1"
	ManagedAgentLocalExecutionProfileDigest         = "sha256:892a718cfd58e138cbb22e556da2f0088fdc8b73f43b47805b35e9c90f777e74"
	ManagedAgentLocalExecutionSourceDigest          = "sha256:e87ebf7f8de39c6addbea4ef9ade99625589b62b882f6f8960e14844c8e7364a"
	ManagedAgentLocalExecutionInputManifestDigest   = "sha256:bcb335668343b2682539f9ea20e9db0f4875f83636d5898fdde26a88e81d51de"
	ManagedAgentLocalExecutionScopeProjection       = "sha256-length-prefixed-tenant-project-v1"
	ManagedAgentLocalExecutionResultDigestAlgorithm = "sha256:deterministic-protobuf-receipt-result-v1"
	ManagedAgentLocalExecutionReceiptMode           = "no_write"
)

type ManagedAgentLocalExecutionProfile struct {
	ID                    string
	AuthorityID           string
	Revision              string
	Decision              string
	ProfileDigest         string
	SourceDigest          string
	InputManifestDigest   string
	Mode                  string
	Transport             string
	ScopeProjection       string
	ResultDigestAlgorithm string
	ReceiptMode           string
	ParentProfiles        [5]string
	Commands              [2]string
	MaxDeadlineSeconds    uint32
}

func (p ManagedAgentLocalExecutionProfile) Valid() bool {
	return p.ID == ManagedAgentLocalExecutionProfileID && p.AuthorityID == ManagedAgentLocalExecutionAuthorityID && p.Revision == ManagedAgentLocalExecutionRevision && p.Decision == ManagedAgentLocalExecutionDecision && p.ProfileDigest == ManagedAgentLocalExecutionProfileDigest && p.SourceDigest == ManagedAgentLocalExecutionSourceDigest && p.InputManifestDigest == ManagedAgentLocalExecutionInputManifestDigest && p.Mode == "localdev_only" && p.Transport == "in_process" && p.ScopeProjection == ManagedAgentLocalExecutionScopeProjection && p.ResultDigestAlgorithm == ManagedAgentLocalExecutionResultDigestAlgorithm && p.ReceiptMode == ManagedAgentLocalExecutionReceiptMode && p.ParentProfiles == [5]string{"cloud-agents/managed-agent-lifecycle/v1alpha1", "cloud-agents/managed-agent-events/v1alpha1", "cloud-agents/worker-supervisor-operation-dispatch/localdev-v1alpha1", "cloud-agents/worker-operation-admission/v1alpha1", "cloud-agents/worker-operation-execution/localdev-v1alpha1"} && p.Commands == [2]string{"Probe", "ValidateBinding"} && p.MaxDeadlineSeconds == 300
}

var GeneratedManagedAgentLocalExecutionProfile = ManagedAgentLocalExecutionProfile{
	ID: ManagedAgentLocalExecutionProfileID, AuthorityID: ManagedAgentLocalExecutionAuthorityID, Revision: ManagedAgentLocalExecutionRevision, Decision: ManagedAgentLocalExecutionDecision, ProfileDigest: ManagedAgentLocalExecutionProfileDigest, SourceDigest: ManagedAgentLocalExecutionSourceDigest, InputManifestDigest: ManagedAgentLocalExecutionInputManifestDigest, Mode: "localdev_only", Transport: "in_process", ScopeProjection: ManagedAgentLocalExecutionScopeProjection, ResultDigestAlgorithm: ManagedAgentLocalExecutionResultDigestAlgorithm, ReceiptMode: ManagedAgentLocalExecutionReceiptMode, ParentProfiles: [5]string{"cloud-agents/managed-agent-lifecycle/v1alpha1", "cloud-agents/managed-agent-events/v1alpha1", "cloud-agents/worker-supervisor-operation-dispatch/localdev-v1alpha1", "cloud-agents/worker-operation-admission/v1alpha1", "cloud-agents/worker-operation-execution/localdev-v1alpha1"}, Commands: [2]string{"Probe", "ValidateBinding"}, MaxDeadlineSeconds: 300,
}

func ManagedAgentLocalExecutionProfileAuthority() ManagedAgentLocalExecutionProfile {
	return GeneratedManagedAgentLocalExecutionProfile
}
