// Code generated by scripts/generate-managed-agent-local-execution-profile.ts; DO NOT EDIT.

package managedagent

const (
	ManagedAgentLocalExecutionAuthorityID           = "D-055-MANAGED-AGENT-WORKER-COORDINATION-000001"
	ManagedAgentLocalExecutionRevision              = "D-055-MANAGED-AGENT-WORKER-COORDINATION-000001.r1"
	ManagedAgentLocalExecutionDecision              = "D-055-MANAGED-AGENT-WORKER-COORDINATION-000001.r1"
	ManagedAgentLocalExecutionProfileID             = "cloud-agents/managed-agent-worker-local-execution/localdev-v1alpha1"
	ManagedAgentLocalExecutionProfileDigest         = "sha256:d47d7cb3c6d6a89c6b5b83d47e866cce3fb52d3dee653cd1f699b693d8065b11"
	ManagedAgentLocalExecutionSourceDigest          = "sha256:b8ea3627cac046714af7eab1b5ba8d92fd449f2c43e4eef0050687921b2781b5"
	ManagedAgentLocalExecutionInputManifestDigest   = "sha256:298dc3fc6f250bb624c59d82f6fb4019d527972147d3630a1a3df347ee2662d0"
	ManagedAgentLocalExecutionScopeProjection       = "sha256-length-prefixed-tenant-project-v1"
	ManagedAgentLocalExecutionResultDigestAlgorithm = "sha256:deterministic-protobuf-receipt-result-v1"
	ManagedAgentLocalExecutionReceiptMode           = "no_write"
)

type ManagedAgentLocalExecutionProfile struct {
	ID                    string
	AuthorityID           string
	Revision              string
	Decision              string
	ProfileDigest         string
	SourceDigest          string
	InputManifestDigest   string
	Mode                  string
	Transport             string
	ScopeProjection       string
	ResultDigestAlgorithm string
	ReceiptMode           string
	ParentProfiles        [5]string
	Commands              [2]string
	MaxDeadlineSeconds    uint32
}

func (p ManagedAgentLocalExecutionProfile) Valid() bool {
	return p.ID == ManagedAgentLocalExecutionProfileID && p.AuthorityID == ManagedAgentLocalExecutionAuthorityID && p.Revision == ManagedAgentLocalExecutionRevision && p.Decision == ManagedAgentLocalExecutionDecision && p.ProfileDigest == ManagedAgentLocalExecutionProfileDigest && p.SourceDigest == ManagedAgentLocalExecutionSourceDigest && p.InputManifestDigest == ManagedAgentLocalExecutionInputManifestDigest && p.Mode == "localdev_only" && p.Transport == "in_process" && p.ScopeProjection == ManagedAgentLocalExecutionScopeProjection && p.ResultDigestAlgorithm == ManagedAgentLocalExecutionResultDigestAlgorithm && p.ReceiptMode == ManagedAgentLocalExecutionReceiptMode && p.ParentProfiles == [5]string{"cloud-agents/managed-agent-lifecycle/v1alpha1", "cloud-agents/managed-agent-events/v1alpha1", "cloud-agents/worker-supervisor-operation-dispatch/localdev-v1alpha1", "cloud-agents/worker-operation-admission/v1alpha1", "cloud-agents/worker-operation-execution/localdev-v1alpha1"} && p.Commands == [2]string{"Probe", "ValidateBinding"} && p.MaxDeadlineSeconds == 300
}

var GeneratedManagedAgentLocalExecutionProfile = ManagedAgentLocalExecutionProfile{
	ID: ManagedAgentLocalExecutionProfileID, AuthorityID: ManagedAgentLocalExecutionAuthorityID, Revision: ManagedAgentLocalExecutionRevision, Decision: ManagedAgentLocalExecutionDecision, ProfileDigest: ManagedAgentLocalExecutionProfileDigest, SourceDigest: ManagedAgentLocalExecutionSourceDigest, InputManifestDigest: ManagedAgentLocalExecutionInputManifestDigest, Mode: "localdev_only", Transport: "in_process", ScopeProjection: ManagedAgentLocalExecutionScopeProjection, ResultDigestAlgorithm: ManagedAgentLocalExecutionResultDigestAlgorithm, ReceiptMode: ManagedAgentLocalExecutionReceiptMode, ParentProfiles: [5]string{"cloud-agents/managed-agent-lifecycle/v1alpha1", "cloud-agents/managed-agent-events/v1alpha1", "cloud-agents/worker-supervisor-operation-dispatch/localdev-v1alpha1", "cloud-agents/worker-operation-admission/v1alpha1", "cloud-agents/worker-operation-execution/localdev-v1alpha1"}, Commands: [2]string{"Probe", "ValidateBinding"}, MaxDeadlineSeconds: 300,
}

func ManagedAgentLocalExecutionProfileAuthority() ManagedAgentLocalExecutionProfile {
	return GeneratedManagedAgentLocalExecutionProfile
}
