// Code generated by scripts/generate-platform-compatibility-recovery-go.ts; DO NOT EDIT.

package compatibility

const (
	RegistryFormatVersion = "cloud-agents-compatibility-recovery-registry/v2"
	RegistryID            = "cloud-agents/platform/compatibility-recovery"
	RegistryDigest        = "sha256:d5ca128f28d637349dd6f8515f9ca6bb182fb0778a3160e24d731712589f2973"
	StateMachineDigest    = "sha256:41ed340b8a1106341f8b797210492af0f9c022d8d43803977ff8079d52251863"
	PolicyDigest          = "sha256:20f5b6e30e7d7254baabc97894aba2af2d2bcf40f4175f504d195b4e3a832708"
	SchemaHead            = "000010"
	SchemaCatalogDigest   = "sha256:a84a02c20244b60d2ffe4d27beb6fa5f5e0db8fb95ef91eef8865bce63412236"
	SchemaMigrationDigest = "sha256:ab758a08c07ffb95b9e9a612c90079fcaf54d06407d0cfe4a0368db570f621e6"
)

var acquireBackfillLeaseOperationProfile = operationProfile{
	profileID:      "backfill/v2",
	profileDigest:  "sha256:c5d96407e0c0003689faa9e5526098b57e8b40d9ef67c76f9318e2b0326e6145",
	operationID:    "backfill-acquire-lease/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_backfill_acquire_lease_v2",
	serviceMethod:  "AcquireBackfillLease",
	mode:           "mutation",
	capability:     "compatibility_recovery.backfill.acquire_lease",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var activateLiveInstanceOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-activate/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_activate_v2",
	serviceMethod:  "ActivateLiveInstance",
	mode:           "mutation",
	capability:     "compatibility_recovery.live_instance.activate",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var advanceBackfillOperationProfile = operationProfile{
	profileID:      "backfill/v2",
	profileDigest:  "sha256:c5d96407e0c0003689faa9e5526098b57e8b40d9ef67c76f9318e2b0326e6145",
	operationID:    "backfill-advance/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_backfill_advance_v2",
	serviceMethod:  "AdvanceBackfill",
	mode:           "mutation",
	capability:     "compatibility_recovery.backfill.advance",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var beginLiveInstanceDrainOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-begin-drain/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_begin_drain_v2",
	serviceMethod:  "BeginLiveInstanceDrain",
	mode:           "mutation",
	capability:     "compatibility_recovery.live_instance.begin_drain",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var collectRetirementReceiptOperationProfile = operationProfile{
	profileID:      "retirement-receipt/v2",
	profileDigest:  "sha256:b789a28be60a340f49662cd5c1570f29b30abd3b4b27ef76d7e6a2666833876f",
	operationID:    "retirement-receipt-collect/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_retirement_receipt_collect_v2",
	serviceMethod:  "CollectRetirementReceipt",
	mode:           "mutation",
	capability:     "compatibility_recovery.retirement_receipt.collect",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var completeBackfillOperationProfile = operationProfile{
	profileID:      "backfill/v2",
	profileDigest:  "sha256:c5d96407e0c0003689faa9e5526098b57e8b40d9ef67c76f9318e2b0326e6145",
	operationID:    "backfill-complete/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_backfill_complete_v2",
	serviceMethod:  "CompleteBackfill",
	mode:           "mutation",
	capability:     "compatibility_recovery.backfill.complete",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var completeRestoreEvidenceOperationProfile = operationProfile{
	profileID:      "restore-evidence/v2",
	profileDigest:  "sha256:c9a3376afb9e90717dc4191f88723488cf79bd5ee5df9ef24db1be8eb9a01106",
	operationID:    "restore-evidence-complete/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_restore_evidence_complete_v2",
	serviceMethod:  "CompleteRestoreEvidence",
	mode:           "mutation",
	capability:     "compatibility_recovery.restore_evidence.complete",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var completeRetirementReceiptOperationProfile = operationProfile{
	profileID:      "retirement-receipt/v2",
	profileDigest:  "sha256:b789a28be60a340f49662cd5c1570f29b30abd3b4b27ef76d7e6a2666833876f",
	operationID:    "retirement-receipt-complete/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_retirement_receipt_complete_v2",
	serviceMethod:  "CompleteRetirementReceipt",
	mode:           "mutation",
	capability:     "compatibility_recovery.retirement_receipt.complete",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var evaluateMigrationPreflightOperationProfile = operationProfile{
	profileID:      "migration-preflight/v2",
	profileDigest:  "sha256:e02302ea60eca9855d362d8bcab7efc0466adab6d3a486d828adccdbc5411d7a",
	operationID:    "migration-preflight-evaluate/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_migration_preflight_evaluate_v2",
	serviceMethod:  "EvaluateMigrationPreflight",
	mode:           "read_only",
	capability:     "compatibility_recovery.migration_preflight.evaluate",
	unknownOutcome: "not_applicable",
}

var fenceLiveInstanceOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-fence/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_fence_v2",
	serviceMethod:  "FenceLiveInstance",
	mode:           "mutation",
	capability:     "compatibility_recovery.live_instance.fence",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var finishLiveInstanceDrainOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-finish-drain/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_finish_drain_v2",
	serviceMethod:  "FinishLiveInstanceDrain",
	mode:           "mutation",
	capability:     "compatibility_recovery.live_instance.finish_drain",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var heartbeatBackfillOperationProfile = operationProfile{
	profileID:      "backfill/v2",
	profileDigest:  "sha256:c5d96407e0c0003689faa9e5526098b57e8b40d9ef67c76f9318e2b0326e6145",
	operationID:    "backfill-heartbeat/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_backfill_heartbeat_v2",
	serviceMethod:  "HeartbeatBackfill",
	mode:           "mutation",
	capability:     "compatibility_recovery.backfill.heartbeat",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var heartbeatLiveInstanceOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-heartbeat/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_heartbeat_v2",
	serviceMethod:  "HeartbeatLiveInstance",
	mode:           "mutation",
	capability:     "compatibility_recovery.live_instance.heartbeat",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var reconcileBackfillOperationProfile = operationProfile{
	profileID:      "backfill/v2",
	profileDigest:  "sha256:c5d96407e0c0003689faa9e5526098b57e8b40d9ef67c76f9318e2b0326e6145",
	operationID:    "backfill-reconcile/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_backfill_reconcile_v2",
	serviceMethod:  "ReconcileBackfill",
	mode:           "read_only",
	capability:     "compatibility_recovery.backfill.reconcile",
	unknownOutcome: "not_applicable",
}

var reconcileLiveInstanceOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-reconcile/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_reconcile_v2",
	serviceMethod:  "ReconcileLiveInstance",
	mode:           "read_only",
	capability:     "compatibility_recovery.live_instance.reconcile",
	unknownOutcome: "not_applicable",
}

var reconcileRestoreEvidenceOperationProfile = operationProfile{
	profileID:      "restore-evidence/v2",
	profileDigest:  "sha256:c9a3376afb9e90717dc4191f88723488cf79bd5ee5df9ef24db1be8eb9a01106",
	operationID:    "restore-evidence-reconcile/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_restore_evidence_reconcile_v2",
	serviceMethod:  "ReconcileRestoreEvidence",
	mode:           "read_only",
	capability:     "compatibility_recovery.restore_evidence.reconcile",
	unknownOutcome: "not_applicable",
}

var reconcileRetirementReceiptOperationProfile = operationProfile{
	profileID:      "retirement-receipt/v2",
	profileDigest:  "sha256:b789a28be60a340f49662cd5c1570f29b30abd3b4b27ef76d7e6a2666833876f",
	operationID:    "retirement-receipt-reconcile/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_retirement_receipt_reconcile_v2",
	serviceMethod:  "ReconcileRetirementReceipt",
	mode:           "read_only",
	capability:     "compatibility_recovery.retirement_receipt.reconcile",
	unknownOutcome: "not_applicable",
}

var reconcileWorkloadPrincipalOperationProfile = operationProfile{
	profileID:      "workload-principal/v2",
	profileDigest:  "sha256:7208b25e051ce6cb298d8f88190365a950bc0ac48a669fbf7ab93de35cee6878",
	operationID:    "workload-principal-reconcile/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_workload_principal_reconcile_v2",
	serviceMethod:  "ReconcileWorkloadPrincipal",
	mode:           "read_only",
	capability:     "compatibility_recovery.workload_principal.reconcile",
	unknownOutcome: "not_applicable",
}

var recordRestoreEvidenceOperationProfile = operationProfile{
	profileID:      "restore-evidence/v2",
	profileDigest:  "sha256:c9a3376afb9e90717dc4191f88723488cf79bd5ee5df9ef24db1be8eb9a01106",
	operationID:    "restore-evidence-record/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_restore_evidence_record_v2",
	serviceMethod:  "RecordRestoreEvidence",
	mode:           "mutation",
	capability:     "compatibility_recovery.restore_evidence.record",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var registerLiveInstanceOperationProfile = operationProfile{
	profileID:      "live-instance/v2",
	profileDigest:  "sha256:0b2362b300f48a58160d5f9b754c865194f2a4ca14d6012fe361b340dd1b8ff8",
	operationID:    "live-instance-register/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_live_instance_register_v2",
	serviceMethod:  "RegisterLiveInstance",
	mode:           "mutation",
	capability:     "compatibility_recovery.live_instance.register",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var registerWorkloadPrincipalOperationProfile = operationProfile{
	profileID:      "workload-principal/v2",
	profileDigest:  "sha256:7208b25e051ce6cb298d8f88190365a950bc0ac48a669fbf7ab93de35cee6878",
	operationID:    "workload-principal-register/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_workload_principal_register_v2",
	serviceMethod:  "RegisterWorkloadPrincipal",
	mode:           "mutation",
	capability:     "compatibility_recovery.workload_principal.register",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var rejectRestoreEvidenceOperationProfile = operationProfile{
	profileID:      "restore-evidence/v2",
	profileDigest:  "sha256:c9a3376afb9e90717dc4191f88723488cf79bd5ee5df9ef24db1be8eb9a01106",
	operationID:    "restore-evidence-reject/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_restore_evidence_reject_v2",
	serviceMethod:  "RejectRestoreEvidence",
	mode:           "mutation",
	capability:     "compatibility_recovery.restore_evidence.reject",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var rejectRetirementReceiptOperationProfile = operationProfile{
	profileID:      "retirement-receipt/v2",
	profileDigest:  "sha256:b789a28be60a340f49662cd5c1570f29b30abd3b4b27ef76d7e6a2666833876f",
	operationID:    "retirement-receipt-reject/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_retirement_receipt_reject_v2",
	serviceMethod:  "RejectRetirementReceipt",
	mode:           "mutation",
	capability:     "compatibility_recovery.retirement_receipt.reject",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var revokeWorkloadPrincipalOperationProfile = operationProfile{
	profileID:      "workload-principal/v2",
	profileDigest:  "sha256:7208b25e051ce6cb298d8f88190365a950bc0ac48a669fbf7ab93de35cee6878",
	operationID:    "workload-principal-revoke/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_workload_principal_revoke_v2",
	serviceMethod:  "RevokeWorkloadPrincipal",
	mode:           "mutation",
	capability:     "compatibility_recovery.workload_principal.revoke",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var rotateWorkloadPrincipalOperationProfile = operationProfile{
	profileID:      "workload-principal/v2",
	profileDigest:  "sha256:7208b25e051ce6cb298d8f88190365a950bc0ac48a669fbf7ab93de35cee6878",
	operationID:    "workload-principal-rotate/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_workload_principal_rotate_v2",
	serviceMethod:  "RotateWorkloadPrincipal",
	mode:           "mutation",
	capability:     "compatibility_recovery.workload_principal.rotate",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var startBackfillOperationProfile = operationProfile{
	profileID:      "backfill/v2",
	profileDigest:  "sha256:c5d96407e0c0003689faa9e5526098b57e8b40d9ef67c76f9318e2b0326e6145",
	operationID:    "backfill-start/v2",
	sqlFunction:    "cloud_agents.compatibility_recovery_backfill_start_v2",
	serviceMethod:  "StartBackfill",
	mode:           "mutation",
	capability:     "compatibility_recovery.backfill.start",
	unknownOutcome: "reconcile_required_no_write_retry",
}

var generatedOperationProfiles = [...]operationProfile{
	acquireBackfillLeaseOperationProfile,
	activateLiveInstanceOperationProfile,
	advanceBackfillOperationProfile,
	beginLiveInstanceDrainOperationProfile,
	collectRetirementReceiptOperationProfile,
	completeBackfillOperationProfile,
	completeRestoreEvidenceOperationProfile,
	completeRetirementReceiptOperationProfile,
	evaluateMigrationPreflightOperationProfile,
	fenceLiveInstanceOperationProfile,
	finishLiveInstanceDrainOperationProfile,
	heartbeatBackfillOperationProfile,
	heartbeatLiveInstanceOperationProfile,
	reconcileBackfillOperationProfile,
	reconcileLiveInstanceOperationProfile,
	reconcileRestoreEvidenceOperationProfile,
	reconcileRetirementReceiptOperationProfile,
	reconcileWorkloadPrincipalOperationProfile,
	recordRestoreEvidenceOperationProfile,
	registerLiveInstanceOperationProfile,
	registerWorkloadPrincipalOperationProfile,
	rejectRestoreEvidenceOperationProfile,
	rejectRetirementReceiptOperationProfile,
	revokeWorkloadPrincipalOperationProfile,
	rotateWorkloadPrincipalOperationProfile,
	startBackfillOperationProfile,
}

func AcquireBackfillLeaseOperation() Operation {
	return Operation{profile: acquireBackfillLeaseOperationProfile}
}

func ActivateLiveInstanceOperation() Operation {
	return Operation{profile: activateLiveInstanceOperationProfile}
}

func AdvanceBackfillOperation() Operation {
	return Operation{profile: advanceBackfillOperationProfile}
}

func BeginLiveInstanceDrainOperation() Operation {
	return Operation{profile: beginLiveInstanceDrainOperationProfile}
}

func CollectRetirementReceiptOperation() Operation {
	return Operation{profile: collectRetirementReceiptOperationProfile}
}

func CompleteBackfillOperation() Operation {
	return Operation{profile: completeBackfillOperationProfile}
}

func CompleteRestoreEvidenceOperation() Operation {
	return Operation{profile: completeRestoreEvidenceOperationProfile}
}

func CompleteRetirementReceiptOperation() Operation {
	return Operation{profile: completeRetirementReceiptOperationProfile}
}

func EvaluateMigrationPreflightOperation() Operation {
	return Operation{profile: evaluateMigrationPreflightOperationProfile}
}

func FenceLiveInstanceOperation() Operation {
	return Operation{profile: fenceLiveInstanceOperationProfile}
}

func FinishLiveInstanceDrainOperation() Operation {
	return Operation{profile: finishLiveInstanceDrainOperationProfile}
}

func HeartbeatBackfillOperation() Operation {
	return Operation{profile: heartbeatBackfillOperationProfile}
}

func HeartbeatLiveInstanceOperation() Operation {
	return Operation{profile: heartbeatLiveInstanceOperationProfile}
}

func ReconcileBackfillOperation() Operation {
	return Operation{profile: reconcileBackfillOperationProfile}
}

func ReconcileLiveInstanceOperation() Operation {
	return Operation{profile: reconcileLiveInstanceOperationProfile}
}

func ReconcileRestoreEvidenceOperation() Operation {
	return Operation{profile: reconcileRestoreEvidenceOperationProfile}
}

func ReconcileRetirementReceiptOperation() Operation {
	return Operation{profile: reconcileRetirementReceiptOperationProfile}
}

func ReconcileWorkloadPrincipalOperation() Operation {
	return Operation{profile: reconcileWorkloadPrincipalOperationProfile}
}

func RecordRestoreEvidenceOperation() Operation {
	return Operation{profile: recordRestoreEvidenceOperationProfile}
}

func RegisterLiveInstanceOperation() Operation {
	return Operation{profile: registerLiveInstanceOperationProfile}
}

func RegisterWorkloadPrincipalOperation() Operation {
	return Operation{profile: registerWorkloadPrincipalOperationProfile}
}

func RejectRestoreEvidenceOperation() Operation {
	return Operation{profile: rejectRestoreEvidenceOperationProfile}
}

func RejectRetirementReceiptOperation() Operation {
	return Operation{profile: rejectRetirementReceiptOperationProfile}
}

func RevokeWorkloadPrincipalOperation() Operation {
	return Operation{profile: revokeWorkloadPrincipalOperationProfile}
}

func RotateWorkloadPrincipalOperation() Operation {
	return Operation{profile: rotateWorkloadPrincipalOperationProfile}
}

func StartBackfillOperation() Operation {
	return Operation{profile: startBackfillOperationProfile}
}
