// Code generated by scripts/generate-platform-runner-ledger-consumer-go.ts; DO NOT EDIT.

package migration

const (
	runnerLedgerConsumerRegistryDigest     = "sha256:f1248220aa18f6f7c85792e4b168fcc18a172ddeca65778686d033535617ed43"
	runnerLedgerConsumerStateMachineDigest = "sha256:eb94b6399fb2d509aea69cbc7bfb6ed2942460af61d5cf2c57271024f37a0547"
	runnerLedgerConsumerPolicyDigest       = "sha256:b011e6869de84c17fa351802630327a36ab92595ada9089cc6068cebda0c4481"

	runnerLedgerConsumerBoundPreflightRegistryID         = "cloud-agents/platform/runner-ledger-preflight"
	runnerLedgerConsumerBoundPreflightRegistryDigest     = "sha256:a17a7333d1455d3ed5a0e2d70c2a3b2ea9ee1e323a5ac935d4d9a12a2db30661"
	runnerLedgerConsumerBoundPreflightStateMachineDigest = "sha256:fe00c5de375865350798e6a79de22b4272fb70949bbd5d3c0a11745bb3dd11ae"
	runnerLedgerConsumerBoundPreflightPolicyDigest       = "sha256:1fb99617210b7d92e7c51d2241f98674c67818c85c82cf13edd2ebe33b34388b"
	runnerLedgerConsumerBoundPreflightProfileID          = "runner-ledger-preflight/v1"
	runnerLedgerConsumerBoundPreflightProfileDigest      = "sha256:beefc1e996e56e88fbcde2afe35a2f823a3846f03e5f6b8f47d4e819a1e1bfe9"
)

var generatedRunnerLedgerConsumerProfile = runnerLedgerConsumerProfile{
	profileID:                        "runner-ledger-consumer/v1",
	profileDigest:                    "sha256:11015e7d78a3edb5adc0e666c2898ca4cc3aaeae097537c867b25aaf0d22f732",
	stateMachineID:                   "runner-ledger-consumer/v1",
	canonicalizationProfile:          "cloud-agents-runner-ledger-consumer/v1-rfc8785-sha256",
	canonicalizationAlgorithm:        "RFC8785",
	digestAlgorithm:                  "SHA-256",
	comparison:                       "exact_string_no_rewrite",
	preflightProfileBinding:          "exact_runner_ledger_preflight_v1_generated_identity",
	preflightDispatchBinding:         "exact_consumed_same_verifier_claim_dispatch_subject_digest",
	currentEvidenceBinding:           "exact_candidate_generation_journal_recovery_and_projection_identity",
	orderedMigrationPrefixBinding:    "exact_complete_length_head_and_domain_separated_digest",
	runtimeResultBinding:             "exact_schema_bundle_manifest_final_head_and_empty_applied",
	storedContradictionPrecedence:    "MIGRATION_EVIDENCE_JOURNAL_CORRUPT_BEFORE_NOT_IMPLEMENTED",
	contextOperationalPrecedence:     "STABLE_CONTEXT_OR_JOURNAL_FAILED_BEFORE_NOT_IMPLEMENTED",
	recoveryRequiredPrecedence:       "MIGRATION_EVIDENCE_RECOVERY_REQUIRED_BEFORE_NOT_IMPLEMENTED",
	unsupportedTransitionPrecedence:  "MIGRATION_PROJECTION_NOT_IMPLEMENTED",
	oneShotConsumptionPrecedence:     "SECOND_CONSUME_FAILS_CLOSED",
	unknownOutcomePrecedence:         "FAIL_CLOSED_NO_RETRY_AS_SECOND_TRANSITION",
	runnerConsumerBoundary:           "complete_return_success_noop_only",
	existingBrandNewWriterBoundary:   "separate_existing_authority_chain",
	entryWriterBoundary:              "not_implemented",
	recoveryWriterBoundary:           "not_implemented",
	databaseSessionBoundary:          "read_only_preflight_closed_before_result",
	databaseTransactionBoundary:      "forbidden",
	ledgerMutationBoundary:           "forbidden",
	evidenceMutationBoundary:         "forbidden",
	httpSurfaceBoundary:              "not_implemented",
	p2SurfaceBoundary:                "not_implemented",
	providerSideEffectsBoundary:      "forbidden",
	productionDatabaseWritesBoundary: "not_authorized",
	deploymentBoundary:               "not_authorized",
	publicationBoundary:              "not_authorized",
	gateStatusBoundary:               "all_gates_open",
}

var generatedRunnerLedgerConsumerTransitions = [...]runnerLedgerConsumerTransition{
	{from: "unclassified", event: "consume_complete_return_success", to: "complete_return_success_noop"},
	{from: "unclassified", event: "consume_entry", to: "entry_not_implemented"},
	{from: "unclassified", event: "consume_recovery", to: "recovery_not_implemented"},
	{from: "unclassified", event: "consume_unknown", to: "unknown_not_implemented"},
}

const generatedRunnerLedgerConsumerPairCount = 17

func generatedRunnerLedgerConsumerAction(disposition runnerLedgerPreflightDisposition, state RecoveryState, action RecoveryAction) (runnerLedgerConsumerAction, bool) {
	switch string(disposition) + "\x00" + string(state) + "\x00" + string(action) {
	case "complete_return_success\u0000completed\u0000return_success":
		return runnerLedgerConsumerAction("return_success_noop"), true
	case "empty_brand_new\u0000brand_new\u0000begin_first_attempt":
		return runnerLedgerConsumerAction("entry_not_implemented"), true
	case "empty_brand_new\u0000brand_new_inherited\u0000begin_first_attempt":
		return runnerLedgerConsumerAction("entry_not_implemented"), true
	case "empty_brand_new\u0000brand_new_inherited\u0000begin_next_attempt":
		return runnerLedgerConsumerAction("entry_not_implemented"), true
	case "partial_next_entry\u0000brand_new_inherited\u0000begin_first_attempt_next_entry":
		return runnerLedgerConsumerAction("entry_not_implemented"), true
	case "partial_next_entry\u0000terminal\u0000begin_first_attempt_next_entry":
		return runnerLedgerConsumerAction("entry_not_implemented"), true
	case "partial_retry_or_recovery\u0000brand_new_inherited\u0000begin_first_attempt":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000brand_new_inherited\u0000begin_next_attempt":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000dangling_statement_intent\u0000append_aborted_retryable":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000dangling_statement_intent\u0000append_aborted_terminal":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000dangling_intermediate\u0000append_aborted_retryable":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000dangling_intermediate\u0000append_aborted_terminal":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000dangling_commit_intent\u0000reconcile_commit":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000ambiguous_unresolved\u0000reconcile_commit":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000terminal\u0000begin_next_attempt":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000terminal\u0000return_failure":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	case "partial_retry_or_recovery\u0000divergent\u0000return_failure":
		return runnerLedgerConsumerAction("recovery_not_implemented"), true
	default:
		return "", false
	}
}
