// Code generated by scripts/generate-platform-runner-ledger-preflight-go.ts; DO NOT EDIT.

package migration

const (
	runnerLedgerPreflightRegistryDigest     = "sha256:7e04dbddbcdd7d08e4831fc77bc034d08f09ffe54e4bfaebe5f39933260edb1a"
	runnerLedgerPreflightStateMachineDigest = "sha256:fe00c5de375865350798e6a79de22b4272fb70949bbd5d3c0a11745bb3dd11ae"
	runnerLedgerPreflightPolicyDigest       = "sha256:fc693052970176594730421b74842a5d497747620b86fd9be7f59e77d65e4bc8"
)

var generatedRunnerLedgerPreflightProfile = runnerLedgerPreflightProfile{
	profileID:                           "runner-ledger-preflight/v1",
	profileDigest:                       "sha256:a6ef13814c34d62d9d9c5f19054c8336ad84ae6836a13d36561a8adc802b98c8",
	stateMachineID:                      "runner-ledger-preflight/v1",
	canonicalizationProfile:             "cloud-agents-runner-ledger-preflight/v1-rfc8785-sha256",
	canonicalizationAlgorithm:           "RFC8785",
	digestAlgorithm:                     "SHA-256",
	comparison:                          "exact_string_no_rewrite",
	schemaBundleBinding:                 "exact_current_verified_schema_bundle_digest",
	executionLineageBinding:             "exact_signed_execution_lineage_digest",
	orderedMigrationPrefixBinding:       "exact_length_head_and_domain_separated_digest",
	lastAppliedCatalogBinding:           "exact_signed_cumulative_catalog_contract_digest_or_initial_predecessor",
	nextEntryBinding:                    "exact_signed_migration_id_and_entry_digest_when_required",
	evidenceRecoveryBinding:             "exact_state_and_next_action_or_explicit_unavailable",
	storedContradictionPrecedence:        "MIGRATION_EVIDENCE_JOURNAL_CORRUPT_BEFORE_NOT_IMPLEMENTED",
	contextOrOperationalPrecedence:       "STABLE_CONTEXT_OR_JOURNAL_FAILED_BEFORE_NOT_IMPLEMENTED",
	recoveryRequiredPrecedence:           "MIGRATION_EVIDENCE_RECOVERY_REQUIRED_BEFORE_NOT_IMPLEMENTED",
	classifiedWithoutBinderPrecedence:    "MIGRATION_PROJECTION_NOT_IMPLEMENTED",
	unknownOutcomePrecedence:             "FAIL_CLOSED_NO_RETRY_AS_SECOND_TRANSITION",
	runnerConsumerBoundary:               "not_implemented",
	databaseSessionBoundary:              "none",
	databaseTransactionBoundary:          "forbidden",
	ledgerMutationBoundary:               "forbidden",
	evidenceMutationBoundary:             "forbidden",
	httpSurfaceBoundary:                  "not_implemented",
	p2SurfaceBoundary:                    "not_implemented",
	providerSideEffectsBoundary:          "forbidden",
	productionDatabaseWritesBoundary:     "not_authorized",
	deploymentBoundary:                   "not_authorized",
	publicationBoundary:                  "not_authorized",
	gateStatusBoundary:                   "all_gates_open",
}

var generatedRunnerLedgerPreflightTransitions = [...]runnerLedgerPreflightTransition{
	{from: "unclassified", event: "observe_complete", to: runnerLedgerPreflightDisposition("complete_return_success")},
	{from: "unclassified", event: "observe_empty", to: runnerLedgerPreflightDisposition("empty_brand_new")},
	{from: "unclassified", event: "observe_partial_next_entry", to: runnerLedgerPreflightDisposition("partial_next_entry")},
	{from: "unclassified", event: "observe_partial_retry_or_recovery", to: runnerLedgerPreflightDisposition("partial_retry_or_recovery")},
	{from: "unclassified", event: "observe_unknown_or_failed", to: runnerLedgerPreflightDisposition("unknown_or_failed")},
}
