// Code generated by scripts/generate-platform-runner-ledger-entry-admission-go.ts; DO NOT EDIT.

package migration

const (
	runnerLedgerEntryAdmissionRegistryDigest     = "sha256:fb7621405bbe62e47ce99ff00239c0e0d3fc12465e475f468b3fb07887bb886a"
	runnerLedgerEntryAdmissionStateMachineDigest = "sha256:94baeab96aaa0da096b6de2c48fc646723d9ad003b68fd1135edf4adcc141189"
	runnerLedgerEntryAdmissionPolicyDigest       = "sha256:9869fae48b30e4077f346b1d7c4309056a2129fb5974e73762d897e2925dc26a"
	runnerLedgerEntryAdmissionProfileDigest      = "sha256:bee8d42d328984f929fafa1e9dd2d4b18c94814e9375a1e1a1199ad8cb0ab551"

	runnerLedgerEntryAdmissionBoundConsumerRegistryID         = "cloud-agents/platform/runner-ledger-consumer"
	runnerLedgerEntryAdmissionBoundConsumerRegistryDigest     = "sha256:f1248220aa18f6f7c85792e4b168fcc18a172ddeca65778686d033535617ed43"
	runnerLedgerEntryAdmissionBoundConsumerStateMachineDigest = "sha256:eb94b6399fb2d509aea69cbc7bfb6ed2942460af61d5cf2c57271024f37a0547"
	runnerLedgerEntryAdmissionBoundConsumerPolicyDigest       = "sha256:b011e6869de84c17fa351802630327a36ab92595ada9089cc6068cebda0c4481"
	runnerLedgerEntryAdmissionBoundConsumerProfileID          = "runner-ledger-consumer/v1"
	runnerLedgerEntryAdmissionBoundConsumerProfileDigest      = "sha256:11015e7d78a3edb5adc0e666c2898ca4cc3aaeae097537c867b25aaf0d22f732"
)

var generatedRunnerLedgerEntryAdmissionProfile = runnerLedgerEntryAdmissionProfile{
	profileID:                        "runner-ledger-entry-admission/v1",
	profileDigest:                    "sha256:bee8d42d328984f929fafa1e9dd2d4b18c94814e9375a1e1a1199ad8cb0ab551",
	stateMachineID:                   "runner-ledger-entry-admission/v1",
	canonicalizationProfile:          "cloud-agents-runner-ledger-entry-admission/v1-rfc8785-sha256",
	canonicalizationAlgorithm:        "RFC8785",
	digestAlgorithm:                  "SHA-256",
	comparison:                       "exact_string_no_rewrite",
	consumerProfileBinding:           "exact_runner_ledger_consumer_v1_generated_identity",
	consumedConsumerFactBinding:      "exact_entry_action_same_verifier_consumed_subject",
	currentEvidenceBinding:           "exact_candidate_generation_journal_recovery_and_projection_before_and_after_database_read",
	selectedEntryBinding:             "exact_ordered_next_entry_index_id_and_digest",
	planClosureBinding:               "exact_entry_plan_count_and_domain_separated_digest",
	databaseSessionBinding:           "exact_connected_and_migration_role_same_session_identity",
	ledgerPrefixBinding:              "exact_length_head_rows_and_digest_before_and_after_catalog_projection",
	catalogProjectionBinding:         "exact_initial_or_cumulative_verified_projection_subject_and_result",
	advisoryLockBinding:              "exact_signed_key_held_until_permit_close",
	storedContradictionPrecedence:    "MIGRATION_EVIDENCE_JOURNAL_CORRUPT_BEFORE_NOT_IMPLEMENTED",
	contextOperationalPrecedence:     "STABLE_CONTEXT_OR_JOURNAL_FAILED_BEFORE_NOT_IMPLEMENTED",
	recoveryRequiredPrecedence:       "MIGRATION_EVIDENCE_RECOVERY_REQUIRED_BEFORE_NOT_IMPLEMENTED",
	unsupportedTransitionPrecedence:  "MIGRATION_PROJECTION_NOT_IMPLEMENTED",
	closeUnlockUnknownPrecedence:     "CLEANUP_FAILURE_INVALIDATES_PERMIT_AND_DOMINATES_NOT_IMPLEMENTED",
	oneShotConsumptionPrecedence:     "SECOND_TRANSITION_FAILS_CLOSED",
	unknownOutcomePrecedence:         "FAIL_CLOSED_NO_RETRY_FROM_ORDINARY_FACT",
	runnerConsumerBoundary:           "entry_read_only_admission_only",
	existingBrandNewWriterBoundary:   "separate_existing_authority_chain",
	entryWriterBoundary:              "not_implemented",
	recoveryWriterBoundary:           "not_implemented",
	databaseSessionBoundary:          "fresh_dedicated_locked_read_only_until_exact_close",
	databaseTransactionBoundary:      "migration_and_read_write_forbidden",
	beginMigrationBoundary:           "forbidden",
	ledgerMutationBoundary:           "forbidden",
	evidenceMutationBoundary:         "forbidden",
	permitConsumerBoundary:           "none",
	httpSurfaceBoundary:              "not_implemented",
	p2SurfaceBoundary:                "not_implemented",
	providerSideEffectsBoundary:      "forbidden",
	productionDatabaseWritesBoundary: "not_authorized",
	deploymentBoundary:               "not_authorized",
	publicationBoundary:              "not_authorized",
	gateStatusBoundary:               "all_gates_open",
}

var generatedRunnerLedgerEntryAdmissionTransitions = [...]runnerLedgerEntryAdmissionTransition{
	{from: "unclassified", event: "select_entry", to: "session_revalidating"},
	{from: "unclassified", event: "select_unknown", to: "unknown_rejected"},
	{from: "session_revalidating", event: "revalidate_exact_boundary", to: "admission_ready"},
	{from: "session_revalidating", event: "revalidate_failed", to: "admission_closed"},
	{from: "admission_ready", event: "close_without_mutation", to: "admission_closed"},
}

const generatedRunnerLedgerEntryAdmissionPairCount = 5

func generatedRunnerLedgerEntryAdmissionAction(disposition runnerLedgerPreflightDisposition, state RecoveryState, action RecoveryAction) (runnerLedgerEntryAdmissionAction, bool) {
	switch string(disposition) + "\x00" + string(state) + "\x00" + string(action) {
	case "empty_brand_new\u0000brand_new\u0000begin_first_attempt":
		return runnerLedgerEntryAdmissionAction("prepare_entry_admission"), true
	case "empty_brand_new\u0000brand_new_inherited\u0000begin_first_attempt":
		return runnerLedgerEntryAdmissionAction("prepare_entry_admission"), true
	case "empty_brand_new\u0000brand_new_inherited\u0000begin_next_attempt":
		return runnerLedgerEntryAdmissionAction("prepare_entry_admission"), true
	case "partial_next_entry\u0000brand_new_inherited\u0000begin_first_attempt_next_entry":
		return runnerLedgerEntryAdmissionAction("prepare_entry_admission"), true
	case "partial_next_entry\u0000terminal\u0000begin_first_attempt_next_entry":
		return runnerLedgerEntryAdmissionAction("prepare_entry_admission"), true
	default:
		return "", false
	}
}
