// Code generated by scripts/generate-foundation-migration-package.ts; DO NOT EDIT.
package localmigration

var productFoundationRunnerBinding = generatedRunnerBindingSelector{
	selectorID: "product-000055", schemaHead: "000055", migrationCount: 55,
	manifestPath: "services/control-plane/migrations/product/000055/manifest.json", manifestSizeBytes: 128865, manifestRawDigest: "sha256:d46409cbbfeba2940123e664d20db5ee6239a0b24c02f98a4ed1401c0c70045f", manifestDigest: "sha256:0a487466130e9bbb78fe1f888774d438f9b6a07e91d129095458d880562cecf9",
	schemaBundlePath: "services/control-plane/migrations/product/000055/schema-bundle.json", schemaBundleSizeBytes: 87141, schemaBundleRawDigest: "sha256:87053210d54aa6f07e1b800d26c2ab014c89e7e1800705c83964a43e07622d76", schemaBundleDigest: "sha256:0bbd6c01ae6a745dbb183f1820ae86942181f9210721efc69b4ceba75b2294ef",
}
