// Code generated by scripts/generate-platform-migration-runner-binding.ts; DO NOT EDIT.
package localmigration

const (
	runnerBindingProfilePath            = "services/control-plane/migrations/successor/000014/runner-binding/profile.json"
	runnerBindingProfileDigest          = "sha256:7ffe830d854e5037994e2b5019da792a42d97928da456639bcdbfc4c3fa05489"
	runnerBindingProfileBlobDigest      = "sha256:b3bcf86b3bb9a147dce4ccbc1db58c5a6d26c216f72e91eec22c5ac7dbba589c"
	runnerBindingProfileSizeBytes       = 74021
	runnerBindingProfileSchemaURL       = "https://schemas.cloud-agents.dev/platform/migrations/successor/000014/runner-binding/profile.schema.json"
	runnerBindingProfileFormatVersion   = "cloud-agents-platform-migration-runner-binding/v1"
	runnerBindingProfileID              = "cloud-agents-platform-migration-runner-binding/v1"
	runnerBindingProfileDomain          = "cloud-agents-platform-migration-runner-binding/v1"
	runnerBindingInputScope             = "runner-binding-generator-and-focused-verification-closure/v1"
	runnerBindingSourcePath             = "services/control-plane/migrations/successor/000014/runner-binding/authority-source.json"
	runnerBindingSourceRawDigest        = "sha256:f781843d9ec2b086225a95578e66cac3ff4f949bc1ff797e8b36d0bd4a908b9f"
	runnerBindingSourceSizeBytes        = 73687
	runnerBindingSourceSchemaPath       = "services/control-plane/migrations/successor/000014/runner-binding/authority-source.schema.json"
	runnerBindingSourceSchemaRawDigest  = "sha256:d52dedce13d23dffff783ebeecf5bd6dc48bd07162a6915cd937c4ef1c288778"
	runnerBindingSourceSchemaSizeBytes  = 20305
	runnerBindingProfileSchemaPath      = "services/control-plane/migrations/successor/000014/runner-binding/profile.schema.json"
	runnerBindingProfileSchemaRawDigest = "sha256:1f3fc9cc77d68515bcce12ab4174a3aafd21df7bf89e59aeeec8fbb155337c20"
	runnerBindingProfileSchemaSizeBytes = 20385
	runnerBindingAuthorityID            = "D-053-MIG-000014"
	runnerBindingRevision               = "D-053-MIG-000014.r2"
)

type generatedRunnerBindingArtifact struct {
	path      string
	mode      string
	sizeBytes int
	rawDigest string
}

func generatedRunnerBindingSourceArtifact() generatedRunnerBindingArtifact {
	return generatedRunnerBindingArtifact{path: runnerBindingSourcePath, mode: "100644", sizeBytes: runnerBindingSourceSizeBytes, rawDigest: runnerBindingSourceRawDigest}
}

func generatedRunnerBindingProfileArtifact() generatedRunnerBindingArtifact {
	return generatedRunnerBindingArtifact{path: runnerBindingProfilePath, mode: "100644", sizeBytes: runnerBindingProfileSizeBytes, rawDigest: runnerBindingProfileBlobDigest}
}

func generatedRunnerBindingSourceSchemaArtifact() generatedRunnerBindingArtifact {
	return generatedRunnerBindingArtifact{path: runnerBindingSourceSchemaPath, mode: "100644", sizeBytes: runnerBindingSourceSchemaSizeBytes, rawDigest: runnerBindingSourceSchemaRawDigest}
}

func generatedRunnerBindingProfileSchemaArtifact() generatedRunnerBindingArtifact {
	return generatedRunnerBindingArtifact{path: runnerBindingProfileSchemaPath, mode: "100644", sizeBytes: runnerBindingProfileSchemaSizeBytes, rawDigest: runnerBindingProfileSchemaRawDigest}
}

var generatedRunnerBindingR1Artifacts = [...]generatedRunnerBindingArtifact{
	{path: "services/control-plane/migrations/successor/000014/authority-source.json", mode: "100644", sizeBytes: 21698, rawDigest: "sha256:6436c991dc838c353f27f91f9aff3257d02e18a6c3e0535244fe7f7d1d7a5d8e"},
	{path: "services/control-plane/migrations/successor/000014/profile.json", mode: "100644", sizeBytes: 22970, rawDigest: "sha256:668c7e9c0337d1e50c81dde0ac465561d4ac4eb5f6d14f7fd8b2e26ef672250a"},
	{path: "services/control-plane/migrations/successor/000014/authority-source.schema.json", mode: "100644", sizeBytes: 9052, rawDigest: "sha256:b7ccd78f1c8cc3969b0d2c8846157dc645595e397ab97942522ecfbe163c873c"},
	{path: "services/control-plane/migrations/successor/000014/profile.schema.json", mode: "100644", sizeBytes: 10010, rawDigest: "sha256:314cc945796fac537bc89a3c09d2e1d6681fa06e028ea0ddecb3a776eb31e827"},
}

type generatedRunnerBindingSelector struct {
	selectorID            string
	schemaHead            string
	manifestPath          string
	manifestSizeBytes     int
	manifestRawDigest     string
	manifestDigest        string
	schemaBundlePath      string
	schemaBundleSizeBytes int
	schemaBundleRawDigest string
	schemaBundleDigest    string
	migrationCount        int
}

var generatedRunnerBindingSelectors = [...]generatedRunnerBindingSelector{
	{selectorID: "canonical-000013", schemaHead: "000013", manifestPath: "services/control-plane/migrations/manifest.json", manifestSizeBytes: 33976, manifestRawDigest: "sha256:95a584a9e517d68e9a904fadfc76f84dcdbd8b532a24d8716468d0ff53d59d6b", manifestDigest: "sha256:56af03a65461e2009cf73c16ac2b1d74d856f68e3efc8b363ab84c537660c4d1", schemaBundlePath: "services/control-plane/migrations/schema-bundle.json", schemaBundleSizeBytes: 22443, schemaBundleRawDigest: "sha256:d5ce27597e2218240a276dbbec01431e4fe26774e195b70445078d8662a3826d", schemaBundleDigest: "sha256:c7e08e81b463d04dd267438ac636811200586d5d84d8cb2e8d18799bd2c5faca", migrationCount: 13},
	{selectorID: "successor-000014", schemaHead: "000014", manifestPath: "services/control-plane/migrations/successor/000014/manifest.json", manifestSizeBytes: 36291, manifestRawDigest: "sha256:961ccac428f8bf0d55a828fd93ae8e2085ae17d34c09cb2b46c28f653851f8ae", manifestDigest: "sha256:1ece795f54e049a15e4de37f351841be0ba611f8eb0be6eaf1aa68dc0145b620", schemaBundlePath: "services/control-plane/migrations/successor/000014/schema-bundle.json", schemaBundleSizeBytes: 23970, schemaBundleRawDigest: "sha256:d90661ac0271b78de563e565bb861b35d570be30fa788131e9813dde56870edc", schemaBundleDigest: "sha256:2f363d4dc412803a3c126dd9b85f4e2fe7109b92b04706d077a786fdaa673677", migrationCount: 14},
}
