// Code generated by scripts/generate-worker-localdev-launcher-profile.ts; DO NOT EDIT.

package worker

const (
	WorkerLocalDevLauncherProfileID                = "cloud-agents/worker-localdev-launcher/v1alpha1"
	WorkerLocalDevLauncherAuthorityID              = "D-056-WORKER-LOCALDEV-LAUNCHER-000001"
	WorkerLocalDevLauncherRevision                 = "D-056-WORKER-LOCALDEV-LAUNCHER-000001.r1"
	WorkerLocalDevLauncherProfileDigest            = "sha256:dc83b89cad24104093e86e69d14743ca9bbc1b106113c90ca52bfa9bde04b72e"
	WorkerLocalDevLauncherSourceDigest             = "sha256:9af247b7deffecd2188a19ad1c4859ca8fb7332c15ed6aa980f15eee99663699"
	WorkerLocalDevLauncherInputManifestDigest      = "sha256:ca5849afe9f82446f1e9e1439e3cbd6303f668e292b0f924a99d9fd4d82fc9ea"
	WorkerLocalDevLauncherHTTPRoutePrefix          = "/cloudagents.worker.v1alpha1.WorkerExecutionService/"
	WorkerLocalDevLauncherHealthRoute              = "/healthz"
	WorkerLocalDevLauncherWorkerIdentitySPIFFE     = "spiffe://cloud-agents.local/worker/localdev"
	WorkerLocalDevLauncherSupervisorIdentitySPIFFE = "spiffe://cloud-agents.local/supervisor/localdev"
	WorkerLocalDevLauncherLeaseID                  = "worker-localdev-lease-000001"
	WorkerLocalDevLauncherGeneration               = 1
)

type WorkerLocalDevLauncherProfile struct {
	ID, AuthorityID, Revision, ProfileDigest, SourceDigest, InputManifestDigest                                                                                                 string
	Mode, Transport                                                                                                                                                             string
	RoutePrefix, HealthRoute, WorkerIdentitySPIFFE, SupervisorIdentitySPIFFE, LeaseID                                                                                           string
	Generation                                                                                                                                                                  uint64
	ExternalSideEffects                                                                                                                                                         bool
	CompleteLedger, EntryWriter, RecoveryWriter, DatabaseWrites, DurablePersistence, Provider, Runtime, ProductionHTTP, PublicHTTP, P2, Deployment, Publication, GateTransition string
}

var GeneratedWorkerLocalDevLauncherProfile = WorkerLocalDevLauncherProfile{ID: WorkerLocalDevLauncherProfileID, AuthorityID: WorkerLocalDevLauncherAuthorityID, Revision: WorkerLocalDevLauncherRevision, ProfileDigest: WorkerLocalDevLauncherProfileDigest, SourceDigest: WorkerLocalDevLauncherSourceDigest, InputManifestDigest: WorkerLocalDevLauncherInputManifestDigest, Mode: "localdev_only", Transport: "loopback_http_connect", RoutePrefix: WorkerLocalDevLauncherHTTPRoutePrefix, HealthRoute: WorkerLocalDevLauncherHealthRoute, WorkerIdentitySPIFFE: WorkerLocalDevLauncherWorkerIdentitySPIFFE, SupervisorIdentitySPIFFE: WorkerLocalDevLauncherSupervisorIdentitySPIFFE, LeaseID: WorkerLocalDevLauncherLeaseID, Generation: WorkerLocalDevLauncherGeneration, ExternalSideEffects: false, CompleteLedger: "no_op", EntryWriter: "not_implemented", RecoveryWriter: "not_implemented", DatabaseWrites: "forbidden", DurablePersistence: "forbidden", Provider: "forbidden", Runtime: "forbidden", ProductionHTTP: "forbidden", PublicHTTP: "forbidden", P2: "forbidden", Deployment: "forbidden", Publication: "forbidden", GateTransition: "forbidden"}

func (p WorkerLocalDevLauncherProfile) Valid() bool {
	return p == GeneratedWorkerLocalDevLauncherProfile
}

func WorkerLocalDevLauncherProfileAuthority() WorkerLocalDevLauncherProfile {
	return GeneratedWorkerLocalDevLauncherProfile
}
