// Code generated by scripts/generate-worker-localdev-launcher-profile.ts; DO NOT EDIT.

package worker

const (
	WorkerLocalDevLauncherProfileID                = "cloud-agents/worker-localdev-launcher/v1alpha1"
	WorkerLocalDevLauncherAuthorityID              = "D-056-WORKER-LOCALDEV-LAUNCHER-000001"
	WorkerLocalDevLauncherRevision                 = "D-056-WORKER-LOCALDEV-LAUNCHER-000001.r1"
	WorkerLocalDevLauncherProfileDigest            = "sha256:ca95d77aa10aeea6a5c4282bb3d8b7419ca23c8a4e93de079d4b93ceccca86a2"
	WorkerLocalDevLauncherSourceDigest             = "sha256:197c3eac490ef4cf161a13df8dcd07fb15d4a0102a2f6494c3be029eeb5e2941"
	WorkerLocalDevLauncherInputManifestDigest      = "sha256:e84694ee3559b36eefe5bec8b9b3fa419c912f8f97f0c700cace03a2d5366e60"
	WorkerLocalDevLauncherHTTPRoutePrefix          = "/cloudagents.worker.v1alpha1.WorkerExecutionService/"
	WorkerLocalDevLauncherHealthRoute              = "/healthz"
	WorkerLocalDevLauncherWorkerIdentitySPIFFE     = "spiffe://cloud-agents.local/worker/localdev"
	WorkerLocalDevLauncherSupervisorIdentitySPIFFE = "spiffe://cloud-agents.local/supervisor/localdev"
	WorkerLocalDevLauncherLeaseID                  = "worker-localdev-lease-000001"
	WorkerLocalDevLauncherGeneration               = 1
)

type WorkerLocalDevLauncherProfile struct {
	ID, AuthorityID, Revision, ProfileDigest, SourceDigest, InputManifestDigest                                                                                                 string
	Mode, Transport                                                                                                                                                             string
	RoutePrefix, HealthRoute, WorkerIdentitySPIFFE, SupervisorIdentitySPIFFE, LeaseID                                                                                           string
	Generation                                                                                                                                                                  uint64
	ExternalSideEffects                                                                                                                                                         bool
	CompleteLedger, EntryWriter, RecoveryWriter, DatabaseWrites, DurablePersistence, Provider, Runtime, ProductionHTTP, PublicHTTP, P2, Deployment, Publication, GateTransition string
}

var GeneratedWorkerLocalDevLauncherProfile = WorkerLocalDevLauncherProfile{ID: WorkerLocalDevLauncherProfileID, AuthorityID: WorkerLocalDevLauncherAuthorityID, Revision: WorkerLocalDevLauncherRevision, ProfileDigest: WorkerLocalDevLauncherProfileDigest, SourceDigest: WorkerLocalDevLauncherSourceDigest, InputManifestDigest: WorkerLocalDevLauncherInputManifestDigest, Mode: "localdev_only", Transport: "loopback_http_connect", RoutePrefix: WorkerLocalDevLauncherHTTPRoutePrefix, HealthRoute: WorkerLocalDevLauncherHealthRoute, WorkerIdentitySPIFFE: WorkerLocalDevLauncherWorkerIdentitySPIFFE, SupervisorIdentitySPIFFE: WorkerLocalDevLauncherSupervisorIdentitySPIFFE, LeaseID: WorkerLocalDevLauncherLeaseID, Generation: WorkerLocalDevLauncherGeneration, ExternalSideEffects: false, CompleteLedger: "no_op", EntryWriter: "not_implemented", RecoveryWriter: "not_implemented", DatabaseWrites: "forbidden", DurablePersistence: "forbidden", Provider: "forbidden", Runtime: "forbidden", ProductionHTTP: "forbidden", PublicHTTP: "forbidden", P2: "forbidden", Deployment: "forbidden", Publication: "forbidden", GateTransition: "forbidden"}

func (p WorkerLocalDevLauncherProfile) Valid() bool {
	return p == GeneratedWorkerLocalDevLauncherProfile
}

func WorkerLocalDevLauncherProfileAuthority() WorkerLocalDevLauncherProfile {
	return GeneratedWorkerLocalDevLauncherProfile
}
