// Code generated by scripts/generate-worker-localdev-bridge-profile.ts; DO NOT EDIT.

package worker

const (
	WorkerLocalDevBridgeProfileID                = "cloud-agents/worker-supervisor-operation-dispatch/launcher-localdev-v1alpha1"
	WorkerLocalDevBridgeAuthorityID              = "D-057-WORKER-LOCALDEV-BRIDGE-000001"
	WorkerLocalDevBridgeRevision                 = "D-057-WORKER-LOCALDEV-BRIDGE-000001.r1"
	WorkerLocalDevBridgeProfileDigest            = "sha256:06899bff4ca8fe12762be3c146fd1220b6eacc6da6687189846b6b62e5bb8ca3"
	WorkerLocalDevBridgeSourceDigest             = "sha256:a4225472b83f540a591ce483058e8429d404ee497ea5ad8af1c672056771fc1a"
	WorkerLocalDevBridgeInputManifestDigest      = "sha256:3a19d9e902f57605d60a4f853704ce00f1a28f28fee5a81d73f41ec394939c70"
	WorkerLocalDevBridgeHTTPRoutePrefix          = "/cloudagents.worker.v1alpha1.WorkerExecutionService/"
	WorkerLocalDevBridgeHealthRoute              = "/healthz"
	WorkerLocalDevBridgeWorkerIdentitySPIFFE     = "spiffe://cloud-agents.local/worker/localdev"
	WorkerLocalDevBridgeSupervisorIdentitySPIFFE = "spiffe://cloud-agents.local/supervisor/localdev"
	WorkerLocalDevBridgeLeaseID                  = "worker-localdev-lease-000001"
	WorkerLocalDevBridgeGeneration               = 1
)

type WorkerLocalDevBridgeProfile struct {
	ID, AuthorityID, Revision, ProfileDigest, SourceDigest, InputManifestDigest                                                                                                 string
	Mode, Transport                                                                                                                                                             string
	RoutePrefix, HealthRoute, WorkerIdentitySPIFFE, SupervisorIdentitySPIFFE, LeaseID                                                                                           string
	Generation                                                                                                                                                                  uint64
	ExternalSideEffects                                                                                                                                                         bool
	CompleteLedger, EntryWriter, RecoveryWriter, DatabaseWrites, DurablePersistence, Provider, Runtime, ProductionHTTP, PublicHTTP, P2, Deployment, Publication, GateTransition string
}

var GeneratedWorkerLocalDevBridgeProfile = WorkerLocalDevBridgeProfile{ID: WorkerLocalDevBridgeProfileID, AuthorityID: WorkerLocalDevBridgeAuthorityID, Revision: WorkerLocalDevBridgeRevision, ProfileDigest: WorkerLocalDevBridgeProfileDigest, SourceDigest: WorkerLocalDevBridgeSourceDigest, InputManifestDigest: WorkerLocalDevBridgeInputManifestDigest, Mode: "localdev_only", Transport: "loopback_http_connect", RoutePrefix: WorkerLocalDevBridgeHTTPRoutePrefix, HealthRoute: WorkerLocalDevBridgeHealthRoute, WorkerIdentitySPIFFE: WorkerLocalDevBridgeWorkerIdentitySPIFFE, SupervisorIdentitySPIFFE: WorkerLocalDevBridgeSupervisorIdentitySPIFFE, LeaseID: WorkerLocalDevBridgeLeaseID, Generation: WorkerLocalDevBridgeGeneration, ExternalSideEffects: false, CompleteLedger: "no_op", EntryWriter: "not_implemented", RecoveryWriter: "not_implemented", DatabaseWrites: "forbidden", DurablePersistence: "forbidden", Provider: "forbidden", Runtime: "forbidden", ProductionHTTP: "forbidden", PublicHTTP: "forbidden", P2: "forbidden", Deployment: "forbidden", Publication: "forbidden", GateTransition: "forbidden"}

func (p WorkerLocalDevBridgeProfile) Valid() bool {
	return p.ID == WorkerLocalDevBridgeProfileID && p.AuthorityID == WorkerLocalDevBridgeAuthorityID && p.Revision == WorkerLocalDevBridgeRevision && p.ProfileDigest == WorkerLocalDevBridgeProfileDigest && p.SourceDigest == WorkerLocalDevBridgeSourceDigest && p.InputManifestDigest == WorkerLocalDevBridgeInputManifestDigest && p.Mode == "localdev_only" && p.Transport == "loopback_http_connect" && p.RoutePrefix == WorkerLocalDevBridgeHTTPRoutePrefix && p.HealthRoute == WorkerLocalDevBridgeHealthRoute && p.WorkerIdentitySPIFFE == WorkerLocalDevBridgeWorkerIdentitySPIFFE && p.SupervisorIdentitySPIFFE == WorkerLocalDevBridgeSupervisorIdentitySPIFFE && p.LeaseID == WorkerLocalDevBridgeLeaseID && p.Generation == WorkerLocalDevBridgeGeneration && !p.ExternalSideEffects && p.CompleteLedger == "no_op" && p.EntryWriter == "not_implemented" && p.RecoveryWriter == "not_implemented" && p.DatabaseWrites == "forbidden" && p.DurablePersistence == "forbidden" && p.Provider == "forbidden" && p.Runtime == "forbidden" && p.ProductionHTTP == "forbidden" && p.PublicHTTP == "forbidden" && p.P2 == "forbidden" && p.Deployment == "forbidden" && p.Publication == "forbidden" && p.GateTransition == "forbidden"
}

func WorkerLocalDevBridgeProfileValid() bool { return GeneratedWorkerLocalDevBridgeProfile.Valid() }

func WorkerLocalDevBridgeProfileAuthority() WorkerLocalDevBridgeProfile {
	return GeneratedWorkerLocalDevBridgeProfile
}
