// Code generated by scripts/generate-worker-localdev-launcher-profile.ts; DO NOT EDIT.

package worker

const (
	WorkerLocalDevLauncherProfileID                = "cloud-agents/worker-localdev-launcher/v1alpha1"
	WorkerLocalDevLauncherAuthorityID              = "D-056-WORKER-LOCALDEV-LAUNCHER-000001"
	WorkerLocalDevLauncherRevision                 = "D-056-WORKER-LOCALDEV-LAUNCHER-000001.r1"
	WorkerLocalDevLauncherProfileDigest            = "sha256:13d33e8b243a33268c9a5f689470f93c6c6e8c3ec414227a79200d08e0bf6d1a"
	WorkerLocalDevLauncherSourceDigest             = "sha256:6d4087b506bb093b6190d1ac736c97fbab412825b0cbe0c717babd6150d59c38"
	WorkerLocalDevLauncherInputManifestDigest      = "sha256:af7eacc94ea920f2bdb66e785ff1a1f85adafef9645c9ca9d7073095904f0efd"
	WorkerLocalDevLauncherHTTPRoutePrefix          = "/cloudagents.worker.v1alpha1.WorkerExecutionService/"
	WorkerLocalDevLauncherHealthRoute              = "/healthz"
	WorkerLocalDevLauncherWorkerIdentitySPIFFE     = "spiffe://cloud-agents.local/worker/localdev"
	WorkerLocalDevLauncherSupervisorIdentitySPIFFE = "spiffe://cloud-agents.local/supervisor/localdev"
	WorkerLocalDevLauncherLeaseID                  = "worker-localdev-lease-000001"
	WorkerLocalDevLauncherGeneration               = 1
)

type WorkerLocalDevLauncherProfile struct {
	ID, AuthorityID, Revision, ProfileDigest, SourceDigest, InputManifestDigest                                                                                                 string
	Mode, Transport                                                                                                                                                             string
	RoutePrefix, HealthRoute, WorkerIdentitySPIFFE, SupervisorIdentitySPIFFE, LeaseID                                                                                           string
	Generation                                                                                                                                                                  uint64
	ExternalSideEffects                                                                                                                                                         bool
	CompleteLedger, EntryWriter, RecoveryWriter, DatabaseWrites, DurablePersistence, Provider, Runtime, ProductionHTTP, PublicHTTP, P2, Deployment, Publication, GateTransition string
}

var GeneratedWorkerLocalDevLauncherProfile = WorkerLocalDevLauncherProfile{ID: WorkerLocalDevLauncherProfileID, AuthorityID: WorkerLocalDevLauncherAuthorityID, Revision: WorkerLocalDevLauncherRevision, ProfileDigest: WorkerLocalDevLauncherProfileDigest, SourceDigest: WorkerLocalDevLauncherSourceDigest, InputManifestDigest: WorkerLocalDevLauncherInputManifestDigest, Mode: "localdev_only", Transport: "loopback_http_connect", RoutePrefix: WorkerLocalDevLauncherHTTPRoutePrefix, HealthRoute: WorkerLocalDevLauncherHealthRoute, WorkerIdentitySPIFFE: WorkerLocalDevLauncherWorkerIdentitySPIFFE, SupervisorIdentitySPIFFE: WorkerLocalDevLauncherSupervisorIdentitySPIFFE, LeaseID: WorkerLocalDevLauncherLeaseID, Generation: WorkerLocalDevLauncherGeneration, ExternalSideEffects: false, CompleteLedger: "no_op", EntryWriter: "not_implemented", RecoveryWriter: "not_implemented", DatabaseWrites: "forbidden", DurablePersistence: "forbidden", Provider: "forbidden", Runtime: "forbidden", ProductionHTTP: "forbidden", PublicHTTP: "forbidden", P2: "forbidden", Deployment: "forbidden", Publication: "forbidden", GateTransition: "forbidden"}

func (p WorkerLocalDevLauncherProfile) Valid() bool {
	return p == GeneratedWorkerLocalDevLauncherProfile
}

func WorkerLocalDevLauncherProfileAuthority() WorkerLocalDevLauncherProfile {
	return GeneratedWorkerLocalDevLauncherProfile
}
