// Code generated by scripts/generate-worker-localdev-bridge-profile.ts; DO NOT EDIT.

package worker

const (
	WorkerLocalDevBridgeProfileID                = "cloud-agents/worker-supervisor-operation-dispatch/launcher-localdev-v1alpha1"
	WorkerLocalDevBridgeAuthorityID              = "D-057-WORKER-LOCALDEV-BRIDGE-000001"
	WorkerLocalDevBridgeRevision                 = "D-057-WORKER-LOCALDEV-BRIDGE-000001.r1"
	WorkerLocalDevBridgeProfileDigest            = "sha256:41c6df041a06a501e6a0351f4301d041fbb6658ad4183d21bd7d5d54845fa23f"
	WorkerLocalDevBridgeSourceDigest             = "sha256:08fdb3e4dc42b115f2475d20d8da88042b2a4cd94181289c05744fafaf3325a7"
	WorkerLocalDevBridgeInputManifestDigest      = "sha256:39373d747c914382fbad73bc86b0f36c91d17ce58019f1117d71f8511b5ab9e6"
	WorkerLocalDevBridgeHTTPRoutePrefix          = "/cloudagents.worker.v1alpha1.WorkerExecutionService/"
	WorkerLocalDevBridgeHealthRoute              = "/healthz"
	WorkerLocalDevBridgeWorkerIdentitySPIFFE     = "spiffe://cloud-agents.local/worker/localdev"
	WorkerLocalDevBridgeSupervisorIdentitySPIFFE = "spiffe://cloud-agents.local/supervisor/localdev"
	WorkerLocalDevBridgeLeaseID                  = "worker-localdev-lease-000001"
	WorkerLocalDevBridgeGeneration               = 1
)

type WorkerLocalDevBridgeProfile struct {
	ID, AuthorityID, Revision, ProfileDigest, SourceDigest, InputManifestDigest                                                                                                 string
	Mode, Transport                                                                                                                                                             string
	RoutePrefix, HealthRoute, WorkerIdentitySPIFFE, SupervisorIdentitySPIFFE, LeaseID                                                                                           string
	Generation                                                                                                                                                                  uint64
	ExternalSideEffects                                                                                                                                                         bool
	CompleteLedger, EntryWriter, RecoveryWriter, DatabaseWrites, DurablePersistence, Provider, Runtime, ProductionHTTP, PublicHTTP, P2, Deployment, Publication, GateTransition string
}

var GeneratedWorkerLocalDevBridgeProfile = WorkerLocalDevBridgeProfile{ID: WorkerLocalDevBridgeProfileID, AuthorityID: WorkerLocalDevBridgeAuthorityID, Revision: WorkerLocalDevBridgeRevision, ProfileDigest: WorkerLocalDevBridgeProfileDigest, SourceDigest: WorkerLocalDevBridgeSourceDigest, InputManifestDigest: WorkerLocalDevBridgeInputManifestDigest, Mode: "localdev_only", Transport: "loopback_http_connect", RoutePrefix: WorkerLocalDevBridgeHTTPRoutePrefix, HealthRoute: WorkerLocalDevBridgeHealthRoute, WorkerIdentitySPIFFE: WorkerLocalDevBridgeWorkerIdentitySPIFFE, SupervisorIdentitySPIFFE: WorkerLocalDevBridgeSupervisorIdentitySPIFFE, LeaseID: WorkerLocalDevBridgeLeaseID, Generation: WorkerLocalDevBridgeGeneration, ExternalSideEffects: false, CompleteLedger: "no_op", EntryWriter: "not_implemented", RecoveryWriter: "not_implemented", DatabaseWrites: "forbidden", DurablePersistence: "forbidden", Provider: "forbidden", Runtime: "forbidden", ProductionHTTP: "forbidden", PublicHTTP: "forbidden", P2: "forbidden", Deployment: "forbidden", Publication: "forbidden", GateTransition: "forbidden"}

func (p WorkerLocalDevBridgeProfile) Valid() bool {
	return p.ID == WorkerLocalDevBridgeProfileID && p.AuthorityID == WorkerLocalDevBridgeAuthorityID && p.Revision == WorkerLocalDevBridgeRevision && p.ProfileDigest == WorkerLocalDevBridgeProfileDigest && p.SourceDigest == WorkerLocalDevBridgeSourceDigest && p.InputManifestDigest == WorkerLocalDevBridgeInputManifestDigest && p.Mode == "localdev_only" && p.Transport == "loopback_http_connect" && p.RoutePrefix == WorkerLocalDevBridgeHTTPRoutePrefix && p.HealthRoute == WorkerLocalDevBridgeHealthRoute && p.WorkerIdentitySPIFFE == WorkerLocalDevBridgeWorkerIdentitySPIFFE && p.SupervisorIdentitySPIFFE == WorkerLocalDevBridgeSupervisorIdentitySPIFFE && p.LeaseID == WorkerLocalDevBridgeLeaseID && p.Generation == WorkerLocalDevBridgeGeneration && !p.ExternalSideEffects && p.CompleteLedger == "no_op" && p.EntryWriter == "not_implemented" && p.RecoveryWriter == "not_implemented" && p.DatabaseWrites == "forbidden" && p.DurablePersistence == "forbidden" && p.Provider == "forbidden" && p.Runtime == "forbidden" && p.ProductionHTTP == "forbidden" && p.PublicHTTP == "forbidden" && p.P2 == "forbidden" && p.Deployment == "forbidden" && p.Publication == "forbidden" && p.GateTransition == "forbidden"
}

func WorkerLocalDevBridgeProfileValid() bool { return GeneratedWorkerLocalDevBridgeProfile.Valid() }

func WorkerLocalDevBridgeProfileAuthority() WorkerLocalDevBridgeProfile {
	return GeneratedWorkerLocalDevBridgeProfile
}
