// Code generated by scripts/generate-platform-json-sdks.ts; DO NOT EDIT.
// Contract manifest: sha256:f2b1b9e64249fc9f72cceb857073e49957b78c6f3ab0b7f8d2d01b042a821e37
// Generator source manifest: sha256:41bdc36584f3310c1bbb248c3002ab1ad1f9fdf1617876d72752937e5dca160a
// Generation config: sha256:18de49cca34f10a2a544fca483dd2b2f001cfcd5394a5e6a1d1636b0ec05fc2c

import {
  type NamespaceRef,
  type SubjectRef,
  validateNamespaceRef,
  validateSubjectRef,
} from "./index.js";

export const platformApiVersion = "platform.cloud-agents.dev/v1alpha1" as const;
export type JSONSidecar = Readonly<Record<string, string>>;
export type ResponseEnvelope<T> = Readonly<{ value: T; unknown: JSONSidecar }>;
type ResponseShape = Readonly<{
  fields?: Readonly<Record<string, ResponseShape>>;
  item?: ResponseShape;
}>;
export type StableError = Readonly<{
  code: string;
  retryable: boolean;
  retryAfterSeconds?: number;
}>;
export type Problem = Readonly<{
  type: string;
  title: string;
  status: number;
  error: StableError;
  requestId: string;
}>;
export type Pagination = Readonly<{ pageSize: number; pageToken?: string }>;
export type WatchCursor = Readonly<{ cursor: string; resourceVersion: string; expiresAt: string }>;
export type Idempotency = Readonly<{ key: string; requestDigest: `sha256:${string}` }>;

export class JSONContractError extends TypeError {
  readonly code: string;
  readonly path: string;
  constructor(code: string, path = "") {
    super(`${code}${path ? ` at ${path}` : ""}`);
    this.name = "JSONContractError";
    this.code = code;
    this.path = path;
  }
}
const error = (code: string, path = ""): never => {
  throw new JSONContractError(code, path);
};

export type ResourceMetadata = Readonly<{
  uid: string;
  name: string;
  tenantRef: NamespaceRef;
  resourceVersion: string;
  createdAt: string;
  updatedAt?: string;
}>;
export type TenantSpec = Readonly<{ displayName: string; state: "active" | "suspended" }>;
export type PlatformTenant = Readonly<{
  apiVersion: typeof platformApiVersion;
  kind: "PlatformTenant";
  metadata: ResourceMetadata;
  spec: TenantSpec;
}>;
export type OrganizationSpec = Readonly<{
  tenantRef: NamespaceRef;
  displayName: string;
  state: "active" | "suspended";
}>;
export type Organization = Readonly<{
  apiVersion: typeof platformApiVersion;
  kind: "Organization";
  metadata: ResourceMetadata;
  spec: OrganizationSpec;
}>;
export type ProjectCreateRequest = Readonly<{
  name: string;
  organizationRef: NamespaceRef;
  displayName: string;
}>;
export type ProjectSpec = Readonly<{
  tenantRef: NamespaceRef;
  organizationRef: NamespaceRef;
  displayName: string;
  state: "active" | "suspended" | "archived";
}>;
export type Project = Readonly<{
  apiVersion: typeof platformApiVersion;
  kind: "Project";
  metadata: ResourceMetadata;
  spec: ProjectSpec;
}>;
export type AuthorizationScope = Readonly<{
  level: "platform" | "tenant" | "organization" | "project";
  ref?: NamespaceRef;
}>;
export type MembershipSpec = Readonly<{
  tenantRef: NamespaceRef;
  subject: SubjectRef;
  scope: AuthorizationScope;
  state: "active" | "suspended" | "revoked";
  expiresAt?: string;
}>;
export type Membership = Readonly<{
  apiVersion: typeof platformApiVersion;
  kind: "Membership";
  metadata: ResourceMetadata;
  spec: MembershipSpec;
}>;
export type RoleSpec = Readonly<{
  name: RoleName;
  version: number;
  permissions: readonly string[];
  state: "active" | "deprecated" | "revoked";
}>;
export type Role = Readonly<{
  apiVersion: typeof platformApiVersion;
  kind: "Role";
  metadata: ResourceMetadata;
  spec: RoleSpec;
}>;
export type RoleName =
  | "platform.admin"
  | "tenant.admin"
  | "organization.admin"
  | "project.admin"
  | "project.operator"
  | "project.developer"
  | "project.viewer";
export type RoleBindingSpec = Readonly<{
  tenantRef: NamespaceRef;
  subject: SubjectRef;
  roleName: RoleName;
  roleVersion: number;
  scope: AuthorizationScope;
  state: "active" | "revoked";
  expiresAt?: string;
}>;
export type RoleBinding = Readonly<{
  apiVersion: typeof platformApiVersion;
  kind: "RoleBinding";
  metadata: ResourceMetadata;
  spec: RoleBindingSpec;
}>;

const scalarResponseShape: ResponseShape = Object.freeze({});
const referenceResponseShape: ResponseShape = {
  fields: { namespace: scalarResponseShape, kind: scalarResponseShape, id: scalarResponseShape },
};
const subjectResponseShape: ResponseShape = {
  fields: { kind: scalarResponseShape, issuer: scalarResponseShape, subject: scalarResponseShape },
};
const scopeResponseShape: ResponseShape = {
  fields: { level: scalarResponseShape, ref: referenceResponseShape },
};
const metadataResponseShape: ResponseShape = {
  fields: {
    uid: scalarResponseShape,
    name: scalarResponseShape,
    tenantRef: referenceResponseShape,
    resourceVersion: scalarResponseShape,
    createdAt: scalarResponseShape,
    updatedAt: scalarResponseShape,
  },
};
const resourceResponseShape = (spec: Readonly<Record<string, ResponseShape>>): ResponseShape => ({
  fields: {
    apiVersion: scalarResponseShape,
    kind: scalarResponseShape,
    metadata: metadataResponseShape,
    spec: { fields: spec },
  },
});
const tenantResponseShape = resourceResponseShape({
  displayName: scalarResponseShape,
  state: scalarResponseShape,
});
const organizationResponseShape = resourceResponseShape({
  tenantRef: referenceResponseShape,
  displayName: scalarResponseShape,
  state: scalarResponseShape,
});
const projectResponseShape = resourceResponseShape({
  tenantRef: referenceResponseShape,
  organizationRef: referenceResponseShape,
  displayName: scalarResponseShape,
  state: scalarResponseShape,
});
const membershipResponseShape = resourceResponseShape({
  tenantRef: referenceResponseShape,
  subject: subjectResponseShape,
  scope: scopeResponseShape,
  state: scalarResponseShape,
  expiresAt: scalarResponseShape,
});
const roleResponseShape = resourceResponseShape({
  name: scalarResponseShape,
  version: scalarResponseShape,
  permissions: { item: scalarResponseShape },
  state: scalarResponseShape,
});
const roleBindingResponseShape = resourceResponseShape({
  tenantRef: referenceResponseShape,
  subject: subjectResponseShape,
  roleName: scalarResponseShape,
  roleVersion: scalarResponseShape,
  scope: scopeResponseShape,
  state: scalarResponseShape,
  expiresAt: scalarResponseShape,
});
const watchCursorResponseShape: ResponseShape = {
  fields: {
    cursor: scalarResponseShape,
    resourceVersion: scalarResponseShape,
    expiresAt: scalarResponseShape,
  },
};

const roleNames = new Set<RoleName>([
  "platform.admin",
  "tenant.admin",
  "organization.admin",
  "project.admin",
  "project.operator",
  "project.developer",
  "project.viewer",
]);
const permissionPattern = /^[a-z][a-z0-9-]*\.(?:create|get|list|watch|update|delete|act|bind)$/u;
const identifierPattern = /^[A-Za-z0-9](?:[A-Za-z0-9._~-]{0,126}[A-Za-z0-9])?$/u;

function record(value: unknown, path = ""): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value))
    error("INVALID_JSON_OBJECT", path);
  return value as Record<string, unknown>;
}
function strictRecord(
  value: unknown,
  allowed: readonly string[],
  required: readonly string[],
  path = "",
): Record<string, unknown> {
  const source = record(value, path);
  const keys = Object.keys(source);
  for (const key of keys) if (!allowed.includes(key)) error("UNKNOWN_FIELD", `${path}/${key}`);
  for (const key of required)
    if (!Object.hasOwn(source, key)) error("MISSING_FIELD", `${path}/${key}`);
  return source;
}
function string(value: unknown, path: string): string {
  if (typeof value !== "string") error("INVALID_FIELD_TYPE", path);
  const text = value as string;
  assertScalar(text, path);
  return text;
}
function boundedString(value: unknown, min: number, max: number, path: string): string {
  const text = string(value, path);
  if ([...text].length < min || [...text].length > max) error("INVALID_STRING", path);
  return text;
}
function identifier(value: unknown, path: string): string {
  const text = string(value, path);
  if (text.length < 1 || text.length > 128 || !identifierPattern.test(text))
    error("INVALID_IDENTIFIER", path);
  return text;
}
function integer(value: unknown, min: number, max: number, path: string): number {
  if (typeof value !== "number" || !Number.isInteger(value) || value < min || value > max)
    error("INVALID_INTEGER", path);
  return value as number;
}
function enumValue<T extends string>(value: unknown, values: readonly T[], path: string): T {
  const text = string(value, path) as T;
  if (!values.includes(text)) error("INVALID_ENUM", path);
  return text;
}
function roleNameValue(value: unknown, path: string): RoleName {
  const text = string(value, path) as RoleName;
  if (!roleNames.has(text)) error("UNKNOWN_ROLE", path);
  return text;
}
function dateTime(value: unknown, path: string): string {
  const text = boundedString(value, 1, 64, path);
  if (
    !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:\d{2})$/u.test(text) ||
    Number.isNaN(Date.parse(text))
  )
    error("INVALID_DATE_TIME", path);
  return text;
}
function absoluteURI(value: unknown, path: string): string {
  const text = boundedString(value, 1, 512, path);
  try {
    const parsed = new URL(text);
    if (!parsed.protocol) error("INVALID_URI", path);
  } catch (cause) {
    if (cause instanceof JSONContractError) throw cause;
    error("INVALID_URI", path);
  }
  return text;
}
function assertScalar(value: string, path: string): void {
  for (let index = 0; index < value.length; index++) {
    const code = value.charCodeAt(index);
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) error("INVALID_UNICODE_SCALAR", path);
      index++;
    } else if (code >= 0xdc00 && code <= 0xdfff) error("INVALID_UNICODE_SCALAR", path);
  }
}
function namespace(value: unknown, expectedKind: string, path: string): NamespaceRef {
  const source = strictRecord(
    value,
    ["namespace", "kind", "id"],
    ["namespace", "kind", "id"],
    path,
  );
  const ref = {
    namespace: string(source.namespace, `${path}/namespace`),
    kind: string(source.kind, `${path}/kind`),
    id: boundedString(source.id, 1, 256, `${path}/id`),
  };
  if (ref.namespace !== "cloud-agents" || ref.kind !== expectedKind)
    error("NAMESPACE_REF_MISMATCH", path);
  validateNamespaceRef(ref as NamespaceRef);
  return Object.freeze(ref) as NamespaceRef;
}
function metadata(value: unknown, path = "/metadata"): ResourceMetadata {
  const source = strictRecord(
    value,
    ["uid", "name", "tenantRef", "resourceVersion", "createdAt", "updatedAt"],
    ["uid", "name", "tenantRef", "resourceVersion", "createdAt"],
    path,
  );
  const resourceVersion = string(source.resourceVersion, `${path}/resourceVersion`);
  if (!/^(?:0|[1-9][0-9]*)$/u.test(resourceVersion) || resourceVersion.length > 20)
    error("INVALID_RESOURCE_VERSION", `${path}/resourceVersion`);
  const result: ResourceMetadata = {
    uid: identifier(source.uid, `${path}/uid`),
    name: identifier(source.name, `${path}/name`),
    tenantRef: namespace(source.tenantRef, "tenant", `${path}/tenantRef`),
    resourceVersion,
    createdAt: dateTime(source.createdAt, `${path}/createdAt`),
  };
  if (source.updatedAt !== undefined)
    return { ...result, updatedAt: dateTime(source.updatedAt, `${path}/updatedAt`) };
  return result;
}
function base(
  value: unknown,
  kind: string,
): { apiVersion: typeof platformApiVersion; kind: string; metadata: ResourceMetadata } {
  const source = strictRecord(
    value,
    ["apiVersion", "kind", "metadata", "spec"],
    ["apiVersion", "kind", "metadata", "spec"],
  );
  if (source.apiVersion !== platformApiVersion || source.kind !== kind)
    error("RESOURCE_KIND_MISMATCH", "/kind");
  return { apiVersion: platformApiVersion, kind, metadata: metadata(source.metadata) };
}
function scope(value: unknown, path = "/scope"): AuthorizationScope {
  const source = strictRecord(value, ["level", "ref"], ["level"], path);
  const level = enumValue(
    source.level,
    ["platform", "tenant", "organization", "project"] as const,
    `${path}/level`,
  );
  if (level === "platform") {
    if (source.ref !== undefined) error("SCOPE_KIND_MISMATCH", `${path}/ref`);
    return { level };
  }
  const expected = level === "tenant" ? "tenant" : level;
  if (source.ref === undefined) error("MISSING_FIELD", `${path}/ref`);
  return { level, ref: namespace(source.ref, expected, `${path}/ref`) };
}
function subject(value: unknown, path = "/subject"): SubjectRef {
  const source = strictRecord(
    value,
    ["kind", "issuer", "subject"],
    ["kind", "issuer", "subject"],
    path,
  );
  const result = {
    kind: string(source.kind, `${path}/kind`),
    issuer: string(source.issuer, `${path}/issuer`),
    subject: string(source.subject, `${path}/subject`),
  };
  validateSubjectRef(result as SubjectRef);
  return Object.freeze(result) as SubjectRef;
}

export function decodeProjectCreateRequest(value: unknown): ProjectCreateRequest {
  const source = strictRecord(
    value,
    ["name", "organizationRef", "displayName"],
    ["name", "organizationRef", "displayName"],
  );
  const organizationRef = namespace(source.organizationRef, "organization", "/organizationRef");
  identifier(organizationRef.id, "/organizationRef/id");
  return Object.freeze({
    name: identifier(source.name, "/name"),
    organizationRef,
    displayName: boundedString(source.displayName, 1, 160, "/displayName"),
  });
}
export function parseProjectCreateRequest(text: string): ProjectCreateRequest {
  return decodeProjectCreateRequest(parseStrictJSON(text));
}
export function encodeProjectCreateRequest(value: ProjectCreateRequest): string {
  const checked = decodeProjectCreateRequest(value);
  return JSON.stringify(checked);
}

export function decodePlatformTenant(value: unknown): PlatformTenant {
  const source = record(value);
  const root = base(source, "PlatformTenant");
  const spec = strictRecord(
    source.spec,
    ["displayName", "state"],
    ["displayName", "state"],
    "/spec",
  );
  if (
    root.metadata.uid !== root.metadata.tenantRef.id ||
    root.metadata.name !== root.metadata.tenantRef.id
  )
    error("TENANT_AUTHORITY_MISMATCH", "/metadata");
  return Object.freeze({
    ...root,
    kind: "PlatformTenant",
    spec: Object.freeze({
      displayName: boundedString(spec.displayName, 1, 160, "/spec/displayName"),
      state: enumValue(spec.state, ["active", "suspended"] as const, "/spec/state"),
    }),
  });
}
export function decodeOrganization(value: unknown): Organization {
  const source = record(value);
  const root = base(source, "Organization");
  const spec = strictRecord(
    source.spec,
    ["tenantRef", "displayName", "state"],
    ["tenantRef", "displayName", "state"],
    "/spec",
  );
  const tenantRef = namespace(spec.tenantRef, "tenant", "/spec/tenantRef");
  if (tenantRef.id !== root.metadata.tenantRef.id)
    error("TENANT_AUTHORITY_MISMATCH", "/spec/tenantRef");
  return Object.freeze({
    ...root,
    kind: "Organization",
    spec: Object.freeze({
      tenantRef,
      displayName: boundedString(spec.displayName, 1, 160, "/spec/displayName"),
      state: enumValue(spec.state, ["active", "suspended"] as const, "/spec/state"),
    }),
  });
}
export function decodeProject(value: unknown): Project {
  const source = record(value);
  const root = base(source, "Project");
  const spec = strictRecord(
    source.spec,
    ["tenantRef", "organizationRef", "displayName", "state"],
    ["tenantRef", "organizationRef", "displayName", "state"],
    "/spec",
  );
  const tenantRef = namespace(spec.tenantRef, "tenant", "/spec/tenantRef");
  if (tenantRef.id !== root.metadata.tenantRef.id)
    error("TENANT_AUTHORITY_MISMATCH", "/spec/tenantRef");
  return Object.freeze({
    ...root,
    kind: "Project",
    spec: Object.freeze({
      tenantRef,
      organizationRef: namespace(spec.organizationRef, "organization", "/spec/organizationRef"),
      displayName: boundedString(spec.displayName, 1, 160, "/spec/displayName"),
      state: enumValue(spec.state, ["active", "suspended", "archived"] as const, "/spec/state"),
    }),
  });
}
export function validateProjectResolvedOrganization(
  project: Project,
  organizationTenant: NamespaceRef,
): void {
  if (
    project.spec.tenantRef.id !== organizationTenant.id ||
    project.spec.tenantRef.kind !== organizationTenant.kind
  )
    error("CROSS_TENANT_REFERENCE", "/spec/organizationRef");
}
export function decodeMembership(value: unknown): Membership {
  const source = record(value);
  const root = base(source, "Membership");
  const spec = strictRecord(
    source.spec,
    ["tenantRef", "subject", "scope", "state", "expiresAt"],
    ["tenantRef", "subject", "scope", "state"],
    "/spec",
  );
  const tenantRef = namespace(spec.tenantRef, "tenant", "/spec/tenantRef");
  if (tenantRef.id !== root.metadata.tenantRef.id)
    error("TENANT_AUTHORITY_MISMATCH", "/spec/tenantRef");
  const result: MembershipSpec = {
    tenantRef,
    subject: subject(spec.subject),
    scope: scope(spec.scope),
    state: enumValue(spec.state, ["active", "suspended", "revoked"] as const, "/spec/state"),
  };
  if (spec.expiresAt !== undefined)
    return Object.freeze({
      ...root,
      kind: "Membership",
      spec: Object.freeze({ ...result, expiresAt: dateTime(spec.expiresAt, "/spec/expiresAt") }),
    });
  return Object.freeze({ ...root, kind: "Membership", spec: Object.freeze(result) });
}
export function decodeRole(value: unknown): Role {
  const source = record(value);
  const root = base(source, "Role");
  const spec = strictRecord(
    source.spec,
    ["name", "version", "permissions", "state"],
    ["name", "version", "permissions", "state"],
    "/spec",
  );
  const name = roleNameValue(spec.name, "/spec/name");
  const permissions = Array.isArray(spec.permissions)
    ? spec.permissions.map((permission, index) => {
        const value = string(permission, `/spec/permissions/${index}`);
        if (value.includes("*"))
          error("WILDCARD_PERMISSION_FORBIDDEN", `/spec/permissions/${index}`);
        if (!permissionPattern.test(value) || value.length < 5 || value.length > 128)
          error("INVALID_PERMISSION", `/spec/permissions/${index}`);
        return value;
      })
    : error("INVALID_PERMISSIONS", "/spec/permissions");
  if (
    new Set(permissions).size !== permissions.length ||
    permissions.length < 1 ||
    permissions.length > 256
  )
    error("INVALID_PERMISSIONS", "/spec/permissions");
  return Object.freeze({
    ...root,
    kind: "Role",
    spec: Object.freeze({
      name,
      version: integer(spec.version, 1, Number.MAX_SAFE_INTEGER, "/spec/version"),
      permissions: Object.freeze(permissions),
      state: enumValue(spec.state, ["active", "deprecated", "revoked"] as const, "/spec/state"),
    }),
  });
}
export function decodeRoleBinding(value: unknown): RoleBinding {
  const source = record(value);
  const root = base(source, "RoleBinding");
  const spec = strictRecord(
    source.spec,
    ["tenantRef", "subject", "roleName", "roleVersion", "scope", "state", "expiresAt"],
    ["tenantRef", "subject", "roleName", "roleVersion", "scope", "state"],
    "/spec",
  );
  const tenantRef = namespace(spec.tenantRef, "tenant", "/spec/tenantRef");
  if (tenantRef.id !== root.metadata.tenantRef.id)
    error("TENANT_AUTHORITY_MISMATCH", "/spec/tenantRef");
  const roleName = roleNameValue(spec.roleName, "/spec/roleName");
  const expected =
    roleName === "platform.admin"
      ? "platform"
      : roleName === "tenant.admin"
        ? "tenant"
        : roleName === "organization.admin"
          ? "organization"
          : "project";
  const roleScope = scope(spec.scope);
  if (roleScope.level !== expected) error("ROLE_SCOPE_MISMATCH", "/spec/scope/level");
  const result: RoleBindingSpec = {
    tenantRef,
    subject: subject(spec.subject),
    roleName,
    roleVersion: integer(spec.roleVersion, 1, Number.MAX_SAFE_INTEGER, "/spec/roleVersion"),
    scope: roleScope,
    state: enumValue(spec.state, ["active", "revoked"] as const, "/spec/state"),
  };
  if (spec.expiresAt !== undefined)
    return Object.freeze({
      ...root,
      kind: "RoleBinding",
      spec: Object.freeze({ ...result, expiresAt: dateTime(spec.expiresAt, "/spec/expiresAt") }),
    });
  return Object.freeze({ ...root, kind: "RoleBinding", spec: Object.freeze(result) });
}

export function parsePlatformTenant(text: string): ResponseEnvelope<PlatformTenant> {
  return parseResponse(text, tenantResponseShape, decodePlatformTenant);
}
export function parseOrganization(text: string): ResponseEnvelope<Organization> {
  return parseResponse(text, organizationResponseShape, decodeOrganization);
}
export function parseProject(text: string): ResponseEnvelope<Project> {
  return parseResponse(text, projectResponseShape, decodeProject);
}
export function parseMembership(text: string): ResponseEnvelope<Membership> {
  return parseResponse(text, membershipResponseShape, decodeMembership);
}
export function parseRole(text: string): ResponseEnvelope<Role> {
  return parseResponse(text, roleResponseShape, decodeRole);
}
export function parseRoleBinding(text: string): ResponseEnvelope<RoleBinding> {
  return parseResponse(text, roleBindingResponseShape, decodeRoleBinding);
}
function parseResponse<T>(
  text: string,
  shape: ResponseShape,
  decode: (value: unknown) => T,
): ResponseEnvelope<T> {
  const value = parseStrictJSON(text);
  const unknown: Record<string, string> = {};
  const known = stripResponseUnknown(text, value, shape, "", unknown);
  return Object.freeze({ value: decode(known), unknown: Object.freeze(unknown) });
}
export function encodeResponse<T>(envelope: ResponseEnvelope<T>): string {
  const entries = Object.entries(envelope.unknown)
    .map(([pointer, raw]) => ({ pointer, raw, segments: splitJSONPointer(pointer) }))
    .toSorted((left, right) =>
      left.pointer < right.pointer ? -1 : left.pointer > right.pointer ? 1 : 0,
    );
  for (let index = 0; index < entries.length; index++) {
    parseStrictJSON(entries[index]!.raw);
    for (let previous = 0; previous < index; previous++)
      if (
        jsonPointerPrefix(entries[previous]!.segments, entries[index]!.segments) ||
        jsonPointerPrefix(entries[index]!.segments, entries[previous]!.segments)
      )
        error("SIDECAR_POINTER_OVERLAP", entries[index]!.pointer);
  }
  let encoded = JSON.stringify(envelope.value);
  for (const entry of entries)
    encoded = mergeSidecarRaw(encoded, entry.segments, entry.raw, entry.pointer);
  return encoded;
}

export function parseProblem(text: string): Problem {
  const source = strictRecord(
    parseStrictJSON(text),
    ["type", "title", "status", "error", "requestId"],
    ["type", "title", "status", "error", "requestId"],
  );
  const stable = strictRecord(
    source.error,
    ["code", "retryable", "retryAfterSeconds"],
    ["code", "retryable"],
    "/error",
  );
  const code = boundedString(stable.code, 3, 96, "/error/code");
  if (!/^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$/u.test(code))
    error("INVALID_STABLE_ERROR_CODE", "/error/code");
  if (typeof stable.retryable !== "boolean") error("INVALID_FIELD_TYPE", "/error/retryable");
  const retryable = stable.retryable as boolean;
  const base = {
    type: absoluteURI(source.type, "/type"),
    title: boundedString(source.title, 1, 160, "/title"),
    status: integer(source.status, 400, 599, "/status"),
    error: { code, retryable },
    requestId: identifier(source.requestId, "/requestId"),
  };
  if (stable.retryAfterSeconds !== undefined)
    return Object.freeze({
      ...base,
      error: Object.freeze({
        ...base.error,
        retryAfterSeconds: integer(stable.retryAfterSeconds, 0, 86400, "/error/retryAfterSeconds"),
      }),
    });
  return Object.freeze({ ...base, error: Object.freeze(base.error) });
}
export function decodePagination(value: unknown): Pagination {
  const source = strictRecord(value, ["pageSize", "pageToken"], ["pageSize"]);
  const base = { pageSize: integer(source.pageSize, 1, 200, "/pageSize") };
  if (source.pageToken === undefined) return base;
  return Object.freeze({ ...base, pageToken: token(source.pageToken, "/pageToken") });
}
export function decodeWatchCursor(value: unknown): WatchCursor {
  const source = strictRecord(
    value,
    ["cursor", "resourceVersion", "expiresAt"],
    ["cursor", "resourceVersion", "expiresAt"],
  );
  const resourceVersion = string(source.resourceVersion, "/resourceVersion");
  if (!/^(?:0|[1-9][0-9]*)$/u.test(resourceVersion) || resourceVersion.length > 20)
    error("INVALID_RESOURCE_VERSION", "/resourceVersion");
  return Object.freeze({
    cursor: token(source.cursor, "/cursor"),
    resourceVersion,
    expiresAt: dateTime(source.expiresAt, "/expiresAt"),
  });
}
export function parseWatchCursor(text: string): ResponseEnvelope<WatchCursor> {
  const value = parseStrictJSON(text);
  const unknown: Record<string, string> = {};
  const known = stripResponseUnknown(text, value, watchCursorResponseShape, "", unknown);
  return Object.freeze({ value: decodeWatchCursor(known), unknown: Object.freeze(unknown) });
}
export function decodeIdempotency(value: unknown): Idempotency {
  const source = strictRecord(value, ["key", "requestDigest"], ["key", "requestDigest"]);
  const key = string(source.key, "/key");
  if (!/^[A-Za-z0-9._~-]{16,128}$/u.test(key)) error("INVALID_IDEMPOTENCY_KEY", "/key");
  const requestDigest = string(source.requestDigest, "/requestDigest");
  if (!/^sha256:[0-9a-f]{64}$/u.test(requestDigest))
    error("INVALID_REQUEST_DIGEST", "/requestDigest");
  return Object.freeze({ key, requestDigest: requestDigest as `sha256:${string}` });
}
function token(value: unknown, path: string): string {
  const text = string(value, path);
  if (text.length < 16 || text.length > 2048 || !/^[A-Za-z0-9_-]+$/u.test(text))
    error("INVALID_TOKEN", path);
  return text;
}

export type FixtureRequest = Readonly<{
  method: "GET" | "POST";
  path: string;
  headers: Readonly<Record<string, string>>;
  body?: string;
}>;
export type FixtureResponse = Readonly<{
  status: number;
  headers: Readonly<Record<string, string>>;
  body: string;
}>;
export type FixtureTransport = (
  request: FixtureRequest,
  signal: AbortSignal,
) => Promise<FixtureResponse>;
export class ClientError extends Error {
  constructor(
    readonly operation: string,
    readonly status: number,
    readonly problem?: unknown,
    cause?: unknown,
  ) {
    super(
      `${operation}: ${typeof problem === "object" && problem !== null && "error" in problem ? String((problem as { error?: { code?: unknown } }).error?.code) : cause instanceof Error ? cause.message : `HTTP ${status}`}`,
      { cause },
    );
    this.name = "ClientError";
  }
}
export class Client {
  constructor(private readonly transport: FixtureTransport) {
    if (typeof transport !== "function") throw new TypeError("fixture transport is required");
  }
  async createProject(
    tenantId: string,
    requestId: string,
    idempotencyKey: string,
    body: ProjectCreateRequest,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<Project>> {
    validatePath(tenantId, requestId);
    if (!/^[A-Za-z0-9._~-]{16,128}$/u.test(idempotencyKey))
      error("INVALID_IDEMPOTENCY_KEY", "/Idempotency-Key");
    const response = await this.call(
      {
        method: "POST",
        path: `/v1/tenants/${tenantId}/projects`,
        headers: { "X-Request-ID": requestId, "Idempotency-Key": idempotencyKey },
        body: encodeProjectCreateRequest(body),
      },
      signal,
    );
    if (response.status !== 201) throw await this.problem("managedAgentCreateProject", response);
    const result = parseProject(response.body);
    requireVersion(response, result.value.metadata.resourceVersion);
    if (result.value.metadata.tenantRef.id !== tenantId || result.value.metadata.name !== body.name)
      error("PATH_BODY_AUTHORITY_MISMATCH", "/metadata");
    return result;
  }
  async getProject(
    tenantId: string,
    projectId: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<Project>> {
    return this.get(
      `/v1/tenants/${tenantId}/projects/${projectId}`,
      tenantId,
      projectId,
      requestId,
      "managedAgentGetProject",
      parseProject,
      signal,
    );
  }
  async getOrganization(
    tenantId: string,
    organizationId: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<Organization>> {
    return this.get(
      `/v1/tenants/${tenantId}/organizations/${organizationId}`,
      tenantId,
      organizationId,
      requestId,
      "managedAgentGetOrganization",
      parseOrganization,
      signal,
    );
  }
  async getPlatformTenant(
    tenantId: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<PlatformTenant>> {
    return this.get(
      `/v1/tenants/${tenantId}`,
      tenantId,
      tenantId,
      requestId,
      "managedAgentGetPlatformTenant",
      parsePlatformTenant,
      signal,
    );
  }
  async getMembership(
    tenantId: string,
    id: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<Membership>> {
    return this.get(
      `/v1/tenants/${tenantId}/memberships/${id}`,
      tenantId,
      id,
      requestId,
      "managedAgentGetMembership",
      parseMembership,
      signal,
    );
  }
  async getRole(
    tenantId: string,
    id: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<Role>> {
    return this.get(
      `/v1/tenants/${tenantId}/roles/${id}`,
      tenantId,
      id,
      requestId,
      "managedAgentGetRole",
      parseRole,
      signal,
    );
  }
  async getRoleBinding(
    tenantId: string,
    id: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<RoleBinding>> {
    return this.get(
      `/v1/tenants/${tenantId}/role-bindings/${id}`,
      tenantId,
      id,
      requestId,
      "managedAgentGetRoleBinding",
      parseRoleBinding,
      signal,
    );
  }
  async getProjectContext(
    tenantId: string,
    id: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<Project>> {
    return this.get(
      `/v1/managed-host/tenants/${tenantId}/projects/${id}`,
      tenantId,
      id,
      requestId,
      "managedHostGetProjectContext",
      parseProject,
      signal,
    );
  }
  async getManagedHostRoleBinding(
    tenantId: string,
    id: string,
    requestId: string,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<RoleBinding>> {
    return this.get(
      `/v1/managed-host/tenants/${tenantId}/role-bindings/${id}`,
      tenantId,
      id,
      requestId,
      "managedHostGetRoleBinding",
      parseRoleBinding,
      signal,
    );
  }
  private async get<T>(
    path: string,
    tenantId: string,
    id: string,
    requestId: string,
    operation: string,
    decode: (text: string) => ResponseEnvelope<T>,
    signal?: AbortSignal,
  ): Promise<ResponseEnvelope<T>> {
    validatePath(tenantId, requestId);
    identifier(id, "/resourceId");
    const response = await this.call(
      { method: "GET", path, headers: { "X-Request-ID": requestId } },
      signal,
    );
    if (response.status !== 200) throw await this.problem(operation, response);
    const result = decode(response.body);
    requireVersion(response, resourceMetadata(result.value).resourceVersion);
    if (
      resourceMetadata(result.value).tenantRef.id !== tenantId ||
      resourceMetadata(result.value).name !== id
    )
      error("PATH_BODY_AUTHORITY_MISMATCH", "/metadata");
    return result;
  }
  private async call(request: FixtureRequest, signal?: AbortSignal): Promise<FixtureResponse> {
    const controller = new AbortController();
    if (signal?.aborted) throw signal.reason ?? new DOMException("Aborted", "AbortError");
    if (signal === undefined) return this.transport(request, controller.signal);
    return new Promise<FixtureResponse>((resolve, reject) => {
      let settled = false;
      const cleanup = () => signal.removeEventListener("abort", onAbort);
      const onAbort = () => {
        if (settled) return;
        settled = true;
        controller.abort(signal.reason);
        cleanup();
        reject(signal.reason ?? new DOMException("Aborted", "AbortError"));
      };
      signal.addEventListener("abort", onAbort, { once: true });
      this.transport(request, controller.signal).then(
        (response) => {
          if (settled) return;
          settled = true;
          cleanup();
          resolve(response);
        },
        (cause: unknown) => {
          if (settled) return;
          settled = true;
          cleanup();
          reject(
            signal.aborted ? (signal.reason ?? new DOMException("Aborted", "AbortError")) : cause,
          );
        },
      );
    });
  }
  private async problem(operation: string, response: FixtureResponse): Promise<ClientError> {
    let problem: Problem;
    try {
      problem = parseProblem(response.body);
    } catch {
      return new ClientError(operation, response.status);
    }
    if (problem.status !== response.status)
      return new ClientError(
        operation,
        response.status,
        undefined,
        new JSONContractError("PROBLEM_STATUS_MISMATCH", "/status"),
      );
    return new ClientError(operation, response.status, problem);
  }
}
function validatePath(tenantId: string, requestId: string): void {
  identifier(tenantId, "/tenantId");
  identifier(requestId, "/Request-ID");
}
function resourceMetadata(value: unknown): ResourceMetadata {
  return (value as { metadata: ResourceMetadata }).metadata;
}
function requireVersion(response: FixtureResponse, version: string): void {
  if (response.headers["X-Resource-Version"] !== version)
    error("RESOURCE_VERSION_MISMATCH", "/X-Resource-Version");
}

function parseStrictJSON(text: string): unknown {
  if (typeof text !== "string") error("INVALID_JSON", "");
  assertNoDuplicateKeys(text);
  try {
    const value = JSON.parse(text) as unknown;
    assertTree(value, "");
    return value;
  } catch (cause) {
    if (cause instanceof JSONContractError) throw cause;
    error("INVALID_JSON", "");
  }
}
type RawJSONNode = Readonly<{
  raw: string;
  value: unknown;
  object?: ReadonlyMap<string, RawJSONNode>;
  array?: readonly RawJSONNode[];
}>;
function stripResponseUnknown(
  text: string,
  value: unknown,
  shape: ResponseShape,
  path: string,
  sidecar: Record<string, string>,
): unknown {
  const node = parseRawJSON(text);
  return stripRawNode(node, value, shape, path, sidecar);
}
function stripRawNode(
  node: RawJSONNode,
  value: unknown,
  shape: ResponseShape,
  path: string,
  sidecar: Record<string, string>,
): unknown {
  if (shape.fields !== undefined) {
    const object = node.object;
    if (object === undefined || typeof value !== "object" || value === null || Array.isArray(value))
      return error("INVALID_JSON_OBJECT", path);
    const known: Record<string, unknown> = {};
    for (const [key, child] of object) {
      const childShape = shape.fields[key];
      const childPath = appendJSONPointer(path, key);
      if (childShape === undefined) sidecar[childPath] = child.raw;
      else
        known[key] = stripRawNode(
          child,
          (value as Record<string, unknown>)[key],
          childShape,
          childPath,
          sidecar,
        );
    }
    return known;
  }
  if (shape.item !== undefined) {
    const array = node.array;
    if (array === undefined || !Array.isArray(value)) return error("INVALID_JSON_ARRAY", path);
    return array.map((child, index) =>
      stripRawNode(
        child,
        (value as readonly unknown[])[index],
        shape.item!,
        appendJSONPointer(path, String(index)),
        sidecar,
      ),
    );
  }
  return value;
}
function parseRawJSON(text: string): RawJSONNode {
  let index = 0;
  const whitespace = () => {
    while (/\s/u.test(text[index] ?? "")) index++;
  };
  const stringToken = (): string => {
    const start = index;
    if (text[index] !== '"') return error("INVALID_JSON", "");
    index++;
    while (index < text.length) {
      const current = text[index++]!;
      if (current === "\\") {
        if (index >= text.length) return error("INVALID_JSON", "");
        index++;
        continue;
      }
      if (current === '"') {
        try {
          return JSON.parse(text.slice(start, index)) as string;
        } catch {
          return error("INVALID_JSON", "");
        }
      }
      if (current.charCodeAt(0) < 0x20) return error("INVALID_JSON", "");
    }
    return error("INVALID_JSON", "");
  };
  const parseValue = (): RawJSONNode => {
    whitespace();
    const start = index;
    if (text[index] === "{") {
      index++;
      const object = new Map<string, RawJSONNode>();
      whitespace();
      if (text[index] === "}") {
        index++;
        return { raw: text.slice(start, index), value: {}, object };
      }
      while (true) {
        whitespace();
        const key = stringToken();
        whitespace();
        if (text[index++] !== ":") return error("INVALID_JSON", "");
        const child = parseValue();
        object.set(key, child);
        whitespace();
        if (text[index] === "}") {
          index++;
          break;
        }
        if (text[index++] !== ",") return error("INVALID_JSON", "");
      }
      return {
        raw: text.slice(start, index),
        value: Object.fromEntries([...object].map(([key, child]) => [key, child.value])),
        object,
      };
    }
    if (text[index] === "[") {
      index++;
      const array: RawJSONNode[] = [];
      whitespace();
      if (text[index] === "]") {
        index++;
        return { raw: text.slice(start, index), value: [], array };
      }
      while (true) {
        array.push(parseValue());
        whitespace();
        if (text[index] === "]") {
          index++;
          break;
        }
        if (text[index++] !== ",") return error("INVALID_JSON", "");
      }
      return { raw: text.slice(start, index), value: array.map((child) => child.value), array };
    }
    if (text[index] === '"') {
      stringToken();
      return {
        raw: text.slice(start, index),
        value: JSON.parse(text.slice(start, index)) as string,
      };
    }
    const tokenStart = index;
    while (index < text.length && !/[\s,\]}]/u.test(text[index]!)) index++;
    if (tokenStart === index) return error("INVALID_JSON", "");
    const raw = text.slice(start, index);
    try {
      return { raw, value: JSON.parse(raw) as unknown };
    } catch {
      return error("INVALID_JSON", "");
    }
  };
  const node = parseValue();
  whitespace();
  if (index !== text.length) error("TRAILING_JSON", "");
  return node;
}
function mergeSidecarRaw(
  current: string,
  segments: readonly string[],
  raw: string,
  pointer: string,
): string {
  if (segments.length === 0) error("INVALID_SIDECAR_POINTER", pointer);
  const node = parseRawJSON(current);
  return mergeRawNode(node, segments, raw, pointer);
}
function mergeRawNode(
  node: RawJSONNode,
  segments: readonly string[],
  raw: string,
  pointer: string,
): string {
  const [head, ...tail] = segments;
  if (node.object !== undefined) {
    const entries = [...node.object];
    const position = entries.findIndex(([key]) => key === head);
    if (tail.length === 0) {
      if (position >= 0) error("SIDECAR_FIELD_COLLISION", pointer);
      entries.push([head!, parseRawJSON(raw)]);
    } else {
      if (position < 0) error("INVALID_SIDECAR_POINTER", pointer);
      entries[position] = [
        head!,
        parseRawJSON(mergeRawNode(entries[position]![1], tail, raw, pointer)),
      ];
    }
    return `{${entries.map(([key, child]) => `${JSON.stringify(key)}:${child.raw}`).join(",")}}`;
  }
  if (node.array !== undefined) {
    const numeric = Number(head);
    if (
      !Number.isInteger(numeric) ||
      String(numeric) !== head ||
      numeric < 0 ||
      numeric >= node.array.length ||
      tail.length === 0
    )
      error(tail.length === 0 ? "SIDECAR_FIELD_COLLISION" : "INVALID_SIDECAR_POINTER", pointer);
    const items = [...node.array];
    items[numeric] = parseRawJSON(mergeRawNode(items[numeric]!, tail, raw, pointer));
    return `[${items.map((item) => item.raw).join(",")}]`;
  }
  return error("INVALID_SIDECAR_POINTER", pointer);
}
function appendJSONPointer(path: string, token: string): string {
  return `${path}/${token.replaceAll("~", "~0").replaceAll("/", "~1")}`;
}
function splitJSONPointer(pointer: string): string[] {
  if (!pointer.startsWith("/")) error("INVALID_SIDECAR_POINTER", pointer);
  return pointer
    .slice(1)
    .split("/")
    .map((token) => {
      let result = "";
      for (let index = 0; index < token.length; index++) {
        if (token[index] !== "~") {
          result += token[index];
          continue;
        }
        const next = token[++index];
        if (next !== "0" && next !== "1") error("INVALID_SIDECAR_POINTER", pointer);
        result += next === "0" ? "~" : "/";
      }
      return result;
    });
}
function jsonPointerPrefix(left: readonly string[], right: readonly string[]): boolean {
  return left.length < right.length && left.every((segment, index) => segment === right[index]);
}
function assertTree(value: unknown, path: string): void {
  if (typeof value === "string") {
    assertScalar(value, path);
    return;
  }
  if (Array.isArray(value)) {
    value.forEach((item, index) => assertTree(item, `${path}/${index}`));
    return;
  }
  if (typeof value === "object" && value !== null) {
    for (const [key, item] of Object.entries(value)) assertTree(item, `${path}/${key}`);
  }
}
function assertNoDuplicateKeys(text: string): void {
  let index = 0;
  const whitespace = () => {
    while (/\s/u.test(text[index] ?? "")) index++;
  };
  const stringToken = () => {
    if (text[index] !== '"') error("INVALID_JSON", "");
    index++;
    let escaped = false;
    while (index < text.length) {
      const current = text[index++]!;
      if (escaped) {
        escaped = false;
        continue;
      }
      if (current === "\\") {
        escaped = true;
        continue;
      }
      if (current === '"') return;
    }
    error("INVALID_JSON", "");
  };
  const value = (): void => {
    whitespace();
    if (text[index] === "{") {
      index++;
      whitespace();
      const keys = new Set<string>();
      if (text[index] === "}") {
        index++;
        return;
      }
      while (true) {
        whitespace();
        const start = index;
        stringToken();
        let key = "";
        try {
          key = JSON.parse(text.slice(start, index)) as string;
        } catch {
          error("INVALID_JSON", "");
        }
        if (keys.has(key)) error("DUPLICATE_FIELD", `/${key}`);
        keys.add(key);
        whitespace();
        if (text[index++] !== ":") error("INVALID_JSON", "");
        value();
        whitespace();
        if (text[index] === "}") {
          index++;
          return;
        }
        if (text[index++] !== ",") error("INVALID_JSON", "");
      }
    }
    if (text[index] === "[") {
      index++;
      whitespace();
      if (text[index] === "]") {
        index++;
        return;
      }
      while (true) {
        value();
        whitespace();
        if (text[index] === "]") {
          index++;
          return;
        }
        if (text[index++] !== ",") error("INVALID_JSON", "");
      }
    }
    if (text[index] === '"') {
      stringToken();
      return;
    }
    const end = /[\s,\]}]/u;
    while (index < text.length && !end.test(text[index]!)) index++;
  };
  value();
  whitespace();
  if (index !== text.length) error("TRAILING_JSON", "");
}
