import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { DURABLE_COORDINATION_V2_OUTPUT_PATH } from "./platform-durable-coordination-registry";

export const DURABLE_COORDINATION_V2_GO_OUTPUT_PATH =
  "services/control-plane/internal/coordination/registry_v2_generated.go";

type Registry = {
  registryDigest: string;
  stateMachineDigest: string;
  policyDigest: string;
  profiles: Array<{ profileDigest: string; spec: any }>;
};

const goString = (value: string): string => JSON.stringify(value);

export function buildDurableCoordinationGoV2(root: string): string {
  const registry = JSON.parse(
    readFileSync(resolve(root, DURABLE_COORDINATION_V2_OUTPUT_PATH), "utf8"),
  ) as Registry;
  if (registry.profiles.length !== 1) {
    throw new Error("durable project v2 registry must contain one profile");
  }
  const { profileDigest, spec } = registry.profiles[0]!;
  if (spec.profileId !== "managedAgentCreateProjectDurable/v1alpha1") {
    throw new Error("unexpected v2 profile");
  }
  return `// Code generated by scripts/generate-platform-durable-coordination-go-v2.ts; DO NOT EDIT.

package coordination

const (
\tDurableProjectCreateRegistryDigest     = ${goString(registry.registryDigest)}
\tDurableProjectCreateStateMachineDigest = ${goString(registry.stateMachineDigest)}
\tDurableProjectCreatePolicyDigest       = ${goString(registry.policyDigest)}
)

var managedAgentCreateProjectDurableProfile = operationProfile{
\tprofileID:                 ${goString(spec.profileId)},
\tprofileDigest:             ${goString(profileDigest)},
\toperationID:               ${goString(spec.operationId)},
\tprojectionSchemaID:        ${goString(spec.projection.schemaId)},
\tcanonicalizationProfile:   ${goString(spec.projection.canonicalizationProfile)},
\tcanonicalizationAlgorithm: ${goString(spec.projection.canonicalizationAlgorithm)},
\tdigestAlgorithm:           ${goString(spec.projection.digestAlgorithm)},
\ttenantSource:              ${goString(spec.authorization.tenantSource)},
\tscopeSource:               ${goString(spec.authorization.scopeSource)},
\tscopeIdentitySchemaID:     ${goString(spec.authorization.scopeIdentity.schemaId)},
\tscopeIdentifierProfile:    ${goString(spec.authorization.scopeIdentity.identifierProfile)},
\tscopeIdentityComparison:   ${goString(spec.authorization.scopeIdentity.comparison)},
\trequiredPermission:        ${goString(spec.authorization.requiredPermission)},
\trequiredScopeLevel:        "organization",
\toutboxEventClass:          ${goString(spec.coordination.outboxEventClass)},
\tresultResourceKind:        ${goString(spec.result.resourceKind)},
\treplayTTLSeconds:          ${spec.idempotency.replayTtlSeconds},
\tcreatesPlatformOperation:  ${String(spec.coordination.createsPlatformOperation)},
\texternalSideEffectAllowed: false,
}
`;
}

export function assertDurableCoordinationGoV2Current(root: string): void {
  const actual = readFileSync(resolve(root, DURABLE_COORDINATION_V2_GO_OUTPUT_PATH), "utf8");
  const expected = buildDurableCoordinationGoV2(root);
  if (actual !== expected) {
    throw new Error(`${DURABLE_COORDINATION_V2_GO_OUTPUT_PATH} is stale.`);
  }
}
