import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, test } from "bun:test";

import {
  buildRunnerLedgerConsumerRegistry,
  RUNNER_LEDGER_CONSUMER_OUTPUT_PATH,
} from "./platform-runner-ledger-consumer-registry";
import {
  assertRunnerLedgerEntryAdmissionRegistryCurrent,
  buildRunnerLedgerEntryAdmissionRegistry,
  RUNNER_LEDGER_ENTRY_ADMISSION_OUTPUT_PATH,
  RUNNER_LEDGER_ENTRY_ADMISSION_SOURCE_PATH,
  RUNNER_LEDGER_ENTRY_ADMISSION_TRANSITION_MATRIX,
  validateRunnerLedgerEntryAdmissionFixture,
} from "./platform-runner-ledger-entry-admission-registry";

const root = resolve(import.meta.dirname, "../..");

function readJson(path: string): Record<string, any> {
  return JSON.parse(readFileSync(resolve(root, path), "utf8")) as Record<string, any>;
}

function fileSha256(path: string): string {
  return createHash("sha256")
    .update(readFileSync(resolve(root, path)))
    .digest("hex");
}

describe("runner ledger entry-admission generated registry", () => {
  test("is current and binds the exact immutable consumer-v1 identity", () => {
    expect(() => assertRunnerLedgerEntryAdmissionRegistryCurrent(root)).not.toThrow();
    const registry = buildRunnerLedgerEntryAdmissionRegistry(root) as Record<string, any>;
    const consumer = buildRunnerLedgerConsumerRegistry(root) as Record<string, any>;
    expect(registry.consumerBinding).toEqual({
      registryId: consumer.registryId,
      registryDigest: consumer.registryDigest,
      stateMachineDigest: consumer.stateMachineDigest,
      policyDigest: consumer.policyDigest,
      profileId: consumer.profile.spec.profileId,
      profileDigest: consumer.profile.profileDigest,
    });
    expect(registry.profile.spec.transitionMatrix).toEqual(
      RUNNER_LEDGER_ENTRY_ADMISSION_TRANSITION_MATRIX,
    );
    expect(readJson(RUNNER_LEDGER_ENTRY_ADMISSION_OUTPUT_PATH)).toEqual(registry);
  });

  test("preserves preflight-v1 and consumer-v1 generated bytes", () => {
    expect(
      fileSha256("contracts/generated/platform/v1alpha1/runner-ledger-preflight-registry-v1.json"),
    ).toBe("2a04f67f9b06f25bc13211934d8cb914dcbe3f92d42053f636ec66b4f28ac11c");
    expect(fileSha256(RUNNER_LEDGER_CONSUMER_OUTPUT_PATH)).toBe(
      "fa7082803ea97d06eefa83eec3de784f7199fc0b47f0ca2d0f8203b8b7e96852",
    );
    expect(
      fileSha256(
        "services/control-plane/internal/migration/runner_ledger_preflight_profile_generated.go",
      ),
    ).toBe("599b78537a3f1dd5d70c1b50aa5e7bc54e1b65ee463876ee3f111709a5ab2112");
    expect(
      fileSha256(
        "services/control-plane/internal/migration/runner_ledger_consumer_profile_generated.go",
      ),
    ).toBe("afc77e723b7a4439c47043376cb79f5cb6416ce22d54ab1dcffbfe49686ce928");
  });

  test("admits exactly the five immutable entry pairs", () => {
    const matrix = RUNNER_LEDGER_ENTRY_ADMISSION_TRANSITION_MATRIX;
    expect(Object.keys(matrix)).toEqual(["empty_brand_new", "partial_next_entry"]);
    const pairs = Object.values(matrix).flat();
    expect(pairs).toHaveLength(5);
    expect(pairs.every((pair) => pair.admissionAction === "prepare_entry_admission")).toBeTrue();
    const consumer = buildRunnerLedgerConsumerRegistry(root) as Record<string, any>;
    const expected = Object.entries(consumer.profile.spec.transitionMatrix).flatMap(
      ([disposition, values]) =>
        (values as Array<Record<string, string>>)
          .filter((pair) => pair.consumerAction === "entry_not_implemented")
          .map((pair) => ({ disposition, state: pair.state, action: pair.action })),
    );
    const actual = Object.entries(matrix).flatMap(([disposition, values]) =>
      values.map((pair) => ({ disposition, state: pair.state, action: pair.action })),
    );
    expect(actual).toEqual(expected);
  });

  test("rejects pair, selector, boundary, and state-machine drift", () => {
    const source = readJson(RUNNER_LEDGER_ENTRY_ADMISSION_SOURCE_PATH);
    const cases: Array<[string, (candidate: Record<string, any>) => void, string]> = [
      [
        "pair",
        (candidate) => {
          candidate.profile.transitionMatrix.empty_brand_new[0].admissionAction = "execute_entry";
        },
        "RUNNER_LEDGER_ENTRY_ADMISSION_BINDING_MISMATCH",
      ],
      [
        "selector",
        (candidate) => {
          candidate.selector.ordinaryFactAsPermit = "allowed";
        },
        "RUNNER_LEDGER_ENTRY_ADMISSION_BINDING_MISMATCH",
      ],
      [
        "boundary",
        (candidate) => {
          candidate.implementationBoundary.beginMigration = "allowed";
        },
        "RUNNER_LEDGER_ENTRY_ADMISSION_BOUNDARY_MISMATCH",
      ],
      [
        "state machine",
        (candidate) => {
          candidate.stateMachine.transitions[4].event = "execute_entry";
        },
        "RUNNER_LEDGER_ENTRY_ADMISSION_STATE_MACHINE_INVALID",
      ],
    ];
    for (const [name, mutate, code] of cases) {
      const candidate = structuredClone(source);
      mutate(candidate);
      const result = validateRunnerLedgerEntryAdmissionFixture(candidate, root);
      expect(result.valid, name).toBeFalse();
      if (!result.valid) expect(result.errors[0]?.code, name).toBe(code);
    }
  });

  test("rejects an edited generated registry and never treats ordinary JSON as authority", () => {
    const generated = readJson(RUNNER_LEDGER_ENTRY_ADMISSION_OUTPUT_PATH);
    generated.registryDigest = "sha256:" + "0".repeat(64);
    const result = validateRunnerLedgerEntryAdmissionFixture(generated, root);
    expect(result.valid).toBeFalse();
    if (!result.valid) {
      expect(result.errors).toEqual([
        {
          code: "RUNNER_LEDGER_ENTRY_ADMISSION_REGISTRY_DIGEST_MISMATCH",
          path: "/registryDigest",
        },
      ]);
    }
  });
});
