// Code generated by scripts/generate-worker-supervisor-local-dispatch-profile.ts; DO NOT EDIT.

package supervisor

const (
	WorkerSupervisorLocalDispatchAuthorityID   = "D-054-WORKER-DISPATCH-000001"
	WorkerSupervisorLocalDispatchRevision      = "D-054-WORKER-DISPATCH-000001.r1"
	WorkerSupervisorLocalDispatchDecision      = "D-054-WORKER-DISPATCH-000001.r1"
	WorkerSupervisorLocalDispatchProfileID     = "cloud-agents/worker-supervisor-operation-dispatch/localdev-v1alpha1"
	WorkerSupervisorLocalDispatchProfileDigest = "sha256:4ed83884e50cf2f55e9799a16afe28c97cf5756969ae47cdc082a1987b5ddbc1"
	WorkerSupervisorLocalDispatchSourceDigest  = "sha256:b97cb1e464e1cd01e4a42eae270834b45c8db92deddc964f7652fb68417565fa"

	// Stable aliases used by the Supervisor client.
	LocalDispatchProfileID   string = WorkerSupervisorLocalDispatchProfileID
	LocalDispatchAuthorityID string = WorkerSupervisorLocalDispatchAuthorityID
	LocalDispatchRevision    string = WorkerSupervisorLocalDispatchRevision
)

// LocalDispatchProfile is the generated, immutable binding consumed by the
// process-local dispatch implementation.
type LocalDispatchProfile struct {
	ID                    string
	AuthorityID           string
	Revision              string
	Decision              string
	ProfileDigest         string
	SourceDigest          string
	Mode                  string
	Transport             string
	ExternalSideEffects   bool
	GenericClientDispatch bool
	ParentProfiles        [2]string
	Capabilities          [3]string
	Commands              [2]string
	ProtocolMajor         uint32
	ProtocolMinor         uint32
	MaxWireMessageBytes   uint32
	MaxRepeatedItems      uint32
	MaxStringBytes        uint32
	MaxPayloadBytes       uint32
	MaxDeadlineSeconds    uint32
	MaxIdentifierBytes    uint32
	MaxFencingTokenBytes  uint32
	MaxAdmissionRecords   uint32
	MaxReceiptRecords     uint32
}

func (p LocalDispatchProfile) Valid() bool {
	return p.ID == LocalDispatchProfileID &&
		p.AuthorityID == LocalDispatchAuthorityID &&
		p.Revision == WorkerSupervisorLocalDispatchRevision &&
		p.Decision == WorkerSupervisorLocalDispatchDecision &&
		p.ProfileDigest == WorkerSupervisorLocalDispatchProfileDigest &&
		p.SourceDigest == WorkerSupervisorLocalDispatchSourceDigest &&
		p.Mode == "localdev_only" && p.Transport == "in_process" &&
		!p.ExternalSideEffects && !p.GenericClientDispatch &&
		p.ParentProfiles == [2]string{"cloud-agents/worker-operation-admission/v1alpha1", "cloud-agents/worker-operation-execution/localdev-v1alpha1"} &&
		p.Capabilities == [3]string{"negotiation", "health", "operation_dispatch"} &&
		p.Commands == [2]string{"Probe", "ValidateBinding"} &&
		p.ProtocolMajor == 1 && p.ProtocolMinor == 0 &&
		p.MaxWireMessageBytes == 1048576 && p.MaxRepeatedItems == 64 &&
		p.MaxStringBytes == 1024 && p.MaxPayloadBytes == 65536 &&
		p.MaxDeadlineSeconds == 300 && p.MaxIdentifierBytes == 256 &&
		p.MaxFencingTokenBytes == 65536 && p.MaxAdmissionRecords == 1024 &&
		p.MaxReceiptRecords == 1024
}

var GeneratedLocalDispatchProfile = LocalDispatchProfile{
	ID: LocalDispatchProfileID, AuthorityID: LocalDispatchAuthorityID, Revision: WorkerSupervisorLocalDispatchRevision, Decision: WorkerSupervisorLocalDispatchDecision,
	ProfileDigest: WorkerSupervisorLocalDispatchProfileDigest, SourceDigest: WorkerSupervisorLocalDispatchSourceDigest,
	Mode: "localdev_only", Transport: "in_process", ExternalSideEffects: false, GenericClientDispatch: false,
	ParentProfiles: [2]string{"cloud-agents/worker-operation-admission/v1alpha1", "cloud-agents/worker-operation-execution/localdev-v1alpha1"},
	Capabilities:   [3]string{"negotiation", "health", "operation_dispatch"}, Commands: [2]string{"Probe", "ValidateBinding"},
	ProtocolMajor: 1, ProtocolMinor: 0, MaxWireMessageBytes: 1048576,
	MaxRepeatedItems: 64, MaxStringBytes: 1024, MaxPayloadBytes: 65536,
	MaxDeadlineSeconds: 300, MaxIdentifierBytes: 256, MaxFencingTokenBytes: 65536,
	MaxAdmissionRecords: 1024, MaxReceiptRecords: 1024,
}

func WorkerSupervisorLocalDispatchProfile() LocalDispatchProfile {
	return GeneratedLocalDispatchProfile
}
