import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const mode = process.argv[2];
if (mode !== "--write" && mode !== "--check") throw new Error("use --write or --check");
const output =
  "services/control-plane/migrations/000083_restore_foundation_workspace_snapshots.sql";
const content =
  "-- Generated by scripts/generate-foundation-workspace-restore.ts; DO NOT EDIT.\n" +
  readFileSync(resolve(root, "scripts/templates/foundation-workspace-restore.sql"), "utf8");
if (mode === "--write") writeFileSync(resolve(root, output), content);
else if (readFileSync(resolve(root, output), "utf8") !== content)
  throw new Error(`${output} is stale`);
process.stdout.write(`foundation workspace restore ${mode}\n`);
