import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { canonicalizeMigrationJson, type MigrationJson } from "./lib/platform-migration-json";

const root = resolve(import.meta.dirname, "..");
const mode = process.argv[2];
if (mode !== "--write" && mode !== "--check") throw new Error("use --write or --check");
const profile = JSON.parse(
  readFileSync(
    resolve(root, "contracts/platform/v1alpha1/foundation-workspace-snapshot.json"),
    "utf8",
  ),
);
assert.equal(profile.profileId, "foundationWorkspaceSnapshot/v1alpha1");
assert.equal(profile.outboxEventClass, "operation_effect");
assert.equal(profile.externalSideEffect, "docker_archive_under_durable_claim");
assert.equal(profile.consistencyMode, "offline");
assert.equal(profile.writerFence, "sandbox-single-writer-reservation");
assert.equal(profile.maximumArchiveBytes, 67108864);
assert.deepEqual(profile.requiredFinalizers, ["workspace-snapshot-copy"]);
const hash = (value: MigrationJson) =>
  "sha256:" + createHash("sha256").update(canonicalizeMigrationJson(value)).digest("hex");
const profileDigest = hash(profile);
const registryDigest = hash({ profileId: profile.profileId, profileDigest });
const rows = [
  [
    "sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30",
    "managedAgentCreateProject/v1alpha1",
    "sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a",
    false,
  ],
  [
    "sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a",
    "managedAgentCreateProject/v1alpha1",
    "sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308",
    false,
  ],
  [
    "sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8",
    "managedAgentCreateProjectDurable/v1alpha1",
    "sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f",
    true,
  ],
  [
    "sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c",
    "foundationSandboxLifecycle/v1alpha1",
    "sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b",
    true,
  ],
  [registryDigest, profile.profileId, profileDigest, true],
] as const;
const literal = (value: string | boolean) =>
  typeof value === "boolean" ? String(value) : "'" + value.replaceAll("'", "''") + "'";
const table = `(VALUES ${rows.map((row) => "(" + row.map(literal).join(", ") + ")").join(",\n")}) AS profiles(registry, id, digest, creates_operation)`;
const functions = [
  [
    "coordination_registry_profile_is_registered",
    "p_registry_digest text, p_profile_id text, p_profile_digest text",
    "boolean",
    `SELECT EXISTS (SELECT 1 FROM ${table} WHERE registry = p_registry_digest AND id = p_profile_id AND digest = p_profile_digest)`,
  ],
  [
    "coordination_registry_digest_for_profile",
    "p_profile_id text, p_profile_digest text",
    "text",
    `SELECT registry FROM ${table} WHERE id = p_profile_id AND digest = p_profile_digest`,
  ],
  [
    "coordination_profile_is_registered",
    "p_profile_id text, p_profile_digest text",
    "boolean",
    `SELECT EXISTS (SELECT 1 FROM ${table} WHERE id = p_profile_id AND digest = p_profile_digest)`,
  ],
  [
    "coordination_profile_creates_operation",
    "p_profile_id text, p_profile_digest text",
    "boolean",
    `SELECT EXISTS (SELECT 1 FROM ${table} WHERE id = p_profile_id AND digest = p_profile_digest AND creates_operation)`,
  ],
  [
    "coordination_profile_outbox_class",
    "p_profile_id text, p_profile_digest text",
    "text",
    `SELECT CASE WHEN creates_operation THEN 'operation_effect' ELSE 'resource_change' END FROM ${table} WHERE id = p_profile_id AND digest = p_profile_digest`,
  ],
] as const;
let sql =
  "-- Generated by scripts/generate-foundation-workspace-snapshot.ts; DO NOT EDIT.\n" +
  functions
    .map(
      ([name, args, result, body]) =>
        `CREATE OR REPLACE FUNCTION cloud_agents.${name}(${args})\nRETURNS ${result} LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, cloud_agents\nAS $$ ${body} $$;\n`,
    )
    .join("\n");
sql += readFileSync(resolve(root, "scripts/templates/foundation-workspace-snapshot.sql"), "utf8")
  .replaceAll("@PROFILE_ID@", profile.profileId)
  .replaceAll("@PROFILE_DIGEST@", profileDigest)
  .replaceAll("@REGISTRY_DIGEST@", registryDigest);
const go = `// Code generated by scripts/generate-foundation-workspace-snapshot.ts; DO NOT EDIT.\n\npackage coordination\n\nconst (\n\tWorkspaceSnapshotProfileID = ${JSON.stringify(profile.profileId)}\n\tWorkspaceSnapshotProfileDigest = ${JSON.stringify(profileDigest)}\n\tWorkspaceSnapshotRegistryDigest = ${JSON.stringify(registryDigest)}\n)\n`;
for (const [path, content] of [
  ["services/control-plane/migrations/000082_add_foundation_workspace_snapshots.sql", sql],
  [
    "services/control-plane/internal/coordination/foundation_snapshot_generated.go",
    execFileSync("gofmt", { input: go, encoding: "utf8" }),
  ],
] as const) {
  if (mode === "--write") writeFileSync(resolve(root, path), content);
  else if (readFileSync(resolve(root, path), "utf8") !== content)
    throw new Error(`${path} is stale`);
}
process.stdout.write(`foundation workspace snapshot ${mode}: ${profileDigest}\n`);
