import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  assertDurableCoordinationRegistryCurrent,
  DURABLE_COORDINATION_OUTPUT_PATH,
} from "./lib/platform-durable-coordination-registry";

export const DURABLE_COORDINATION_GO_OUTPUT_PATH =
  "services/control-plane/internal/coordination/registry_generated.go";

type GeneratedProfile = {
  readonly profileDigest: string;
  readonly spec: {
    readonly profileId: string;
    readonly operationId: string;
    readonly http: {
      readonly method: string;
      readonly path: string;
      readonly idempotencyHeader: string;
    };
    readonly subjectIdentity: {
      readonly schemaId: string;
      readonly digestProfile: string;
      readonly comparison: string;
    };
    readonly projection: {
      readonly schemaId: string;
      readonly canonicalizationProfile: string;
      readonly canonicalizationAlgorithm: string;
      readonly digestAlgorithm: string;
      readonly numberHandling: string;
    };
    readonly authorization: {
      readonly tenantSource: string;
      readonly requiredPermission: string;
      readonly scopeSource: string;
      readonly scopeIdentity: {
        readonly schemaId: string;
        readonly identifierProfile: string;
        readonly comparison: string;
      };
    };
    readonly coordination: {
      readonly createsPlatformOperation: boolean;
      readonly externalSideEffect: string;
      readonly outboxEventClass: string;
      readonly requiredFinalizers: ReadonlyArray<string>;
    };
    readonly idempotency: { readonly replayTtlSeconds: number };
    readonly result: { readonly resourceKind: string };
  };
};

type GeneratedRegistry = {
  readonly registryDigest: string;
  readonly stateMachineDigest: string;
  readonly policyDigest: string;
  readonly profiles: ReadonlyArray<GeneratedProfile>;
};

function goString(value: string): string {
  return JSON.stringify(value);
}

export function serializeDurableCoordinationGo(registry: GeneratedRegistry): string {
  if (registry.profiles.length !== 1) {
    throw new Error("The current Go consumer requires exactly one generated profile.");
  }
  const [{ profileDigest, spec }] = registry.profiles;
  if (
    spec.profileId !== "managedAgentCreateProject/v1alpha1" ||
    spec.operationId !== "managedAgentCreateProject" ||
    spec.http.method !== "POST" ||
    spec.http.path !== "/v1/tenants/{tenantId}/projects" ||
    spec.http.idempotencyHeader !== "Idempotency-Key" ||
    spec.subjectIdentity.schemaId !==
      "https://schemas.cloud-agents.dev/common/v1alpha1/schemas/subject-ref.schema.json" ||
    spec.subjectIdentity.digestProfile !== "cloud-agents-subject-ref/v1alpha1-rfc8785-sha256" ||
    spec.subjectIdentity.comparison !== "exact_string_no_rewrite" ||
    spec.projection.schemaId !==
      "https://schemas.cloud-agents.dev/platform/v1alpha1/schemas/managed-agent-create-project-idempotency-projection.schema.json" ||
    spec.projection.canonicalizationProfile !==
      "cloud-agents-http-idempotency/managedAgentCreateProject/v1alpha1" ||
    spec.projection.canonicalizationAlgorithm !== "RFC8785" ||
    spec.projection.digestAlgorithm !== "SHA-256" ||
    spec.projection.numberHandling !== "NOT_APPLICABLE_NO_NUMBER_FIELDS" ||
    spec.authorization.tenantSource !== "path.tenantId" ||
    spec.authorization.scopeSource !== "body.organizationRef" ||
    spec.authorization.scopeIdentity.schemaId !==
      "https://schemas.cloud-agents.dev/platform/v1alpha1/schemas/managed-agent-create-project-organization-ref.schema.json" ||
    spec.authorization.scopeIdentity.identifierProfile !==
      "cloud-agents-authorization-scope-identifier/ascii-v1" ||
    spec.authorization.scopeIdentity.comparison !== "exact_string_no_rewrite" ||
    spec.authorization.requiredPermission !== "projects.create" ||
    spec.coordination.createsPlatformOperation ||
    spec.coordination.externalSideEffect !== "forbidden" ||
    spec.coordination.outboxEventClass !== "resource_change" ||
    spec.coordination.requiredFinalizers.length !== 0 ||
    spec.idempotency.replayTtlSeconds !== 86400 ||
    spec.result.resourceKind !== "project"
  ) {
    throw new Error("The current generated Go profile boundary drifted.");
  }
  return `// Code generated by scripts/generate-platform-durable-coordination-go.ts; DO NOT EDIT.

package coordination

const (
\tRegistryDigest     = ${goString(registry.registryDigest)}
\tStateMachineDigest = ${goString(registry.stateMachineDigest)}
\tPolicyDigest       = ${goString(registry.policyDigest)}
)

var managedAgentCreateProjectProfile = operationProfile{
\tprofileID:                 ${goString(spec.profileId)},
\tprofileDigest:             ${goString(profileDigest)},
\toperationID:               ${goString(spec.operationId)},
\tprojectionSchemaID:        ${goString(spec.projection.schemaId)},
\tcanonicalizationProfile:   ${goString(spec.projection.canonicalizationProfile)},
\tcanonicalizationAlgorithm: ${goString(spec.projection.canonicalizationAlgorithm)},
\tdigestAlgorithm:           ${goString(spec.projection.digestAlgorithm)},
\ttenantSource:              ${goString(spec.authorization.tenantSource)},
\tscopeSource:               ${goString(spec.authorization.scopeSource)},
\tscopeIdentitySchemaID:     ${goString(spec.authorization.scopeIdentity.schemaId)},
\tscopeIdentifierProfile:    ${goString(spec.authorization.scopeIdentity.identifierProfile)},
\tscopeIdentityComparison:   ${goString(spec.authorization.scopeIdentity.comparison)},
\trequiredPermission:        ${goString(spec.authorization.requiredPermission)},
\trequiredScopeLevel:        "organization",
\toutboxEventClass:          ${goString(spec.coordination.outboxEventClass)},
\tresultResourceKind:        ${goString(spec.result.resourceKind)},
\treplayTTLSeconds:          ${spec.idempotency.replayTtlSeconds},
\tcreatesPlatformOperation:  ${String(spec.coordination.createsPlatformOperation)},
\texternalSideEffectAllowed: false,
}
`;
}

function readRegistry(root: string): GeneratedRegistry {
  assertDurableCoordinationRegistryCurrent(root);
  return JSON.parse(
    readFileSync(resolve(root, DURABLE_COORDINATION_OUTPUT_PATH), "utf8"),
  ) as GeneratedRegistry;
}

export function expectedDurableCoordinationGo(root: string): string {
  return serializeDurableCoordinationGo(readRegistry(root));
}

const root = resolve(import.meta.dirname, "..");
const output = resolve(root, DURABLE_COORDINATION_GO_OUTPUT_PATH);
const [mode] = process.argv.slice(2);

if (mode === "--write") {
  writeFileSync(output, expectedDurableCoordinationGo(root));
  process.stdout.write(
    `platform-durable-coordination-go: wrote ${DURABLE_COORDINATION_GO_OUTPUT_PATH}\n`,
  );
} else if (mode === "--check") {
  const expected = expectedDurableCoordinationGo(root);
  const actual = readFileSync(output, "utf8");
  if (actual !== expected) {
    throw new Error(
      `${DURABLE_COORDINATION_GO_OUTPUT_PATH} is stale; run bun scripts/generate-platform-durable-coordination-go.ts --write.`,
    );
  }
  process.stdout.write("platform-durable-coordination-go: current\n");
} else {
  throw new Error(
    "Usage: bun scripts/generate-platform-durable-coordination-go.ts --write|--check",
  );
}
