import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { migrationDigest } from "./lib/platform-migration-json";
import { splitPostgresStatements, classifyMigrationStatement } from "./lib/platform-migration-sql";
import { validateObjectIdentity } from "./lib/platform-migration-projection";

// One exact product successor; frozen predecessor artifacts are inputs, never rewritten.
const root = resolve(import.meta.dirname, "..");
const mode = process.argv[2];
assert.ok(mode === "--write" || mode === "--check");
const base = "services/control-plane/migrations/product/000055";
const sqlPath = "services/control-plane/migrations/000055_reconcile_foundation_sandboxes.sql";
const read = (path: string) => readFileSync(resolve(root, path));
const json = (path: string) => JSON.parse(read(path).toString());
const bytes = (value: unknown) => Buffer.from(JSON.stringify(value, null, 2) + "\n");
const digest = (data: Uint8Array) => "sha256:" + createHash("sha256").update(data).digest("hex");
const artifact = (path: string, data = read(path)) => ({
  path,
  mode: "100644",
  size_bytes: data.length,
  sha256: digest(data),
});
const prior = json("services/control-plane/migrations/product/000054/manifest.json");
const catalog = json(prior.schema_bundle.migrations.at(-1).catalog_contract.path);
catalog.schema_head = "000055";
const sql = read(sqlPath);
catalog.source_descriptors.push({
  migration_id: "000055",
  sql_sha256: digest(sql),
  statements: splitPostgresStatements(sql).map((s) => ({
    index: s.index,
    start: s.start,
    end: s.end,
    sha256: s.sha256,
    classification: classifyMigrationStatement(s, "000055"),
  })),
});
const additions: any[] = [];
for (const [name, arguments_] of [
  ["claim_foundation_sandbox_v1", ["text", "text", "text", "integer", "text", "text"]],
  [
    "renew_foundation_sandbox_claim_v1",
    ["text", "text", "text", "text", "text", "timestamptz", "integer"],
  ],
  [
    "settle_foundation_sandbox_v1",
    [
      "text",
      "text",
      "text",
      "text",
      "text",
      "timestamptz",
      "text",
      "text",
      "text",
      "text",
      "text",
      "boolean",
      "text",
      "text",
    ],
  ],
  ["reap_foundation_sandbox_claim_v1", ["text", "text"]],
] as const)
  additions.push({
    kind: "function",
    identity: {
      schema: "cloud_agents",
      name,
      arguments: arguments_.map((argument) => ({ schema: "pg_catalog", name: argument })),
    },
  });
for (const item of additions) validateObjectIdentity(item);
catalog.declared_object_identities.push(...additions);
const catalogBytes = bytes(catalog);
const catalogArtifact = artifact(`${base}/catalog/schema-000054.json`, catalogBytes);
const schema = structuredClone(prior.schema_bundle);
schema.schema_head = "000055";
schema.migrations.push({
  ...structuredClone(schema.migrations.at(-1)),
  id: "000055",
  name: "reconcile_foundation_sandboxes",
  predecessor_id: "000054",
  schema_from: "000054",
  schema_to: "000055",
  sql_artifact: artifact(sqlPath),
  predecessor_catalog_contract: prior.schema_bundle.migrations.at(-1).catalog_contract,
  catalog_contract: catalogArtifact,
});
const schemaDigest = migrationDigest({
  domain: "cloud-agents-platform-schema-bundle/v1",
  schema_bundle: schema,
});
const schemaBytes = bytes({
  format_version: "cloud-agents-platform-schema-bundle/v1",
  schema_bundle: schema,
  schema_bundle_digest: schemaDigest,
});
const schemaArtifact = artifact(`${base}/schema-bundle.json`, schemaBytes);
const manifest = structuredClone(prior);
manifest.schema_bundle = schema;
manifest.schema_bundle_digest = schemaDigest;
manifest.runtime_artifacts.push(artifact(sqlPath), catalogArtifact, schemaArtifact);
manifest.runtime_artifacts.sort((a: any, b: any) => a.path.localeCompare(b.path, "en"));
delete manifest.manifest_digest;
manifest.manifest_digest = migrationDigest(manifest);
const manifestBytes = bytes(manifest);
const binding = `// Code generated by scripts/generate-foundation-migration-package.ts; DO NOT EDIT.
package localmigration
var productFoundationRunnerBinding = generatedRunnerBindingSelector{
selectorID:"product-000055",schemaHead:"000055",migrationCount:55,
manifestPath:"${base}/manifest.json",manifestSizeBytes:${manifestBytes.length},manifestRawDigest:"${digest(manifestBytes)}",manifestDigest:"${manifest.manifest_digest}",
schemaBundlePath:"${schemaArtifact.path}",schemaBundleSizeBytes:${schemaBytes.length},schemaBundleRawDigest:"${schemaArtifact.sha256}",schemaBundleDigest:"${schemaDigest}",
}
`;
for (const [path, data] of new Map([
  [catalogArtifact.path, catalogBytes],
  [schemaArtifact.path, schemaBytes],
  [`${base}/manifest.json`, manifestBytes],
  [
    "services/control-plane/internal/localmigration/product_foundation_generated.go",
    execFileSync("gofmt", { input: binding }),
  ],
])) {
  if (mode === "--write") {
    mkdirSync(dirname(resolve(root, path)), { recursive: true });
    writeFileSync(resolve(root, path), data);
  } else assert.deepEqual(read(path), data, `${path} is stale`);
}
process.stdout.write(`product-000055 ${mode}: ${schemaDigest}\n`);
