import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  assertDurableCoordinationRegistryCurrent,
  DURABLE_COORDINATION_OUTPUT_PATH,
} from "./lib/platform-durable-coordination-registry";

export const DURABLE_COORDINATION_GO_OUTPUT_PATH =
  "services/control-plane/internal/coordination/registry_generated.go";

type GeneratedProfile = {
  readonly profileDigest: string;
  readonly spec: {
    readonly profileId: string;
    readonly operationId: string;
    readonly authorization: {
      readonly tenantSource: string;
      readonly requiredPermission: string;
      readonly scopeSource: string;
    };
    readonly coordination: {
      readonly createsPlatformOperation: boolean;
      readonly externalSideEffect: string;
      readonly outboxEventClass: string;
      readonly requiredFinalizers: ReadonlyArray<string>;
    };
    readonly idempotency: { readonly replayTtlSeconds: number };
    readonly result: { readonly resourceKind: string };
  };
};

type GeneratedRegistry = {
  readonly registryDigest: string;
  readonly stateMachineDigest: string;
  readonly policyDigest: string;
  readonly profiles: ReadonlyArray<GeneratedProfile>;
};

function goString(value: string): string {
  return JSON.stringify(value);
}

export function serializeDurableCoordinationGo(registry: GeneratedRegistry): string {
  if (registry.profiles.length !== 1) {
    throw new Error("The current Go consumer requires exactly one generated profile.");
  }
  const [{ profileDigest, spec }] = registry.profiles;
  if (
    spec.profileId !== "managedAgentCreateProject/v1alpha1" ||
    spec.operationId !== "managedAgentCreateProject" ||
    spec.authorization.tenantSource !== "path.tenantId" ||
    spec.authorization.scopeSource !== "body.organizationRef" ||
    spec.authorization.requiredPermission !== "projects.create" ||
    spec.coordination.createsPlatformOperation ||
    spec.coordination.externalSideEffect !== "forbidden" ||
    spec.coordination.outboxEventClass !== "resource_change" ||
    spec.coordination.requiredFinalizers.length !== 0 ||
    spec.idempotency.replayTtlSeconds !== 86400 ||
    spec.result.resourceKind !== "project"
  ) {
    throw new Error("The current generated Go profile boundary drifted.");
  }
  return `// Code generated by scripts/generate-platform-durable-coordination-go.ts; DO NOT EDIT.

package coordination

const (
\tRegistryDigest     = ${goString(registry.registryDigest)}
\tStateMachineDigest = ${goString(registry.stateMachineDigest)}
\tPolicyDigest       = ${goString(registry.policyDigest)}
)

var managedAgentCreateProjectProfile = operationProfile{
\tprofileID:                 ${goString(spec.profileId)},
\tprofileDigest:             ${goString(profileDigest)},
\toperationID:               ${goString(spec.operationId)},
\trequiredPermission:        ${goString(spec.authorization.requiredPermission)},
\trequiredScopeLevel:        "organization",
\toutboxEventClass:          ${goString(spec.coordination.outboxEventClass)},
\tresultResourceKind:        ${goString(spec.result.resourceKind)},
\treplayTTLSeconds:          ${spec.idempotency.replayTtlSeconds},
\tcreatesPlatformOperation:  ${String(spec.coordination.createsPlatformOperation)},
\texternalSideEffectAllowed: false,
}
`;
}

function readRegistry(root: string): GeneratedRegistry {
  assertDurableCoordinationRegistryCurrent(root);
  return JSON.parse(
    readFileSync(resolve(root, DURABLE_COORDINATION_OUTPUT_PATH), "utf8"),
  ) as GeneratedRegistry;
}

export function expectedDurableCoordinationGo(root: string): string {
  return serializeDurableCoordinationGo(readRegistry(root));
}

const root = resolve(import.meta.dirname, "..");
const output = resolve(root, DURABLE_COORDINATION_GO_OUTPUT_PATH);
const [mode] = process.argv.slice(2);

if (mode === "--write") {
  writeFileSync(output, expectedDurableCoordinationGo(root));
  process.stdout.write(
    `platform-durable-coordination-go: wrote ${DURABLE_COORDINATION_GO_OUTPUT_PATH}\n`,
  );
} else if (mode === "--check") {
  const expected = expectedDurableCoordinationGo(root);
  const actual = readFileSync(output, "utf8");
  if (actual !== expected) {
    throw new Error(
      `${DURABLE_COORDINATION_GO_OUTPUT_PATH} is stale; run bun scripts/generate-platform-durable-coordination-go.ts --write.`,
    );
  }
  process.stdout.write("platform-durable-coordination-go: current\n");
} else {
  throw new Error(
    "Usage: bun scripts/generate-platform-durable-coordination-go.ts --write|--check",
  );
}
