import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const registryPath = "contracts/generated/platform/v1alpha1/durable-coordination-registry-v2.json";
const outputPath = "services/control-plane/internal/coordination/registry_v2_generated.go";

type Registry = {
  registryDigest: string;
  stateMachineDigest: string;
  policyDigest: string;
  profiles: Array<{ profileDigest: string; spec: any }>;
};
const goString = (value: string) => JSON.stringify(value);
function expected(): string {
  const registry = JSON.parse(readFileSync(resolve(root, registryPath), "utf8")) as Registry;
  if (registry.profiles.length !== 1)
    throw new Error("durable project v2 registry must contain one profile");
  const { profileDigest, spec } = registry.profiles[0];
  if (spec.profileId !== "managedAgentCreateProjectDurable/v1alpha1")
    throw new Error("unexpected v2 profile");
  return `// Code generated by scripts/generate-platform-durable-coordination-go-v2.ts; DO NOT EDIT.

package coordination

const (
\tDurableProjectCreateRegistryDigest     = ${goString(registry.registryDigest)}
\tDurableProjectCreateStateMachineDigest = ${goString(registry.stateMachineDigest)}
\tDurableProjectCreatePolicyDigest       = ${goString(registry.policyDigest)}
)

var managedAgentCreateProjectDurableProfile = operationProfile{
\tprofileID:                 ${goString(spec.profileId)},
\tprofileDigest:             ${goString(profileDigest)},
\toperationID:               ${goString(spec.operationId)},
\tprojectionSchemaID:        ${goString(spec.projection.schemaId)},
\tcanonicalizationProfile:   ${goString(spec.projection.canonicalizationProfile)},
\tcanonicalizationAlgorithm: ${goString(spec.projection.canonicalizationAlgorithm)},
\tdigestAlgorithm:           ${goString(spec.projection.digestAlgorithm)},
\ttenantSource:              ${goString(spec.authorization.tenantSource)},
\tscopeSource:               ${goString(spec.authorization.scopeSource)},
\tscopeIdentitySchemaID:     ${goString(spec.authorization.scopeIdentity.schemaId)},
\tscopeIdentifierProfile:    ${goString(spec.authorization.scopeIdentity.identifierProfile)},
\tscopeIdentityComparison:   ${goString(spec.authorization.scopeIdentity.comparison)},
\trequiredPermission:        ${goString(spec.authorization.requiredPermission)},
\trequiredScopeLevel:        "organization",
\toutboxEventClass:          ${goString(spec.coordination.outboxEventClass)},
\tresultResourceKind:        ${goString(spec.result.resourceKind)},
\treplayTTLSeconds:          ${spec.idempotency.replayTtlSeconds},
\tcreatesPlatformOperation:  ${String(spec.coordination.createsPlatformOperation)},
\texternalSideEffectAllowed: false,
}
`;
}
const mode = process.argv[2] ?? "--check";
const output = resolve(root, outputPath);
const value = expected();
if (mode === "--write") {
  writeFileSync(output, value);
  process.stdout.write(`platform-durable-coordination-go-v2: wrote ${outputPath}\n`);
} else if (mode === "--check") {
  if (readFileSync(output, "utf8") !== value) throw new Error(`${outputPath} is stale`);
  process.stdout.write("platform-durable-coordination-go-v2: current\n");
} else
  throw new Error(
    "usage: bun scripts/generate-platform-durable-coordination-go-v2.ts [--write|--check]",
  );
