import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { canonicalizeMigrationJson, type MigrationJson } from "./lib/platform-migration-json";

const root = resolve(import.meta.dirname, "..");
const mode = process.argv[2];
if (mode !== "--write" && mode !== "--check") throw new Error("use --write or --check");
const profile = JSON.parse(
  readFileSync(
    resolve(root, "contracts/platform/v1alpha1/foundation-workspace-snapshot-cleanup.json"),
    "utf8",
  ),
);
assert.equal(profile.profileId, "foundationWorkspaceSnapshotCleanup/v1alpha1");
assert.equal(profile.resourceKind, "workspaceSnapshot");
assert.equal(profile.outboxEventClass, "operation_effect");
assert.equal(profile.externalSideEffect, "docker_snapshot_volume_delete_under_durable_claim");
assert.equal(profile.fence, "snapshot-resource-version");
assert.deepEqual(profile.allowedTriggers, ["manual", "retention"]);
assert.deepEqual(profile.requiredFinalizers, ["workspace-snapshot-delete"]);
assert.equal(profile.secretMaterial, "excluded");
const hash = (value: MigrationJson) =>
  "sha256:" + createHash("sha256").update(canonicalizeMigrationJson(value)).digest("hex");
const profileDigest = hash(profile);
const registryDigest = hash({ profileId: profile.profileId, profileDigest });
// Extend the last frozen registry projection; historical identities remain owned by that migration.
const predecessor = readFileSync(
  resolve(root, "services/control-plane/migrations/000082_add_foundation_workspace_snapshots.sql"),
  "utf8",
);
const boundary = predecessor.indexOf("ALTER TABLE cloud_agents.resource_changes");
assert.ok(boundary > 0, "snapshot registry projection is missing");
const registrySQL = predecessor.slice(predecessor.indexOf("\n") + 1, boundary).trimEnd();
const tables = [...registrySQL.matchAll(/\(VALUES [\s\S]*?\) AS profiles\(registry, id, digest, creates_operation\)/gu)];
assert.ok(tables.length > 0 && tables.every(([table]) => table === tables[0]![0]));
assert.ok(!registrySQL.includes(profile.profileId), "cleanup profile is already registered");
const table = tables[0]![0];
const literal = (value: string) => "'" + value.replaceAll("'", "''") + "'";
const extended = table.replace(
  ") AS profiles",
  `,\n(${[registryDigest, profile.profileId, profileDigest].map(literal).join(", ")}, true)) AS profiles`,
);
let sql =
  "-- Generated by scripts/generate-foundation-workspace-snapshot-cleanup.ts; DO NOT EDIT.\n" +
  registrySQL.replaceAll(table, extended) + "\n";
sql += readFileSync(
  resolve(root, "scripts/templates/foundation-workspace-snapshot-cleanup.sql"),
  "utf8",
)
  .replaceAll("@PROFILE_ID@", profile.profileId)
  .replaceAll("@PROFILE_DIGEST@", profileDigest)
  .replaceAll("@REGISTRY_DIGEST@", registryDigest);
const go = `// Code generated by scripts/generate-foundation-workspace-snapshot-cleanup.ts; DO NOT EDIT.\n\npackage coordination\n\nconst (\n\tWorkspaceSnapshotCleanupProfileID = ${JSON.stringify(profile.profileId)}\n\tWorkspaceSnapshotCleanupProfileDigest = ${JSON.stringify(profileDigest)}\n\tWorkspaceSnapshotCleanupRegistryDigest = ${JSON.stringify(registryDigest)}\n)\n`;
for (const [path, content] of [
  ["services/control-plane/migrations/000084_cleanup_foundation_workspace_snapshots.sql", sql],
  [
    "services/control-plane/internal/coordination/foundation_snapshot_cleanup_generated.go",
    execFileSync("gofmt", { input: go, encoding: "utf8" }),
  ],
] as const) {
  if (mode === "--write") writeFileSync(resolve(root, path), content);
  else if (readFileSync(resolve(root, path), "utf8") !== content)
    throw new Error(`${path} is stale`);
}
process.stdout.write(`foundation workspace snapshot cleanup ${mode}: ${profileDigest}\n`);
