-- Generated by scripts/generate-foundation-workspace-snapshot.ts; DO NOT EDIT.
CREATE OR REPLACE FUNCTION cloud_agents.coordination_registry_profile_is_registered(p_registry_digest text, p_profile_id text, p_profile_digest text)
RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, cloud_agents
AS $$ SELECT EXISTS (SELECT 1 FROM (VALUES ('sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30', 'managedAgentCreateProject/v1alpha1', 'sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a', false),
('sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a', 'managedAgentCreateProject/v1alpha1', 'sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308', false),
('sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8', 'managedAgentCreateProjectDurable/v1alpha1', 'sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f', true),
('sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c', 'foundationSandboxLifecycle/v1alpha1', 'sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b', true),
('sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', true)) AS profiles(registry, id, digest, creates_operation) WHERE registry = p_registry_digest AND id = p_profile_id AND digest = p_profile_digest) $$;

CREATE OR REPLACE FUNCTION cloud_agents.coordination_registry_digest_for_profile(p_profile_id text, p_profile_digest text)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, cloud_agents
AS $$ SELECT registry FROM (VALUES ('sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30', 'managedAgentCreateProject/v1alpha1', 'sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a', false),
('sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a', 'managedAgentCreateProject/v1alpha1', 'sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308', false),
('sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8', 'managedAgentCreateProjectDurable/v1alpha1', 'sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f', true),
('sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c', 'foundationSandboxLifecycle/v1alpha1', 'sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b', true),
('sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', true)) AS profiles(registry, id, digest, creates_operation) WHERE id = p_profile_id AND digest = p_profile_digest $$;

CREATE OR REPLACE FUNCTION cloud_agents.coordination_profile_is_registered(p_profile_id text, p_profile_digest text)
RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, cloud_agents
AS $$ SELECT EXISTS (SELECT 1 FROM (VALUES ('sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30', 'managedAgentCreateProject/v1alpha1', 'sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a', false),
('sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a', 'managedAgentCreateProject/v1alpha1', 'sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308', false),
('sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8', 'managedAgentCreateProjectDurable/v1alpha1', 'sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f', true),
('sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c', 'foundationSandboxLifecycle/v1alpha1', 'sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b', true),
('sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', true)) AS profiles(registry, id, digest, creates_operation) WHERE id = p_profile_id AND digest = p_profile_digest) $$;

CREATE OR REPLACE FUNCTION cloud_agents.coordination_profile_creates_operation(p_profile_id text, p_profile_digest text)
RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, cloud_agents
AS $$ SELECT EXISTS (SELECT 1 FROM (VALUES ('sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30', 'managedAgentCreateProject/v1alpha1', 'sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a', false),
('sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a', 'managedAgentCreateProject/v1alpha1', 'sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308', false),
('sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8', 'managedAgentCreateProjectDurable/v1alpha1', 'sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f', true),
('sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c', 'foundationSandboxLifecycle/v1alpha1', 'sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b', true),
('sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', true)) AS profiles(registry, id, digest, creates_operation) WHERE id = p_profile_id AND digest = p_profile_digest AND creates_operation) $$;

CREATE OR REPLACE FUNCTION cloud_agents.coordination_profile_outbox_class(p_profile_id text, p_profile_digest text)
RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, cloud_agents
AS $$ SELECT CASE WHEN creates_operation THEN 'operation_effect' ELSE 'resource_change' END FROM (VALUES ('sha256:11c0f599e8320668a6f601241206c795933b26e3b9c456a58353a0d13c7ecd30', 'managedAgentCreateProject/v1alpha1', 'sha256:059b4cca58f9621e9b70b723fb3b681f62948d6d4965af60105165afce680d5a', false),
('sha256:ca5703cbbc68f7501e6fb4da0a0f09bc9fdd6e52bc48f080627bec64fd1b635a', 'managedAgentCreateProject/v1alpha1', 'sha256:cdd54c59c0c363687eeb0e0e48aff00221cc4d42780bdf935c4b47bcd297f308', false),
('sha256:8c973a9460b659eb601fb5db547eb9fd85b25bf74d050c56a76f003710118ec8', 'managedAgentCreateProjectDurable/v1alpha1', 'sha256:48d3afc5e78e7e7c537e528f74a510b91d08cffa4415eed3f6d651bd78deb81f', true),
('sha256:9ebf663f49a5d1f5209d5c94656419d21fc2022105355d51a5b2fc3ed318378c', 'foundationSandboxLifecycle/v1alpha1', 'sha256:aabd6aa244c89a4850eba529dbe387132c3a0aff7ffba430f6115afb6e215a1b', true),
('sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', true)) AS profiles(registry, id, digest, creates_operation) WHERE id = p_profile_id AND digest = p_profile_digest $$;

ALTER TABLE cloud_agents.resource_changes DROP CONSTRAINT resource_changes_resource_kind;
ALTER TABLE cloud_agents.resource_changes ADD CONSTRAINT resource_changes_resource_kind
    CHECK (resource_kind IN ('platform_tenant', 'organization', 'project', 'membership', 'role_binding', 'sandboxSession', 'workspaceSnapshot'));

CREATE TABLE cloud_agents.workspace_snapshots (
    tenant_id text NOT NULL,
    project_uid text NOT NULL,
    snapshot_uid text NOT NULL CHECK (cloud_agents.is_valid_identifier(snapshot_uid)),
    source_workspace_uid text NOT NULL,
    source_workspace_resource_version bigint NOT NULL CHECK (source_workspace_resource_version > 0),
    source_sandbox_uid text NOT NULL CHECK (cloud_agents.is_valid_identifier(source_sandbox_uid)),
    source_sandbox_generation bigint NOT NULL CHECK (source_sandbox_generation > 0),
    source_volume_uid text NOT NULL,
    target_uid text NOT NULL,
    backend text NOT NULL DEFAULT 'docker-volume-v1' CHECK (backend = 'docker-volume-v1'),
    consistency_mode text NOT NULL DEFAULT 'offline' CHECK (consistency_mode = 'offline'),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'available', 'unknown', 'failed')),
    operation_id text NOT NULL,
    operation_generation bigint NOT NULL DEFAULT 1 CHECK (operation_generation = 1),
    resource_version bigint NOT NULL DEFAULT 1 CHECK (resource_version > 0),
    source_physical_volume_uid text NOT NULL CHECK (cloud_agents.is_valid_identifier(source_physical_volume_uid)),
    image_uri text NOT NULL CHECK (image_uri ~ '^[A-Za-z0-9._:/-]+@sha256:[0-9a-f]{64}$' AND length(image_uri) <= 1024),
    physical_snapshot_uid text CHECK (physical_snapshot_uid IS NULL OR cloud_agents.is_valid_identifier(physical_snapshot_uid)),
    content_digest text CHECK (content_digest IS NULL OR content_digest ~ '^sha256:[0-9a-f]{64}$'),
    size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes BETWEEN 0 AND 67108864),
    stable_error_code text CHECK (stable_error_code IS NULL OR cloud_agents.is_valid_identifier(stable_error_code)),
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    observed_at timestamptz,
    PRIMARY KEY (tenant_id, project_uid, snapshot_uid),
    UNIQUE (tenant_id, operation_id, operation_generation),
    FOREIGN KEY (tenant_id, project_uid, source_workspace_uid) REFERENCES cloud_agents.workspaces
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, project_uid, source_volume_uid) REFERENCES cloud_agents.workspace_volumes
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, project_uid, target_uid) REFERENCES cloud_agents.deployment_targets
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, operation_id, operation_generation) REFERENCES cloud_agents.platform_operations
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CHECK (
        status = 'pending' AND physical_snapshot_uid IS NULL AND content_digest IS NULL AND size_bytes IS NULL AND stable_error_code IS NULL AND observed_at IS NULL
        OR status = 'available' AND physical_snapshot_uid IS NOT NULL AND content_digest IS NOT NULL AND size_bytes IS NOT NULL AND stable_error_code IS NULL AND observed_at IS NOT NULL
        OR status = 'unknown' AND physical_snapshot_uid IS NULL AND content_digest IS NULL AND size_bytes IS NULL AND stable_error_code IS NULL AND observed_at IS NOT NULL
        OR status = 'failed' AND physical_snapshot_uid IS NULL AND content_digest IS NULL AND size_bytes IS NULL AND stable_error_code IS NOT NULL AND observed_at IS NOT NULL
    )
);
CREATE INDEX workspace_snapshots_source_idx ON cloud_agents.workspace_snapshots (tenant_id, project_uid, source_workspace_uid);
CREATE INDEX workspace_snapshots_status_idx ON cloud_agents.workspace_snapshots (status, created_at, tenant_id, snapshot_uid);
ALTER TABLE cloud_agents.workspace_snapshots OWNER TO cloud_agents_migration_owner;
ALTER TABLE cloud_agents.workspace_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE cloud_agents.workspace_snapshots FORCE ROW LEVEL SECURITY;
CREATE POLICY workspace_snapshots_runtime ON cloud_agents.workspace_snapshots TO cloud_agents_runtime
    USING (tenant_id = cloud_agents.require_tenant_id()) WITH CHECK (tenant_id = cloud_agents.require_tenant_id());
CREATE POLICY workspace_snapshots_owner ON cloud_agents.workspace_snapshots TO cloud_agents_migration_owner USING (true) WITH CHECK (true);
REVOKE ALL ON TABLE cloud_agents.workspace_snapshots FROM PUBLIC;
GRANT SELECT ON TABLE cloud_agents.workspace_snapshots TO cloud_agents_runtime;

CREATE FUNCTION cloud_agents.accept_foundation_workspace_snapshot_v1(
    p_project text, p_snapshot text, p_sandbox text, p_expected_sandbox_generation bigint,
    p_subject text, p_key text, p_digest text
)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, cloud_agents
AS $$
DECLARE
    actor text;
    tenant text;
    source_volume text;
    source_physical_volume text;
    selected_workspace text;
    selected_workspace_version bigint;
    selected_target text;
    selected_image text;
    operation_value text;
    event_value text;
    prior_digest text;
    prior_operation text;
BEGIN
    actor := cloud_agents.require_runtime_mutation_principal();
    tenant := cloud_agents.require_tenant_id();
    IF NOT cloud_agents.is_valid_identifier(p_project) OR NOT cloud_agents.is_valid_identifier(p_snapshot)
        OR NOT cloud_agents.is_valid_identifier(p_sandbox) OR p_expected_sandbox_generation < 1
        OR p_subject !~ '^sha256:[0-9a-f]{64}$' OR p_key !~ '^[A-Za-z0-9._~-]{16,128}$'
        OR p_digest !~ '^sha256:[0-9a-f]{64}$'
    THEN RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'workspace snapshot request is invalid'; END IF;

    SELECT record.request_digest, record.operation_id INTO prior_digest, prior_operation
    FROM cloud_agents.idempotency_records AS record
    WHERE record.tenant_id = tenant AND record.subject_digest = p_subject
      AND record.profile_id = 'foundationWorkspaceSnapshot/v1alpha1' AND record.profile_digest = 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f'
      AND record.idempotency_key = p_key FOR UPDATE;
    IF FOUND THEN
        IF prior_digest IS DISTINCT FROM p_digest OR NOT EXISTS (
            SELECT 1 FROM cloud_agents.workspace_snapshots AS snapshot
            WHERE snapshot.tenant_id = tenant AND snapshot.project_uid = p_project
              AND snapshot.snapshot_uid = p_snapshot AND snapshot.source_sandbox_uid = p_sandbox
              AND snapshot.source_sandbox_generation = p_expected_sandbox_generation
              AND snapshot.operation_id = prior_operation
        ) THEN RAISE EXCEPTION USING ERRCODE = '23505', MESSAGE = 'workspace snapshot idempotency conflict'; END IF;
        RETURN prior_operation;
    END IF;

    SELECT sandbox.workspace_uid, workspace.resource_version, volume.volume_uid,
      volume.physical_volume_uid, volume.target_uid, sandbox.image_uri
      INTO selected_workspace, selected_workspace_version, source_volume,
        source_physical_volume, selected_target, selected_image
    FROM cloud_agents.sandbox_sessions AS sandbox
    JOIN cloud_agents.workspaces AS workspace
      ON workspace.tenant_id = sandbox.tenant_id AND workspace.project_uid = sandbox.project_uid AND workspace.workspace_uid = sandbox.workspace_uid
    JOIN cloud_agents.workspace_volumes AS volume
      ON volume.tenant_id = sandbox.tenant_id AND volume.project_uid = sandbox.project_uid AND volume.workspace_uid = sandbox.workspace_uid
    JOIN cloud_agents.deployment_targets AS target
      ON target.tenant_id = volume.tenant_id AND target.project_uid = volume.project_uid AND target.target_uid = volume.target_uid
    WHERE sandbox.tenant_id = tenant AND sandbox.project_uid = p_project AND sandbox.sandbox_uid = p_sandbox
      AND sandbox.generation = p_expected_sandbox_generation AND sandbox.desired_state = 'stopped'
      AND sandbox.observed_state = 'stopped' AND sandbox.observed_generation = sandbox.generation AND sandbox.writer_released
      AND volume.observed_state = 'available' AND volume.physical_volume_uid IS NOT NULL
      AND target.target_kind = 'docker' AND target.observed_phase = 'ready' AND target.scheduling_state = 'active'
    FOR SHARE OF sandbox, workspace, volume, target;
    IF NOT FOUND OR EXISTS (
        SELECT 1 FROM cloud_agents.sandbox_sessions AS writer
        WHERE writer.tenant_id = tenant AND writer.project_uid = p_project
          AND writer.workspace_uid = selected_workspace AND NOT writer.writer_released
    ) THEN RAISE EXCEPTION USING ERRCODE = '23505', MESSAGE = 'workspace snapshot requires an offline source'; END IF;

    BEGIN
        UPDATE cloud_agents.sandbox_sessions SET writer_released = false
        WHERE tenant_id = tenant AND project_uid = p_project AND sandbox_uid = p_sandbox
          AND generation = p_expected_sandbox_generation AND desired_state = 'stopped'
          AND observed_state = 'stopped' AND observed_generation = generation AND writer_released;
    EXCEPTION WHEN unique_violation THEN
        RAISE EXCEPTION USING ERRCODE = '23505', MESSAGE = 'workspace snapshot source conflict';
    END;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '23505', MESSAGE = 'workspace snapshot source conflict'; END IF;

    operation_value := 'op-' || pg_catalog.md5(tenant || '|' || p_project || '|' || p_snapshot || '|' || p_key);
    event_value := 'evt-' || pg_catalog.md5(tenant || '|' || p_project || '|' || p_snapshot || '|' || p_key);
    INSERT INTO cloud_agents.idempotency_records
        (tenant_id, tenant_ref_id, subject_digest, registry_digest, profile_id, profile_digest,
         idempotency_key, request_digest, state, expires_at)
    VALUES (tenant, tenant, p_subject, 'sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f',
        p_key, p_digest, 'pending', transaction_timestamp() + interval '1 day');
    INSERT INTO cloud_agents.platform_operations
        (tenant_id, tenant_ref_id, operation_id, operation_generation, registry_digest, state_machine_digest,
         policy_digest, profile_id, profile_digest, subject_digest, request_digest, state, cleanup_phase,
         recovery_generation, current_attempt_number)
    VALUES (tenant, tenant, operation_value, 1, 'sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', cloud_agents.coordination_state_machine_digest(),
        cloud_agents.coordination_policy_digest(), 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', p_subject, p_digest,
        'pending', 'none', 0, 0);
    INSERT INTO cloud_agents.workspace_snapshots
        (tenant_id, project_uid, snapshot_uid, source_workspace_uid, source_workspace_resource_version,
         source_sandbox_uid, source_sandbox_generation, source_volume_uid, target_uid, operation_id, source_physical_volume_uid, image_uri)
    VALUES (tenant, p_project, p_snapshot, selected_workspace, selected_workspace_version, p_sandbox, p_expected_sandbox_generation,
        source_volume, selected_target, operation_value, source_physical_volume, selected_image);
    INSERT INTO cloud_agents.operation_finalizers
        (tenant_id, tenant_ref_id, operation_id, operation_generation, finalizer_name, required, state, delivery_attempts)
    VALUES (tenant, tenant, operation_value, 1, 'workspace-snapshot-copy', true, 'pending', 0);
    INSERT INTO cloud_agents.outbox_events
        (tenant_id, tenant_ref_id, event_id, registry_digest, profile_id, profile_digest, event_class,
         aggregate_kind, aggregate_id, aggregate_sequence, generation, operation_id, operation_generation,
         payload_digest, state, delivery_attempts)
    VALUES (tenant, tenant, event_value, 'sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f', 'operation_effect',
        'workspaceSnapshot', p_snapshot, 1, 1, operation_value, 1, p_digest, 'pending', 0);
    INSERT INTO cloud_agents.coordination_audit_facts
        (tenant_id, tenant_ref_id, audit_fact_id, registry_digest, profile_id, profile_digest,
         subject_digest, operation_id, operation_generation, transition, outcome)
    VALUES (tenant, tenant, event_value, 'sha256:b1398bb866a44269a21a101f6e4d2b12eb19cbccd001b7f673010eecbf015f94', 'foundationWorkspaceSnapshot/v1alpha1', 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f',
        p_subject, operation_value, 1, 'workspace.snapshot.accept', 'pending');
    UPDATE cloud_agents.idempotency_records SET operation_id = operation_value, operation_generation = 1
    WHERE tenant_id = tenant AND subject_digest = p_subject AND profile_id = 'foundationWorkspaceSnapshot/v1alpha1'
      AND profile_digest = 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f' AND idempotency_key = p_key;
    RETURN operation_value;
END;
$$;

CREATE FUNCTION cloud_agents.claim_foundation_workspace_snapshot_v1(
    p_holder text, p_incarnation text, p_token text, p_lease_seconds integer, p_subject text, p_audit text
)
RETURNS TABLE (
    tenant_id text, event_id text, delivery_attempts integer, claim_expires_at timestamptz,
    operation_id text, project_uid text, snapshot_uid text, workspace_uid text,
    target_uid text, target_endpoint text, credential_ref text, source_volume_uid text, image_uri text
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, cloud_agents
AS $$
DECLARE claimed_at timestamptz := transaction_timestamp(); candidate cloud_agents.outbox_events%ROWTYPE;
BEGIN
    PERFORM cloud_agents.require_runtime_mutation_principal();
    IF NOT cloud_agents.is_valid_identifier(p_holder) OR NOT cloud_agents.is_valid_identifier(p_incarnation)
      OR NOT cloud_agents.is_valid_identifier(p_token) OR p_lease_seconds NOT BETWEEN 1 AND 60
      OR p_subject !~ '^sha256:[0-9a-f]{64}$' OR NOT cloud_agents.is_valid_identifier(p_audit)
    THEN RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'workspace snapshot claim is invalid'; END IF;
    SELECT event.* INTO candidate FROM cloud_agents.outbox_events AS event
    JOIN cloud_agents.workspace_snapshots AS snapshot
      ON snapshot.tenant_id = event.tenant_id AND snapshot.operation_id = event.operation_id
     AND snapshot.operation_generation = event.operation_generation AND snapshot.snapshot_uid = event.aggregate_id
    JOIN cloud_agents.workspaces AS workspace
      ON workspace.tenant_id = snapshot.tenant_id AND workspace.project_uid = snapshot.project_uid AND workspace.workspace_uid = snapshot.source_workspace_uid
    JOIN cloud_agents.workspace_volumes AS volume
      ON volume.tenant_id = snapshot.tenant_id AND volume.project_uid = snapshot.project_uid AND volume.volume_uid = snapshot.source_volume_uid
    JOIN cloud_agents.sandbox_sessions AS source
      ON source.tenant_id = snapshot.tenant_id AND source.project_uid = snapshot.project_uid
     AND source.sandbox_uid = snapshot.source_sandbox_uid AND source.workspace_uid = snapshot.source_workspace_uid
    JOIN cloud_agents.deployment_targets AS target
      ON target.tenant_id = snapshot.tenant_id AND target.project_uid = snapshot.project_uid AND target.target_uid = snapshot.target_uid
    WHERE event.profile_id = 'foundationWorkspaceSnapshot/v1alpha1' AND event.profile_digest = 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f'
      AND event.event_class = 'operation_effect' AND event.aggregate_kind = 'workspaceSnapshot'
      AND (event.state = 'pending' OR event.state = 'retry_wait' AND event.next_attempt_at <= claimed_at)
      AND event.delivery_attempts < 8 AND snapshot.status IN ('pending', 'unknown')
      AND workspace.resource_version = snapshot.source_workspace_resource_version
      AND source.generation = snapshot.source_sandbox_generation AND source.desired_state = 'stopped'
      AND source.observed_state = 'stopped' AND source.observed_generation = source.generation AND NOT source.writer_released
      AND volume.observed_state = 'available' AND volume.physical_volume_uid = snapshot.source_physical_volume_uid
      AND target.target_kind = 'docker' AND target.observed_phase = 'ready' AND target.scheduling_state = 'active'
      AND NOT EXISTS (SELECT 1 FROM cloud_agents.sandbox_sessions AS writer
          WHERE writer.tenant_id = snapshot.tenant_id AND writer.project_uid = snapshot.project_uid
            AND writer.workspace_uid = snapshot.source_workspace_uid AND writer.sandbox_uid <> snapshot.source_sandbox_uid
            AND NOT writer.writer_released)
    ORDER BY event.created_at, event.tenant_id, event.event_id FOR UPDATE OF event SKIP LOCKED LIMIT 1;
    IF NOT FOUND THEN RETURN; END IF;
    PERFORM pg_catalog.set_config('cloud_agents.tenant_id', candidate.tenant_id, true);
    UPDATE cloud_agents.outbox_events AS event SET state = 'claimed', delivery_attempts = event.delivery_attempts + 1,
      next_attempt_at = NULL, claim_holder_id = p_holder, claim_incarnation = p_incarnation, claim_token = p_token,
      claim_started_at = claimed_at, claim_expires_at = claimed_at + pg_catalog.make_interval(secs => p_lease_seconds), updated_at = claimed_at
    WHERE event.tenant_id = candidate.tenant_id AND event.event_id = candidate.event_id RETURNING event.* INTO candidate;
    UPDATE cloud_agents.platform_operations AS operation SET state = CASE WHEN candidate.delivery_attempts = 1 THEN 'running' ELSE 'reconciling' END,
      recovery_generation = candidate.delivery_attempts - 1, current_attempt_number = candidate.delivery_attempts, updated_at = claimed_at
    WHERE operation.tenant_id = candidate.tenant_id AND operation.operation_id = candidate.operation_id
      AND operation.operation_generation = candidate.operation_generation AND operation.state IN ('pending', 'running', 'reconciling');
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot operation is not claimable'; END IF;
    INSERT INTO cloud_agents.operation_attempts
      (tenant_id, tenant_ref_id, operation_id, operation_generation, attempt_number, state,
       claim_holder_id, claim_incarnation, claim_token, claim_started_at, claim_expires_at, created_at, updated_at)
    VALUES (candidate.tenant_id, candidate.tenant_id, candidate.operation_id, candidate.operation_generation,
      candidate.delivery_attempts, 'claimed', p_holder, p_incarnation, p_token, claimed_at, candidate.claim_expires_at, claimed_at, claimed_at);
    PERFORM cloud_agents.append_coordination_audit(candidate.tenant_id, p_audit, candidate.profile_id, candidate.profile_digest,
      p_subject, candidate.operation_id, candidate.operation_generation, candidate.delivery_attempts,
      NULL, NULL, NULL, 'workspace.snapshot.claim', 'pending', NULL, NULL, claimed_at);
    RETURN QUERY SELECT candidate.tenant_id, candidate.event_id, candidate.delivery_attempts, candidate.claim_expires_at,
      candidate.operation_id, snapshot.project_uid, snapshot.snapshot_uid, snapshot.source_workspace_uid,
      snapshot.target_uid, target.endpoint, target.credential_ref, snapshot.source_physical_volume_uid, snapshot.image_uri
    FROM cloud_agents.workspace_snapshots AS snapshot
    JOIN cloud_agents.deployment_targets AS target
      ON target.tenant_id = snapshot.tenant_id AND target.project_uid = snapshot.project_uid AND target.target_uid = snapshot.target_uid
    WHERE snapshot.tenant_id = candidate.tenant_id AND snapshot.operation_id = candidate.operation_id;
END;
$$;

CREATE FUNCTION cloud_agents.renew_foundation_workspace_snapshot_claim_v1(
    p_tenant text, p_event text, p_holder text, p_incarnation text, p_token text, p_prior_expiry timestamptz, p_lease_seconds integer
)
RETURNS timestamptz LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, cloud_agents
AS $$
DECLARE renewed_at timestamptz := transaction_timestamp(); renewed_expiry timestamptz;
BEGIN
    PERFORM cloud_agents.require_runtime_mutation_principal();
    IF p_tenant IS DISTINCT FROM cloud_agents.require_tenant_id() OR p_lease_seconds NOT BETWEEN 1 AND 60
      OR NOT cloud_agents.is_valid_identifier(p_event) OR NOT cloud_agents.is_valid_identifier(p_holder)
      OR NOT cloud_agents.is_valid_identifier(p_incarnation) OR NOT cloud_agents.is_valid_identifier(p_token) OR p_prior_expiry IS NULL
    THEN RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'workspace snapshot renewal is invalid'; END IF;
    renewed_expiry := renewed_at + pg_catalog.make_interval(secs => p_lease_seconds);
    UPDATE cloud_agents.outbox_events AS event SET claim_expires_at = renewed_expiry, updated_at = renewed_at
    WHERE event.tenant_id = p_tenant AND event.event_id = p_event AND event.state = 'claimed'
      AND event.profile_id = 'foundationWorkspaceSnapshot/v1alpha1' AND event.claim_holder_id = p_holder
      AND event.claim_incarnation = p_incarnation AND event.claim_token = p_token
      AND event.claim_expires_at = p_prior_expiry AND event.claim_expires_at > renewed_at;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot claim is stale'; END IF;
    UPDATE cloud_agents.operation_attempts AS attempt SET claim_expires_at = renewed_expiry, updated_at = renewed_at
    FROM cloud_agents.outbox_events AS event WHERE event.tenant_id = p_tenant AND event.event_id = p_event
      AND attempt.tenant_id = event.tenant_id AND attempt.operation_id = event.operation_id
      AND attempt.operation_generation = event.operation_generation AND attempt.attempt_number = event.delivery_attempts
      AND attempt.state = 'claimed' AND attempt.claim_holder_id = p_holder
      AND attempt.claim_incarnation = p_incarnation AND attempt.claim_token = p_token AND attempt.claim_expires_at = p_prior_expiry;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot attempt is stale'; END IF;
    RETURN renewed_expiry;
END;
$$;

CREATE FUNCTION cloud_agents.settle_foundation_workspace_snapshot_v1(
    p_tenant text, p_event text, p_holder text, p_incarnation text, p_token text, p_expiry timestamptz,
    p_transition text, p_snapshot_volume text, p_content_digest text, p_size_bytes bigint,
    p_error text, p_cleanup_complete boolean, p_subject text, p_audit text
)
RETURNS TABLE (outbox_state text, operation_state text, resource_version bigint)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, cloud_agents
AS $$
DECLARE actor text; settled_at timestamptz := transaction_timestamp(); event cloud_agents.outbox_events%ROWTYPE; next_revision bigint; expected_revision bigint;
BEGIN
    actor := cloud_agents.require_runtime_mutation_principal();
    IF p_tenant IS DISTINCT FROM cloud_agents.require_tenant_id() OR p_transition NOT IN ('succeeded', 'retry', 'failed')
      OR NOT cloud_agents.is_valid_identifier(p_event) OR NOT cloud_agents.is_valid_identifier(p_holder)
      OR NOT cloud_agents.is_valid_identifier(p_incarnation) OR NOT cloud_agents.is_valid_identifier(p_token)
      OR p_expiry IS NULL OR p_cleanup_complete IS NULL OR p_subject !~ '^sha256:[0-9a-f]{64}$'
      OR NOT cloud_agents.is_valid_identifier(p_audit)
      OR p_transition = 'succeeded' AND (NOT cloud_agents.is_valid_identifier(p_snapshot_volume)
          OR p_content_digest !~ '^sha256:[0-9a-f]{64}$' OR p_size_bytes NOT BETWEEN 0 AND 67108864
          OR p_error IS NOT NULL OR NOT p_cleanup_complete)
      OR p_transition <> 'succeeded' AND (NOT cloud_agents.is_valid_identifier(p_error)
          OR p_snapshot_volume IS NOT NULL OR p_content_digest IS NOT NULL OR p_size_bytes IS NOT NULL)
    THEN RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'workspace snapshot settlement is invalid'; END IF;
    SELECT stored.* INTO event FROM cloud_agents.outbox_events AS stored
    WHERE stored.tenant_id = p_tenant AND stored.event_id = p_event FOR UPDATE;
    IF NOT FOUND OR event.state <> 'claimed' OR event.profile_id <> 'foundationWorkspaceSnapshot/v1alpha1' OR event.profile_digest <> 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f'
      OR event.claim_holder_id IS DISTINCT FROM p_holder OR event.claim_incarnation IS DISTINCT FROM p_incarnation
      OR event.claim_token IS DISTINCT FROM p_token OR event.claim_expires_at IS DISTINCT FROM p_expiry
      OR event.claim_expires_at <= settled_at OR p_transition = 'retry' AND event.delivery_attempts >= 8
    THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot settlement claim is stale'; END IF;
    IF p_transition = 'succeeded' THEN
      SELECT revision.current_revision INTO expected_revision FROM cloud_agents.tenant_resource_versions AS revision
      WHERE revision.tenant_id = p_tenant AND revision.tenant_uid = p_tenant FOR UPDATE;
      next_revision := cloud_agents.allocate_tenant_revision(p_tenant, expected_revision, settled_at);
      INSERT INTO cloud_agents.resource_changes (tenant_id, tenant_uid, resource_version, resource_kind, resource_uid, change_kind, actor_database_principal, occurred_at)
      VALUES (p_tenant, p_tenant, next_revision, 'workspaceSnapshot', event.aggregate_id, 'created', actor, settled_at);
      PERFORM * FROM cloud_agents.transition_outbox_claim(p_tenant, p_event, p_holder, p_incarnation, p_token, p_expiry,
        'delivery_succeeded', NULL, p_subject, p_audit);
      UPDATE cloud_agents.workspace_snapshots SET status = 'available', physical_snapshot_uid = p_snapshot_volume,
        content_digest = p_content_digest, size_bytes = p_size_bytes, stable_error_code = NULL,
        resource_version = next_revision, updated_at = settled_at, observed_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND snapshot_uid = event.aggregate_id;
      UPDATE cloud_agents.sandbox_sessions AS source SET writer_released = true
      FROM cloud_agents.workspace_snapshots AS snapshot
      WHERE snapshot.tenant_id = p_tenant AND snapshot.operation_id = event.operation_id
        AND source.tenant_id = snapshot.tenant_id AND source.project_uid = snapshot.project_uid
        AND source.sandbox_uid = snapshot.source_sandbox_uid AND source.generation = snapshot.source_sandbox_generation
        AND source.desired_state = 'stopped' AND source.observed_state = 'stopped'
        AND source.observed_generation = source.generation AND NOT source.writer_released;
      IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot writer fence drifted'; END IF;
      UPDATE cloud_agents.operation_attempts SET state = 'succeeded', claim_holder_id = NULL, claim_incarnation = NULL,
        claim_token = NULL, claim_started_at = NULL, claim_expires_at = NULL, updated_at = settled_at, terminal_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation AND attempt_number = event.delivery_attempts;
      UPDATE cloud_agents.platform_operations SET state = 'succeeded', cleanup_phase = 'complete', terminal_resource_kind = 'workspaceSnapshot',
        terminal_resource_id = event.aggregate_id, terminal_resource_version = next_revision, updated_at = settled_at, terminal_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
      UPDATE cloud_agents.operation_finalizers SET state = 'succeeded', updated_at = settled_at, terminal_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
      UPDATE cloud_agents.idempotency_records SET state = 'succeeded', resource_kind = 'workspaceSnapshot', resource_id = event.aggregate_id,
        resource_version = next_revision, updated_at = settled_at, terminal_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
      INSERT INTO cloud_agents.terminal_receipts (tenant_id, tenant_ref_id, operation_id, operation_generation, attempt_number,
        receipt_id, outcome, resource_kind, resource_id, resource_version, persisted_at)
      VALUES (p_tenant, p_tenant, event.operation_id, event.operation_generation, event.delivery_attempts,
        'success', 'succeeded', 'workspaceSnapshot', event.aggregate_id, next_revision, settled_at);
      outbox_state := 'delivered'; operation_state := 'succeeded'; resource_version := next_revision;
    ELSE
      PERFORM * FROM cloud_agents.transition_outbox_claim(p_tenant, p_event, p_holder, p_incarnation, p_token, p_expiry,
        CASE WHEN p_transition = 'retry' THEN 'delivery_failed_retryable' ELSE 'delivery_failed_terminal' END,
        CASE WHEN p_transition = 'failed' THEN p_error END, p_subject, p_audit);
      UPDATE cloud_agents.operation_attempts SET state = 'failed', claim_holder_id = NULL, claim_incarnation = NULL,
        claim_token = NULL, claim_started_at = NULL, claim_expires_at = NULL, stable_error_code = p_error,
        updated_at = settled_at, terminal_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation AND attempt_number = event.delivery_attempts;
      UPDATE cloud_agents.workspace_snapshots SET status = CASE WHEN p_transition = 'retry' THEN 'unknown' ELSE 'failed' END,
        physical_snapshot_uid = NULL, content_digest = NULL, size_bytes = NULL,
        stable_error_code = CASE WHEN p_transition = 'retry' THEN NULL ELSE p_error END,
        updated_at = settled_at, observed_at = settled_at
      WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND snapshot_uid = event.aggregate_id;
      IF p_transition = 'retry' THEN
        UPDATE cloud_agents.platform_operations SET state = 'reconciling', updated_at = settled_at
        WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
        outbox_state := 'retry_wait'; operation_state := 'reconciling'; resource_version := NULL;
      ELSE
        UPDATE cloud_agents.sandbox_sessions AS source SET writer_released = true
        FROM cloud_agents.workspace_snapshots AS snapshot
        WHERE snapshot.tenant_id = p_tenant AND snapshot.operation_id = event.operation_id
          AND source.tenant_id = snapshot.tenant_id AND source.project_uid = snapshot.project_uid
          AND source.sandbox_uid = snapshot.source_sandbox_uid AND source.generation = snapshot.source_sandbox_generation
          AND source.desired_state = 'stopped' AND source.observed_state = 'stopped'
          AND source.observed_generation = source.generation AND NOT source.writer_released;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot writer fence drifted'; END IF;
        UPDATE cloud_agents.platform_operations SET state = 'failed', cleanup_phase = CASE WHEN p_cleanup_complete THEN 'complete' ELSE 'blocked' END,
          terminal_error_code = p_error, updated_at = settled_at, terminal_at = settled_at
        WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
        UPDATE cloud_agents.operation_finalizers SET state = CASE WHEN p_cleanup_complete THEN 'succeeded' ELSE 'dead_letter' END,
          stable_error_code = CASE WHEN p_cleanup_complete THEN NULL ELSE p_error END, updated_at = settled_at, terminal_at = settled_at
        WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
        UPDATE cloud_agents.idempotency_records SET state = 'failed', stable_error_code = p_error, updated_at = settled_at, terminal_at = settled_at
        WHERE tenant_id = p_tenant AND operation_id = event.operation_id AND operation_generation = event.operation_generation;
        INSERT INTO cloud_agents.terminal_receipts (tenant_id, tenant_ref_id, operation_id, operation_generation, attempt_number,
          receipt_id, outcome, stable_error_code, persisted_at)
        VALUES (p_tenant, p_tenant, event.operation_id, event.operation_generation, event.delivery_attempts,
          'failure', 'failed', p_error, settled_at);
        outbox_state := 'dead_letter'; operation_state := 'failed'; resource_version := NULL;
      END IF;
    END IF;
    RETURN NEXT;
END;
$$;

CREATE FUNCTION cloud_agents.reap_foundation_workspace_snapshot_claim_v1(p_subject text, p_audit text)
RETURNS TABLE (tenant_id text, event_id text, outbox_state text, delivery_attempts integer)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, cloud_agents
AS $$
DECLARE reaped_at timestamptz := transaction_timestamp(); candidate cloud_agents.outbox_events%ROWTYPE; error_code constant text := 'workspace_snapshot_claim_expired';
BEGIN
    PERFORM cloud_agents.require_runtime_mutation_principal();
    IF p_subject !~ '^sha256:[0-9a-f]{64}$' OR NOT cloud_agents.is_valid_identifier(p_audit)
    THEN RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'workspace snapshot reaper is invalid'; END IF;
    SELECT event.* INTO candidate FROM cloud_agents.outbox_events AS event
    WHERE event.profile_id = 'foundationWorkspaceSnapshot/v1alpha1' AND event.profile_digest = 'sha256:76432dc8e1962f28c4679c70fb4bcedc93171945ff816f625fb4c66aed3c177f'
      AND event.event_class = 'operation_effect' AND event.aggregate_kind = 'workspaceSnapshot'
      AND event.state = 'claimed' AND event.claim_expires_at <= reaped_at
    ORDER BY event.claim_expires_at, event.tenant_id, event.event_id FOR UPDATE SKIP LOCKED LIMIT 1;
    IF NOT FOUND THEN RETURN; END IF;
    PERFORM pg_catalog.set_config('cloud_agents.tenant_id', candidate.tenant_id, true);
    UPDATE cloud_agents.operation_attempts SET state = CASE WHEN candidate.delivery_attempts < 8 THEN 'unknown' ELSE 'failed' END,
      claim_holder_id = NULL, claim_incarnation = NULL, claim_token = NULL, claim_started_at = NULL, claim_expires_at = NULL,
      stable_error_code = CASE WHEN candidate.delivery_attempts < 8 THEN NULL ELSE error_code END, updated_at = reaped_at,
      terminal_at = CASE WHEN candidate.delivery_attempts < 8 THEN NULL ELSE reaped_at END
    WHERE tenant_id = candidate.tenant_id AND operation_id = candidate.operation_id
      AND operation_generation = candidate.operation_generation AND attempt_number = candidate.delivery_attempts AND state = 'claimed';
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot attempt authority drifted'; END IF;
    UPDATE cloud_agents.workspace_snapshots SET status = CASE WHEN candidate.delivery_attempts < 8 THEN 'unknown' ELSE 'failed' END,
      physical_snapshot_uid = NULL, content_digest = NULL, size_bytes = NULL,
      stable_error_code = CASE WHEN candidate.delivery_attempts < 8 THEN NULL ELSE error_code END,
      updated_at = reaped_at, observed_at = reaped_at
    WHERE tenant_id = candidate.tenant_id AND operation_id = candidate.operation_id AND snapshot_uid = candidate.aggregate_id;
    IF candidate.delivery_attempts < 8 THEN
      outbox_state := 'pending';
      UPDATE cloud_agents.outbox_events SET state = 'pending', claim_holder_id = NULL, claim_incarnation = NULL,
        claim_token = NULL, claim_started_at = NULL, claim_expires_at = NULL, stable_error_code = NULL, updated_at = reaped_at
      WHERE tenant_id = candidate.tenant_id AND event_id = candidate.event_id;
      UPDATE cloud_agents.platform_operations SET state = 'reconciling', updated_at = reaped_at
      WHERE tenant_id = candidate.tenant_id AND operation_id = candidate.operation_id AND operation_generation = candidate.operation_generation;
    ELSE
      outbox_state := 'dead_letter';
      UPDATE cloud_agents.sandbox_sessions AS source SET writer_released = true
      FROM cloud_agents.workspace_snapshots AS snapshot
      WHERE snapshot.tenant_id = candidate.tenant_id AND snapshot.operation_id = candidate.operation_id
        AND source.tenant_id = snapshot.tenant_id AND source.project_uid = snapshot.project_uid
        AND source.sandbox_uid = snapshot.source_sandbox_uid AND source.generation = snapshot.source_sandbox_generation
        AND source.desired_state = 'stopped' AND source.observed_state = 'stopped'
        AND source.observed_generation = source.generation AND NOT source.writer_released;
      IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'workspace snapshot writer fence drifted'; END IF;
      UPDATE cloud_agents.outbox_events SET state = 'dead_letter', claim_holder_id = NULL, claim_incarnation = NULL,
        claim_token = NULL, claim_started_at = NULL, claim_expires_at = NULL, stable_error_code = error_code,
        dead_lettered_at = reaped_at, updated_at = reaped_at
      WHERE tenant_id = candidate.tenant_id AND event_id = candidate.event_id;
      UPDATE cloud_agents.platform_operations SET state = 'failed', cleanup_phase = 'blocked', terminal_error_code = error_code,
        updated_at = reaped_at, terminal_at = reaped_at
      WHERE tenant_id = candidate.tenant_id AND operation_id = candidate.operation_id AND operation_generation = candidate.operation_generation;
      UPDATE cloud_agents.operation_finalizers SET state = 'dead_letter', delivery_attempts = candidate.delivery_attempts,
        stable_error_code = error_code, updated_at = reaped_at, terminal_at = reaped_at
      WHERE tenant_id = candidate.tenant_id AND operation_id = candidate.operation_id AND operation_generation = candidate.operation_generation;
      UPDATE cloud_agents.idempotency_records SET state = 'failed', stable_error_code = error_code, updated_at = reaped_at, terminal_at = reaped_at
      WHERE tenant_id = candidate.tenant_id AND operation_id = candidate.operation_id AND operation_generation = candidate.operation_generation;
      INSERT INTO cloud_agents.terminal_receipts (tenant_id, tenant_ref_id, operation_id, operation_generation, attempt_number,
        receipt_id, outcome, stable_error_code, persisted_at)
      VALUES (candidate.tenant_id, candidate.tenant_id, candidate.operation_id, candidate.operation_generation,
        candidate.delivery_attempts, 'expired', 'failed', error_code, reaped_at);
    END IF;
    PERFORM cloud_agents.append_coordination_audit(candidate.tenant_id, p_audit, candidate.profile_id, candidate.profile_digest,
      p_subject, candidate.operation_id, candidate.operation_generation, candidate.delivery_attempts,
      NULL, NULL, NULL, 'workspace.snapshot.reap', CASE WHEN candidate.delivery_attempts < 8 THEN 'pending' ELSE 'failed' END,
      CASE WHEN candidate.delivery_attempts < 8 THEN NULL ELSE error_code END, NULL, reaped_at);
    tenant_id := candidate.tenant_id; event_id := candidate.event_id; delivery_attempts := candidate.delivery_attempts; RETURN NEXT;
END;
$$;

ALTER FUNCTION cloud_agents.accept_foundation_workspace_snapshot_v1(text,text,text,bigint,text,text,text) OWNER TO cloud_agents_migration_owner;
ALTER FUNCTION cloud_agents.claim_foundation_workspace_snapshot_v1(text,text,text,integer,text,text) OWNER TO cloud_agents_migration_owner;
ALTER FUNCTION cloud_agents.renew_foundation_workspace_snapshot_claim_v1(text,text,text,text,text,timestamptz,integer) OWNER TO cloud_agents_migration_owner;
ALTER FUNCTION cloud_agents.settle_foundation_workspace_snapshot_v1(text,text,text,text,text,timestamptz,text,text,text,bigint,text,boolean,text,text) OWNER TO cloud_agents_migration_owner;
ALTER FUNCTION cloud_agents.reap_foundation_workspace_snapshot_claim_v1(text,text) OWNER TO cloud_agents_migration_owner;
REVOKE ALL ON FUNCTION cloud_agents.accept_foundation_workspace_snapshot_v1(text,text,text,bigint,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION cloud_agents.claim_foundation_workspace_snapshot_v1(text,text,text,integer,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION cloud_agents.renew_foundation_workspace_snapshot_claim_v1(text,text,text,text,text,timestamptz,integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION cloud_agents.settle_foundation_workspace_snapshot_v1(text,text,text,text,text,timestamptz,text,text,text,bigint,text,boolean,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION cloud_agents.reap_foundation_workspace_snapshot_claim_v1(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION cloud_agents.accept_foundation_workspace_snapshot_v1(text,text,text,bigint,text,text,text) TO cloud_agents_runtime;
GRANT EXECUTE ON FUNCTION cloud_agents.claim_foundation_workspace_snapshot_v1(text,text,text,integer,text,text) TO cloud_agents_runtime;
GRANT EXECUTE ON FUNCTION cloud_agents.renew_foundation_workspace_snapshot_claim_v1(text,text,text,text,text,timestamptz,integer) TO cloud_agents_runtime;
GRANT EXECUTE ON FUNCTION cloud_agents.settle_foundation_workspace_snapshot_v1(text,text,text,text,text,timestamptz,text,text,text,bigint,text,boolean,text,text) TO cloud_agents_runtime;
GRANT EXECUTE ON FUNCTION cloud_agents.reap_foundation_workspace_snapshot_claim_v1(text,text) TO cloud_agents_runtime;
